### PR TITLE
Improve import time

### PR DESCRIPTION
**Pull request by marscher**
- by avoiding import lifts
- doing as much imports lazy (when an API function is called)

I'm not sure if we're going to break peoples code by doing so, but anyway users should call the api functions directly instead of importing implementation details.

### CODE REVIEW

**Comment by franknoe** [comment]
Lazy imports are fine, but I am clearly against avoiding the lifts. They were done deliberately, i.e. having easy access to objects are part of the design. I disagree that everything should be done by api functions, they are just a convenience option very much like in sklearn.

**Comment by marscher** [comment]
As you suggested, I rebased out the commit of import lifting removal.

**Comment by franknoe** [comment]
ok!

**Comment by marscher** [comment]
https://pypi.python.org/pypi/Importing/1.10 this can be interesting for us!

**Pull request merged**
