### PR TITLE
[plot.timescales] added optional argument marker and markersize

### PR DESCRIPTION
**Pull request by gph82**

### CODE REVIEW

**Comment by marscher** [comment]
Shouldn't we just pass a **kwargs to pyplot to allow the advanced user 
to give arbitrary arguments?

**Comment by gph82** [comment]
yes, yes we should indeed
. I'll close and reopen when done

On 18.06.2015 12:18, Martin K. Scherer wrote:

> Shouldn't we just pass a **kwargs to pyplot to allow the advanced user
> to give arbitrary arguments?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/pull/366#issuecomment-113100181.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

## http://userpage.fu-berlin.de/gph82/

**Comment by marscher** [comment]
Why is it common sense to close a pull request after only one point of 
criticism has been given? The creator of the PR can just update this and 
continue the discussion where it has started.

**Comment by gph82** [comment]
Sorry, I thought it was...( #349). Anyway, implemented *kwargs now

**Comment by marscher** [comment]
Actually it would be nice, if all of your plotting functions would accept kwargs to have a standard interface.

**Pull request merged**
