### PR TITLE
Refactor model estimator

### PR DESCRIPTION
**Pull request by franknoe**
This PR is huge. It contains all changes to the Model / Estimator infrastructure that we have discussed. I have rebased the branch to be merged onto dev_release_1.3. In order to have to redo an extensive merge or rebase and resolve conflicts, accepting this branch means two things:
- future improvements should go to this branch and not to devel, until we decide to merge into devel
- we cannot replay the rebase of dev_release_1.3 onto devel. So don't accept this PR for now if this is an issue.

Note that this branch requires an install of the devel version of bhmm to function. For this reason there will be an error in the automatic tests that cannot be avoided until these features end up in a bhmm release.

### CODE REVIEW

**Comment by marscher** [comment]
We can change travis and appveyor to install a git version, but I'd prefer a new release (maybe a patch-level one).

A few minutes ago Ben and I have successfully extracted the msmtools package and I'd love to remove the parts from Pyemma which are redundant now. I'll suggest doing this after the merge of this PR and use the latest state for doing the refactoring/deletion.

The history of this PR seems very cluttered with tiny commits, which can be squashed together via git rebase -i.

**Comment by franknoe** [comment]
Am 08/07/15 um 16:42 schrieb Martin K. Scherer:

> We can change travis and appveyor to install a git version, but I'd 
> prefer a new release (maybe a patch-level one).
> 
> I agree. I just said this to make clear that we shouldn't expect zero 
> errors in the automatic tests.
> 
> A few minutes ago Ben and I have successfully extracted the msmtools 
> package and I'd love to remove the parts from Pyemma which are 
> redundant now. I'll suggest doing this after the merge of this PR and 
> use the latest state for doing the refactoring/deletion.
> 
> OK!
> 
> The history of this PR seems very cluttered with tiny commits, which 
> can be squashed together via git rebase -i.
> 
> OK. Is this a comment for the future or should I do something?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/402#issuecomment-119607104.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I'll suggest cleaning up the history of this one, since it probably contains a lot of refactoring along the road which are not really interesting for future developments.

So what you should do is call rebase -i on this branch. This pops up the editor of your choice where you can choose for each commit, either it should be taken into account (# comment it out if not), squash it into the previous one (maintaining the commit message) or fix up, which takes the content but not the message.

For such a huge history, this is a long taking task, so we can consider squashing to whole thing together in one commit to save time.

**Comment by franknoe** [comment]
OK, I'll do this in a minute... I have to give a talk first

Am 08/07/15 um 16:49 schrieb Martin K. Scherer:

> I'll suggest cleaning up the history of this one, since it probably 
> contains a lot of refactoring along the road which are not really 
> interesting for future developments.
> 
> So what you should do is call rebase -i on this branch. This pops up 
> the editor of your choice where you can choose for each commit, either 
> it should be taken into account (# comment it out if not), squash it 
> into the previous one (maintaining the commit message) or fix up, 
> which takes the content but not the message.
> 
> For such a huge history, this is a long taking task, so we can 
> consider squashing to whole thing together in one commit to save time.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/402#issuecomment-119609850.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
the bhmm repo is prohibitively huge to use it for travis (several hundreds of MB). So please make a new patch release

**Comment by franknoe** [comment]
We first need to separate the core package from the application package. 
This repo is so large because it contains paper pdfs and references that 
have nothing to do with the code.

Why is this a pyEMMA issue?

Am 08/07/15 um 16:54 schrieb Martin K. Scherer:

> the bhmm repo is prohibitively huge to use it for travis (several 
> hundreds of MB). So please make a new patc
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/402#issuecomment-119612038.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Our tests fail, because of a not yet released bhmm feature.

**Comment by franknoe** [comment]
I get this result. What should I do?

panda:pyemma noe$ git rebase -i
There is no tracking information for the current branch.
Please specify which branch you want to rebase against.
See git-rebase(1) for details

```
 git rebase <branch>
```

If you wish to set tracking information for this branch you can do so with:

```
 git branch --set-upstream-to=origin/<branch> refactor_model_estimator
```

Am 08/07/15 um 16:49 schrieb Martin K. Scherer:

> I'll suggest cleaning up the history of this one, since it probably 
> contains a lot of refactoring along the road which are not really 
> interesting for future developments.
> 
> So what you should do is call rebase -i on this branch. This pops up 
> the editor of your choice where you can choose for each commit, either 
> it should be taken into account (# comment it out if not), squash it 
> into the previous one (maintaining the commit message) or fix up, 
> which takes the content but not the message.
> 
> For such a huge history, this is a long taking task, so we can 
> consider squashing to whole thing together in one commit to save time.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/402#issuecomment-119609850.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Sure, but we need to do something on bhmm to make the bhmm repo smaller.

Am 08/07/15 um 17:06 schrieb Martin K. Scherer:

> Our tests fail, because of a not yet released bhmm feature.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/402#issuecomment-119617002.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
One can drag the large files out into a second repo and include is as a submodule. So only if one is interested in those files, one can clone it.

**Comment by franknoe** [comment]
Good idea. But the bhmm core module won't depend on any large files, so 
we won't need to do that.

Am 08/07/15 um 17:16 schrieb Martin K. Scherer:

> One can drag the large files out into a second repo and include is as 
> a submodule. So only if one is interested in those files, one can 
> clone it.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/402#issuecomment-119621125.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I'm talking about the cluttered bhmm git repo and you?

**Comment by franknoe** [comment]
yes, the same. But that's a bhmm issue and not a pyemma issue, so we can 
close this.

Am 08/07/15 um 17:34 schrieb Martin K. Scherer:

> I'm talking about the cluttered bhmm git repo and you?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/402#issuecomment-119627954.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
I don't know what to do here. Do you mean to use the -i option during 
the rebase?
Please not this rebase has already happened, and I won't redo it because 
there were a lot of merge conflicts that needed nontrivial fixing. If we 
can't compress the commit history a posteriori, we'll have to leave it 
as it is.

Am 08/07/15 um 16:49 schrieb Martin K. Scherer:

> I'll suggest cleaning up the history of this one, since it probably 
> contains a lot of refactoring along the road which are not really 
> interesting for future developments.
> 
> So what you should do is call rebase -i on this branch. This pops up 
> the editor of your choice where you can choose for each commit, either 
> it should be taken into account (# comment it out if not), squash it 
> into the previous one (maintaining the commit message) or fix up, 
> which takes the content but not the message.
> 
> For such a huge history, this is a long taking task, so we can 
> consider squashing to whole thing together in one commit to save time.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/402#issuecomment-119609850.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
P.S.: I don't think you need to wait with with the merge for a new bhmm release. This is still a feature branch like refactor_model_estimator was a feature branch before.

**Comment by franknoe** [comment]
@jchodera has extracted the bhmm core package: https://github.com/bhmm/bhmm

**Comment by marscher** [comment]
thank you @jchodera! Now the tests are passing.

**Comment by franknoe** [comment]
great

Am 09/07/15 um 16:45 schrieb Martin K. Scherer:

> thank you @jchodera https://github.com/jchodera! Now the tests are 
> passing.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/402#issuecomment-120008830.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
the history of this PR is some how duplicated. The same commits appear twice with different hashes. Since you did 99,9% of the work, would you like to `git checkout dev_release_1.3; git merge --squash refactor_model_estimator` to shrink the history to one commit and give yourself the credit for it?

**Comment by marscher** [comment]
please pull once before you do that.

**Comment by franknoe** [comment]
Sure, let me try ...

Am 09/07/15 um 16:56 schrieb Martin K. Scherer:

> the history of this PR is some how duplicated. The same commits appear 
> twice with different hashes. Since you did 99,9% of the work, would 
> you like to |git checkout dev_release_1.3; git merge --squash 
> refactor_model_estimator| to shrink the history to one commit and give 
> yourself the credit for it?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/402#issuecomment-120013961.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
OK, looks good (see below). Should I now commit and push normally?

```
panda:pyemma noe$ git merge --squash refactor_model_estimator
Auto-merging pyemma/msm/util/__init__.py
Removing pyemma/msm/ui/timescales_test.py
Removing pyemma/msm/ui/timescales.py
Removing pyemma/msm/ui/msm_test.py
Removing pyemma/msm/ui/msm.py
Squash commit -- not updating HEAD
Automatic merge went well; stopped before committing as requested
```

Am 09/07/15 um 16:56 schrieb Martin K. Scherer:

> the history of this PR is some how duplicated. The same commits appear 
> twice with different hashes. Since you did 99,9% of the work, would 
> you like to |git checkout dev_release_1.3; git merge --squash 
> refactor_model_estimator| to shrink the history to one commit and give 
> yourself the credit for it?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/402#issuecomment-120013961.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
yes, you might consider writing a summary for the commit message, since
the auto-generated message consists only out of the squashed commit
messages.

**Comment by marscher** [comment]
merged manually

**Pull request closed without merging**
