### PR TITLE
[coor|tica|variational] check for rank zero correlation matrices

### LINKED ISSUE #1053: TICA error message when only 0's are passed
One of our users made a projection that was 0 for all frames/trajectories (no residues ever came in contact). Obviously TICA cannot find anything in that degenerate space. Would be awesome if you could handle this case and print out a more meaningful message because the current one is a bit obscure.

Thanks! 

```pytb
/shared/sdoerr/Software/anaconda3/lib/python3.5/site-packages/pyemma/_base/estimator.py in fit(self, X)
    386 
    387         """
--> 388         return self.estimate(X)
    389 
    390     @property

/shared/sdoerr/Software/anaconda3/lib/python3.5/site-packages/pyemma/coordinates/transform/tica.py in estimate(self, X, **kwargs)
    211         the independent components.
    212         """
--> 213         return super(TICA, self).estimate(X, **kwargs)
    214 
    215     def partial_fit(self, X):

/shared/sdoerr/Software/anaconda3/lib/python3.5/site-packages/pyemma/coordinates/data/_base/transformer.py in estimate(self, X, **kwargs)
    226     """ Basis class for pipelined Transformers, which perform also estimation. """
    227     def estimate(self, X, **kwargs):
--> 228         super(StreamingEstimationTransformer, self).estimate(X, **kwargs)
    229         # we perform the mapping to memory exactly here, because a StreamingEstimator on its own
    230         # has not output to be mapped. Only the combination of Estimation/Transforming has this feature.

/shared/sdoerr/Software/anaconda3/lib/python3.5/site-packages/pyemma/coordinates/data/_base/streaming_estimator.py in estimate(self, X, **kwargs)
     49         # run estimation
     50         try:
---> 51             super(StreamingEstimator, self).estimate(X, **kwargs)
     52         except NotConvergedWarning as ncw:
     53             self._logger.info(

/shared/sdoerr/Software/anaconda3/lib/python3.5/site-packages/pyemma/_base/estimator.py in estimate(self, X, **params)
    364         if params:
    365             self.set_params(**params)
--> 366         self._model = self._estimate(X)
    367         self._estimated = True
    368         return self

/shared/sdoerr/Software/anaconda3/lib/python3.5/site-packages/pyemma/coordinates/transform/tica.py in _estimate(self, iterable, **kw)
    258                                         cov=self._covar.cov,
    259                                         cov_tau=self._covar.cov_tau)
--> 260         self._diagonalize()
    261 
    262         return self._model

/shared/sdoerr/Software/anaconda3/lib/python3.5/site-packages/pyemma/coordinates/transform/tica.py in _diagonalize(self)
    283         # diagonalize with low rank approximation
    284         self._logger.debug("diagonalize Cov and Cov_tau.")
--> 285         eigenvalues, eigenvectors = eig_corr(self._covar.cov, self._covar.cov_tau, self.epsilon, sign_maxelement=True)
    286         if self.kinetic_map and self.commute_map:
    287             raise ValueError('Trying to use both kinetic_map and commute_map. Use either or.')

/shared/sdoerr/Software/anaconda3/lib/python3.5/site-packages/pyemma/_ext/variational/solvers/direct.py in eig_corr(C0, Ct, epsilon, method, sign_maxelement)
    156     if _np.allclose(Ct.T, Ct):
    157         from scipy.linalg import eigh
--> 158         l, R_trans = eigh(Ct_trans)
    159     else:
    160         from scipy.linalg import eig

/shared/sdoerr/Software/anaconda3/lib/python3.5/site-packages/scipy/linalg/decomp.py in eigh(a, b, lower, eigvals_only, overwrite_a, overwrite_b, turbo, eigvals, type, check_finite)
    343         if eigvals is None:
    344             w, v, info = evr(a1, uplo=uplo, jobz=_job, range="A", il=1,
--> 345                              iu=a1.shape[0], overwrite_a=overwrite_a)
    346         else:
    347             (lo, hi) = eigvals

ValueError: failed to create intent(cache|hide)|optional array-- must have defined dimensions but got (0,)
```

### PR DESCRIPTION
**Pull request by fabian-paul**
fixes #1053 
Comments and suggestions welcome.

### CODE REVIEW

**Comment by marscher** [comment]
great! Thank you.

**Comment by fabian-paul** [comment]
The tests fail because of this doctest (?)
https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/__init__.py#L51

**Comment by marscher** [comment]
It is IT maintainence day and therefore the file needed in this test can not be downloaded :+1:

**Comment by marscher** [comment]
But probably I should move this test to a separate unit and provide a tiny test file

**Comment by marscher** [comment]
The failure is unrelated. Merging.

**Pull request merged**
