### PR TITLE
Enable subset to handle active sets in pyemma.thermo

### PR DESCRIPTION
**Pull request by cwehmeyer**

### CODE REVIEW

**Comment by cwehmeyer** [comment]
@marscher do you want to add anything before we merge?

**Comment by marscher** [comment]
well, the new subset is pretty much untested (33% coverage). I thought it should be used by the feature in thermo (which then itself seems untested).

**Comment by marscher** [comment]
The unittest for subset is in _base, which is ignored by nosetest stupidity...

**Comment by marscher** [comment]
nose-devs/nose/issues/963

**Comment by marscher** [comment]
Please do not merge, this is broken...

**Comment by marscher** [comment]
We can merge this now, right? @cwehmeyer

**Comment by cwehmeyer** [comment]
Not yet. We need to address some new issues with this.

**Pull request merged**
