### PR TITLE
Fix timescale tolerances

### PR DESCRIPTION
**Pull request by trendelkampschroer**
[msm/analysis] Set floating point tolerance to distinguish unit eigenvalues from eigenvalues<1 in timescales computation to tol=1e-14

### CODE REVIEW

**Comment by franknoe** [comment]
Thanks.

**Comment by trendelkampschroer** [comment]
Did you merge?

**Comment by franknoe** [comment]
yes

Am 07/05/15 um 15:56 schrieb Benjamin Trendelkamp-Schroer:

> Did you merge?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/298#issuecomment-99876803.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Ah, I need to click twice, there is a confirm merge after merge. Now it 
is done.

Am 07/05/15 um 15:56 schrieb Benjamin Trendelkamp-Schroer:

> Did you merge?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/298#issuecomment-99876803.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by trendelkampschroer** [comment]
Thanks

**Pull request merged**
