### PR TITLE
[tica] added implied timescales attribute

### PR DESCRIPTION
**Pull request by gph82**
I think this is nice

### CODE REVIEW

**Comment by franknoe** [comment]
There is a minus missing. Your timescales are negative

**Comment by gph82** [comment]
OMG, that's right, even in the test! (which BTW I'm renaming because it had a wrong name)

**Comment by gph82** [comment]
Just updated the PR after merging with dev_release_1.3 We should be okay

**Comment by gph82** [comment]
scratch that. I'll take care of it later

**Comment by gph82** [comment]
I think you have to revert this, @marscher

**Comment by marscher** [comment]
Am 29.07.2015 um 19:15 schrieb Guillermo Pérez-Hernández:

**Comment by gph82** [comment]
tests are failing...for reasons

**Comment by marscher** [comment]
Will fix it on the branch directly. Thanks!

**Pull request merged**
