### PR TITLE
[featurizer.pairs] opt arg excluded_neighbors added, default behaviour changed

### PR DESCRIPTION
**Pull request by gph82**
This closes #478. @franknoe , if I set default exclusions=0 tests break. Might be that people are already using it that way. I'd suggest we leave it like this for now. The entire "pairwise_parse" area will be a bit of construction site once I have more time (hTICA needs very good handling of this)

### CODE REVIEW

**Comment by franknoe** [comment]
Aren't the tests just failing because they assume excluded_neighbors=2? So they should work if you just call pairs with excluded_neighbors=2 in the tests.

I'm all for doing it right immediately. The reason we had pairs in the beginning was to compute residue pairs, and then it makes sense to exclude one or two neighbors. But I think pairs is used in a more general way, e.g. for computing atoms pairs, and then excluding 1- and 2-neighbors might mean nothing, because they might not be neighbors in the structure.

**Comment by gph82** [comment]
"Aren't the tests just failing because they assume excluded_neighbors=2? So they should work if you just call pairs with excluded_neighbors=2 in the tests."

It's not that I don't know how to make the tests work, sorry, i meant that we're essentially changing the api call. Now we don't have that many users, but I guess one should avoid it, right? I'll update the test and the default before we merge.

**Comment by franknoe** [comment]
Yes, one should be careful with changes, but I think it's OK to change 
default behavior when it makes sense. That will not crash people's codes 
and make the data processing only minimally more expensive. In our 
initial implementation of the pairs function we simply haven't though 
about this.

Am 03/08/15 um 22:03 schrieb Guillermo Pérez-Hernández:

> "Aren't the tests just failing because they assume 
> excluded_neighbors=2? So they should work if you just call pairs with 
> excluded_neighbors=2 in the tests."
> 
> It's not that I don't know how to make the tests work, sorry, i meant 
> that we're essentially changing the api call. Now we don't have that 
> many users, but I guess one should avoid it, right? I'll update the 
> test and the default before we merge.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/479#issuecomment-127390474.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
on it

**Comment by gph82** [comment]
we should at least put it in the changelog. Are we systematically doing changelog entries, or on a case-by-case basis?

**Comment by franknoe** [comment]
sure, put it in. So far the changelog has been mostly ad hoc and 
described the general changes, but I think Martin has dug up a way to 
generate changelogs out of commit messages.

Am 03/08/15 um 22:16 schrieb Guillermo Pérez-Hernández:

> we should at least put it in the changelog. Are we systematically 
> doing changelog entries, or on a case-by-case basis?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/479#issuecomment-127395111.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
The commit message was wrong. Now we can merge

**Comment by gph82** [comment]
I am a bit confused as to why this PR now shows also @fabian-paul 's changes...

**Comment by gph82** [comment]
Hi, can someone merge this? This keeps me from developing smaller fixes on my devel branch

**Comment by franknoe** [comment]
I have to wait for the AppVeyor build. That can unfortunately take a while - apparently the freely available server resources are insufficient.

**Comment by franknoe** [comment]
What about leaving the add_distances_ca() unchanged by adding excluded_neighbors=2 as a kwarg and passing that to the neighbor calculation? For Ca's it does make sense to leave out neighbors because they are ordered.

**Comment by gph82** [comment]
At this moment, the complexity of doing this in my tree is much larger than merging and doing that request again. I don't have mergetools in my system (because of an update)

**Comment by gph82** [comment]
thanks!

**Pull request merged**
