### PR TITLE
fit transform for list of ndarrays

### PR DESCRIPTION
**Pull request by clonker**
Changed the transformer to allow a list of ndarrays upon estimate call and added a test for that.

Also, changed the sklearn/base fit_transform implementation, such that transform gets called on self, rather on what estimate returns, as the returned value might be a model (that does not have a transform method). Or am I mixing something up here and the model should indeed have a transform method?

This should deal with issue #752.

### CODE REVIEW

**Comment by franknoe** [comment]
I'll have a look. In principle we shouldn't touch sklearn/base, this is 
just a copy of the sklearn base class to ensure compatibility with 
sklearn without creating a package dependency.

Am 31/03/16 um 17:06 schrieb Moritz Hoffmann:

> Changed the transformer to allow a list of ndarrays upon estimate call 
> and added a test for that.
> 
> Also, changed the sklearn/base fit_transform implementation, such that 
> transform gets called on self, rather on what estimate returns, as the 
> returned value might be a model (that does not have a transform 
> method). Or am I mixing something up here and the model should indeed 
> have a transform method?
> 
> This should deal with issue #752 
> https://github.com/markovmodel/PyEMMA/issues/752.
> 
> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
> https://github.com/markovmodel/PyEMMA/pull/753
> 
> ```
>     Commit Summary
> ```
> - [transformer] allow lists of ndarrays in estimate
>   
>   ```
>   File Changes
>   ```
> - _M_ pyemma/_ext/sklearn/base.py
>   https://github.com/markovmodel/PyEMMA/pull/753/files#diff-0 (6)
> - _M_ pyemma/coordinates/tests/test_tica.py
>   https://github.com/markovmodel/PyEMMA/pull/753/files#diff-1 (9)
> - _M_ pyemma/coordinates/transform/transformer.py
>   https://github.com/markovmodel/PyEMMA/pull/753/files#diff-2 (5)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/markovmodel/PyEMMA/pull/753.patch
> - https://github.com/markovmodel/PyEMMA/pull/753.diff
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/753

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by clonker** [comment]
Alright, thanks!

**Comment by franknoe** [comment]
Since `self.fit(X, **fit_params).transform(X)` is the sklearn behavior, our code should implement that in order to be compatible. In terms of the Model/Estimator/Transformer nomenclature I think that a transformer is a specific model, so an estimator that estimates a transformer, should also return (at least) a transformer, and thus the return value of it's fit function is expect to implement `transform()`.

So far for generics. I haven't gone through the code yet to see if there is a problem with that.

**Comment by franknoe** [comment]
@clonker , any idea why only one test is triggered here?

**Comment by clonker** [comment]
That makes sense, I will revert the changes on sklearn/base. :-)
The only reason I made them in the first place however, is that at least the tica model being returned by estimate() does not provide a transform() method, leading to an exception when calling fit_transform.

As for the tests, im not sure why they don't get triggered.. in travis the settings are correctly set to build pull requests. Perhaps it is a problem with travis itself.

**Comment by franknoe** [comment]
I think there is a problem with the Estimator/Model concept in the current code. The estimate and fit routine of an estimator should return self (i.e. an estimator), with the model being fitted and available. For example, in TICA the properties `cov` and `cov_tau` will be available after the fit. However the following example should work too:

``` python
tica = TICA(lag=10, dim=5).fit(X)
print tica.lag
```

which requires that the estimator is being returned because lag is a property of the estimator. Same with PCA.

Conceptually, Estimators are the base. An estimator fit should always return the estimator. Having Models as separate objects is something optional which may have some advantages, e.g. when sampling models (e.g. BayesianMSM). A Transformer should be a subclass of Model, but not of Estimator (there is no reason why a Transformer needs to be estimated).

Transformers and Models can be Mixins that can be added to an Estimator.

Let me know if these explanations are sufficient to adapt the code. If not, it may be easier to meet in person tomorrow or so.

**Comment by clonker** [comment]
So I think I have changed the relevant parts, but please correct me if I'm wrong.
- The `estimate` method in the msm part of pyemma does return only `self`, whereas the it returned `self.model` in the coordinates package. I changed that to `self`. 
- Concerning the Transformers, I have removed that the coordinates base Transformer extends Estimator, however the StreamingTransformer still does (since it first needs to get estimated and then can transform data).

**Comment by clonker** [comment]
By the way: Travis seems to build ([here](https://travis-ci.org/markovmodel/PyEMMA/builds/120027768)), however it does not pop up as pending check in the PR.. odd..

**Comment by franknoe** [comment]
Am 01/04/16 um 11:58 schrieb Moritz Hoffmann:

> So I think I have changed the relevant parts, but please correct me if 
> I'm wrong.
> - The |estimate| method in the msm part of pyemma does return only
>   |self|, whereas the it returned |self.model| in the coordinates
>   package. I changed that to |self|.
> 
> correct.
> - Concerning the Transformers, I have removed that the coordinates
>   base Transformer extends Estimator, however the
>   StreamingTransformer still does (since it first needs to get
>   estimated and then can transform data).
> 
> That's right. The StreamingTransformer is an Estimator, the 
> "Streaming..." part of the name indicates that (stream from data). But 
> the name is not very self-explanatory. If anyone has an idea for a 
> self-explanatory name that is not very long, I'd be happy to hear about it.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/753#issuecomment-204335674

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Thanks! Merging now.

**Comment by franknoe** [comment]
Fixes #752

**Pull request merged**
