### PR TITLE
Sqlite db backend for TrajInfo (len, dim, offsets)

### PR DESCRIPTION
**Pull request by marscher**
- Tested with 8 different nodes in parallel, which all write to the same file and it worked like a charm.
- Introduced a new configuration variables to set maximum entries in DB or max size. If that number is reached the n oldest entries will be removed.

### CODE REVIEW

**Comment by franknoe** [comment]
Cool stuff! But since we're on a tight deadline with a release that contains TRAM and this has not been tested in actual use, I would strongly vote for postponing this to the next release. It's not a feature that is essential for function - just good to have.
Do your tests also include situations where sqlite is _not_ available to see that this is handled correctly?

Present test failures are mainly due to printing progress bars when non are expected in the test class.

**Comment by marscher** [comment]
Writing locks the database for a potentially long time, we need to adjust the timeouts appropriately.

To implement a LRU cache, we could add extra databases, which hold the last accessed timestamps for a set of files. Having multiple databases for a range of files (dont know yet how to distribute) will shorten waiting times for updates.

**Comment by marscher** [comment]
The test failures are due to progress bar handling in TRAM. I've merged devel into this branch to ensure I have the latest changes, but still this does not help.

@cwehmeyer Do you maybe have a clue what is going on here?

**Comment by cwehmeyer** [comment]
I have got an idea. Let me think about this...

**Comment by marscher** [comment]
Call for testers @gph82, @franknoe 

I've already tested it with 5 parallel nodes on the same filesystem with now drawbacks and it is pretty fast.

**Comment by franknoe** [comment]
I guess Guille is in the best position to test this.

Am 27/05/16 um 18:17 schrieb Martin K. Scherer:

> Call for testers @gph82 https://github.com/gph82, @franknoe 
> https://github.com/franknoe
> 
> I've already tested it with 5 parallel nodes on the same filesystem 
> with now drawbacks and it is pretty fast.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/798#issuecomment-222189501, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AGMeQvKZCGvP8TWiL3bv6BufzWKOAg-wks5qFxkMgaJpZM4IaT4M.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
@gph82  has tested this with a fairly large dataset and reported no errors. Pending merge.

cc @franknoe

**Comment by gph82** [comment]
A bit late but want to thank @marscher for this. 

I thoroughly tested the parallel access to the sqlite db yesterday by 18 processes across 3 machines.  Creating a reader for ca 30 million frames (ca 5K atoms) went down from 20 hours (this number here #788 ) to ca 1h. 

Thanks!

**Comment by gph82** [comment]
BTW how do I configure the allowed size of the DB on /home/mi/gph82/.pyemma? Is the variable name documented somewhere?

**Comment by marscher** [comment]
yes it is: have a look at pyemma.config

**Comment by gph82** [comment]
awesome, thanks! Just did 

``` python
pyemma.config.traj_info_max_size = 1000
pyemma.config.traj_info_max_entries = 500000
pyemma.config.save('/home/mi/gph82/.pyemma/pyemma.cfg'
```

right?

**Comment by marscher** [comment]
yes, and you can omit the argument in save (default is to save it in the hidden folder in your home directory).

**Pull request merged**
