### PR TITLE
[TICA/Sparsifier] added transparent handling of constant features.

### PR DESCRIPTION
**Pull request by marscher**
This is done via determining if there are potentially constant features in the
input. The data source is being asked, if it is worth looking for constant
features and if so, they are determined in the first pass of TICA.

### CODE REVIEW

**Comment by franknoe** [comment]
thanks, I'll review this.

Am 23/10/15 um 18:54 schrieb Martin K. Scherer:

> This is done via determining if there are potentially constant 
> features in the
> input. The data source is being asked, if it is worth looking for constant
> features and if so, they are determined in the first pass of TICA.
> 
> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
> https://github.com/markovmodel/PyEMMA/pull/586
> 
> ```
>     Commit Summary
> ```
> - [TICA/Sparsifier] added transparent handling of constant features.
>   
>   ```
>   File Changes
>   ```
> - _M_ pyemma/coordinates/data/feature_reader.py
>   https://github.com/markovmodel/PyEMMA/pull/586/files#diff-0 (7)
> - _M_ pyemma/coordinates/data/featurizer.py
>   https://github.com/markovmodel/PyEMMA/pull/586/files#diff-1 (15)
> - _M_ pyemma/coordinates/data/interface.py
>   https://github.com/markovmodel/PyEMMA/pull/586/files#diff-2 (6)
> - _M_ pyemma/coordinates/data/sparsifier.py
>   https://github.com/markovmodel/PyEMMA/pull/586/files#diff-3 (7)
> - _M_ pyemma/coordinates/tests/test_featurereader.py
>   https://github.com/markovmodel/PyEMMA/pull/586/files#diff-4 (10)
> - _M_ pyemma/coordinates/tests/test_sparsifier.py
>   https://github.com/markovmodel/PyEMMA/pull/586/files#diff-5 (79)
> - _M_ pyemma/coordinates/transform/tica.py
>   https://github.com/markovmodel/PyEMMA/pull/586/files#diff-6 (48)
> - _M_ pyemma/coordinates/transform/transformer.py
>   https://github.com/markovmodel/PyEMMA/pull/586/files#diff-7 (4)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/markovmodel/PyEMMA/pull/586.patch
> - https://github.com/markovmodel/PyEMMA/pull/586.diff
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/586.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
The windows tests are failing because the generated test-files are still opened and therefore can not be deleted. This suggests that there might be a bug in the feature reader not closing files properly.

**Comment by franknoe** [comment]
I don't understand this implementation. I don't understand why we need to modify the tica class.

I thought the Sparsifier is a transformer that maps n features to m varying features. Then, couldn't it be simply be used inside the coor.tica API function as a pipelining step before tica? Let's talk about tomorrow, I'd like to first understand this in detail before considering a merge.

**Comment by marscher** [comment]
I've integrated the Sparsifier in the first pass of TICA to save one pass over the data, as you suggested yourself in #569. Of course we can decouple it and do it in the API, but this would then waste one pass. Your understanding of what the Sparsifier does is totally correct.

**Comment by franknoe** [comment]
OK, let's discuss it later

Am 28/10/15 um 13:31 schrieb Martin K. Scherer:

> I've integrated the Sparsifier in the first pass of TICA to save one 
> pass over the data, as you suggested yourself in #569 
> https://github.com/markovmodel/PyEMMA/pull/569. Of course we can 
> decouple it and do it in the API, but this would then waste one pass. 
> Your understanding of what the Sparsifier does is totally correct.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/586#issuecomment-151828887.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
The Sparsifier is now used to optionally calculate the mean (in the same manner as TICA (eg. respect constraint "force_eigenvalues_le_one", which depends on lag time - so the Sparsifier needs to know this). This happens in the same pass. If the mean is provided, the mean is truncated to the varying indices calculated by the Sparsifier.
The Sparsifier instance is then used as input stage of TICA.

**Comment by franknoe** [comment]
Please don't include this into 2.0.2

**Comment by franknoe** [comment]
- Please demonstrate that this works with real data (same result as without sparsification) and also demonstrate the performance gain compared to not sparsifying.
- The contact featurizer produces boolean arrays. Are they fed into the TICA estimator like that? Wouldn't this run into the problem that multiplying integer/boolean arrays by numpy is far slower than multiplying float arrays? And is there any advantage to use boolean in our current context? I think we don't save memory, because we start by calculating a distance matrix (float).
- Test validity of the boolean type implementation by comparing the new result to float contact arrays with 0.0 / 1.0.
- Ortography: "Brechen" is break, not brake (past tense: broken)

**Comment by franknoe** [comment]
Please wait with this PR til our meeting next week. I think our low-level handling in the new covariance computation routines may replace that at least partially and will be more efficient.

**Comment by marscher** [comment]
We'll handle this with the new covar extension.

**Pull request closed without merging**
