### PR TITLE
[FeatureReader] method top_matches_traj added

### LINKED ISSUE #438: [coor] does not complain about top and traj file when they are different
I accidentally read in a topology file with solvent and trajectory files without solvent. Up to the stage of using TICA I didn't get any errors. TICA then complained with a very cryptic error. Maybe a sanity check or warning would be good here. 

```
/home/mi/ppxasjsm/Software/anaconda/lib/python2.7/site-packages/mdtraj-1.3.0-py2.7-linux-x86_64.egg/mdtraj/core/trajectory.pyc in xyz(self, value)
    809 
    810         value = ensure_type(value, np.float32, 3, 'xyz', shape=shape,
--> 811                             warn_on_cast=False, add_newaxis_on_deficient_ndim=True)
    812         self._xyz = value
    813         self._rmsd_traces = None

/home/mi/ppxasjsm/Software/anaconda/lib/python2.7/site-packages/mdtraj-1.3.0-py2.7-linux-x86_64.egg/mdtraj/utils/validation.pyc in ensure_type(val, dtype, ndim, name, length, can_be_none, shape, warn_on_cast, add_newaxis_on_deficient_ndim)
    146             if a != b:
    147                 # check for equality
--> 148                 raise error
    149 
    150     return val

ValueError: xyz must be shape (Any, 23044, 3). You supplied  (100, 103, 3)
```

### PR DESCRIPTION
**Pull request by gph82**
fixes #438

### CODE REVIEW

**Comment by franknoe** [comment]
Würde ich verstecken (nicht vom User aufrufen lassen) und umbennen ->

```
_assert_toptraj_consistency
```

**Comment by marscher** [comment]
I'll suggest reading one frame, this is sufficient for the 
"topology"-shape check and it does not blow up your memory.

Am 22.07.2015 um 11:51 schrieb Guillermo Pérez-Hernández:

**Comment by gph82** [comment]
Alles klar, aber die Message hört beim Pfeil auf :)

**Comment by gph82** [comment]
@marscher , I think that is exactly what's happening in top_matches_traj

**Comment by franknoe** [comment]
corrected. Umbennen nicht so wichtig, aber verstecken.

Am 22/07/15 um 11:54 schrieb Guillermo Pérez-Hernández:

> Alles klar, aber die Message hört beim Pfeil auf :)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/440#issuecomment-123646639.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 22.07.2015 um 11:55 schrieb Guillermo Pérez-Hernández:

**Comment by gph82** [comment]
@marscher can you point me to an example where that is happening. First time with context managers

**Comment by marscher** [comment]
Am 22.07.2015 um 11:58 schrieb Guillermo Pérez-Hernández:

**Comment by gph82** [comment]
okay, wait please...

**Comment by gph82** [comment]
Okay, for some reason I seem not to be able to rename that commit message. You can merge if you want

**Pull request merged**
