### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by marscher** [comment]
Error: MD5 sums mismatch for download: https://repo.continuum.io/pkgs/free/linux-64/libgfortran-3.0-0.tar.bz2 (d41d8cd98f00b204e9800998ecf8427e != 0d1664f9e5992bbd447a9c4d8bc43c64) 

marvelous

**Comment by marscher** [comment]
https://travis-ci.org/markovmodel/PyEMMA/jobs/115164337#L1841 why ever this only happens on OSX is a riddle wrapped up in an enigma.... :+1:

**Comment by franknoe** [comment]
Probably the same reason like my error.

```
======================================================================
ERROR: test_corrupted_db 
(pyemma.coordinates.tests.test_traj_info_cache.TestTrajectoryInfoCache)
----------------------------------------------------------------------
Traceback (most recent call last):
   File 
"/Users/noe/data/software_projects/pyemma/pyemma/coordinates/tests/test_traj_info_cache.py", 
line 209, in test_corrupted_db
     db = TrajectoryInfoCache(name)
   File 
"/Users/noe/data/software_projects/pyemma/pyemma/coordinates/data/util/traj_info_cache.py", 
line 156, in __init__
     self._database.sync()
AttributeError: sync
```

Am 11/03/16 um 12:50 schrieb Martin K. Scherer:

> https://travis-ci.org/markovmodel/PyEMMA/jobs/115164337#L1841 why ever 
> this only happens on OSX is a riddle wrapped up in an enigma.... :+1:
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/730#issuecomment-195335640.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Pull request merged**
