### PR TITLE
[clustering.interface] added methods index_states and sample_index_by_…

### PR DESCRIPTION
**Pull request by gph82**
…state

This ports the index_states and sample_indexes_by_state from util.discrete_trajectories to the clustering interface. Now the clustering object also has these methods, which up to now only the estimated_MSM had (I think).

### CODE REVIEW

**Comment by franknoe** [comment]
Good idea. Well done.

Suggested Name change: Use `index_clusters` and `sample_indexes_by_cluster`, because in a clustering algorithm it's not clear what a "state" is.

**Comment by gph82** [comment]
OK. What about microstate?

**Comment by franknoe** [comment]
clustering has itself nothing to do with MSM building, so it's neither 
clear what states nor microstates should be.

Am 02/07/15 um 11:45 schrieb Guillermo Pérez-Hernández:

> OK. What about microstate?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/389#issuecomment-117980545.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
please don't merge, little snafu with rebases etc

**Comment by gph82** [comment]
now

**Comment by franknoe** [comment]
cluster_s_ not cluster (compare to state_s_)

**Comment by gph82** [comment]
Now it is like this:
index_states = index_clusters
sample_indexes_by_state = sample_indexes_by_cluster

**Pull request merged**
