### PR TITLE
[TICA] variable self._skipped_trajs stores skipped trajs and 'skipped traje…

### PR DESCRIPTION
**Pull request by gph82**
…ctory' warnings stop after 100 warnings

Otherwise the notebook might get too cluttered (or even crash) when thousands of warnings are issued.

### CODE REVIEW

**Comment by franknoe** [comment]
Generally the output is still overly verbose in my poing of view. Can we 
collect that information in one warning (e.g. that many trajectories 
were skipped)?

Am 25/06/15 um 11:24 schrieb Guillermo Pérez-Hernández:

> …ctory' warnings stop after 100 warnings
> 
> Otherwise the notebook might get too cluttered (or even crash) when 
> thousands of warnings are issues.
> 
> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
> https://github.com/markovmodel/PyEMMA/pull/379
> 
> ```
>     Commit Summary
> ```
> - [TICA] variable self._skipped stores skipped trajs and 'skipped
>   trajectory' warnings stop after 100 warnings
>   
>   ```
>   File Changes
>   ```
> - _M_ pyemma/coordinates/transform/tica.py
>   https://github.com/markovmodel/PyEMMA/pull/379/files#diff-0 (11)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/markovmodel/PyEMMA/pull/379.patch
> - https://github.com/markovmodel/PyEMMA/pull/379.diff
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/379.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
Sure. I just did this as least-invasive approach to keep my notebooks from crashing. Do you think we should have self._skipped or self.skipped?

**Comment by marscher** [comment]
Am 25.06.2015 um 11:32 schrieb Frank Noe:

> Generally the output is still overly verbose in my poing of view. Can we
> collect that information in one warning (e.g. that many trajectories
> were skipped)?
> Yes, one logging.warning with a list of skipped trajectories would be 
> sufficient.

**Comment by marscher** [comment]
one could also apply a warnings filter
https://docs.python.org/2/library/warnings.html#warnings.filterwarnings

**Comment by marscher** [comment]
I introduced this warning after Nuria was wondering about bad statistic 
because nearly all of her trajectories were kicked out due to large lag 
times/short trajs. So in general I consider this useful.

**Comment by franknoe** [comment]
what does self._skipped contain exactly? Indexes?
maybe use skipped_trajs or skipped_traj_indexes, otherwise it isn't 
clear what is skipped.

Am 25/06/15 um 11:24 schrieb Guillermo Pérez-Hernández:

> …ctory' warnings stop after 100 warnings
> 
> Otherwise the notebook might get too cluttered (or even crash) when 
> thousands of warnings are issues.
> 
> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
> https://github.com/markovmodel/PyEMMA/pull/379
> 
> ```
>     Commit Summary
> ```
> - [TICA] variable self._skipped stores skipped trajs and 'skipped
>   trajectory' warnings stop after 100 warnings
>   
>   ```
>   File Changes
>   ```
> - _M_ pyemma/coordinates/transform/tica.py
>   https://github.com/markovmodel/PyEMMA/pull/379/files#diff-0 (11)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/markovmodel/PyEMMA/pull/379.patch
> - https://github.com/markovmodel/PyEMMA/pull/379.diff
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/379.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
yup, indexes. To my question. self._skipped_trajs or self.skipped_trajs?

**Comment by franknoe** [comment]
Let's do _skipped_trajs for now. Otherwise it becomes an API thing, and 
we should thing a bit more deeply about what we wanna present on the API 
level. We can always lift it by adding a a property

``` python
@property
def skipped_trajs()
     return self._skipped_trajs
```

later

Am 25/06/15 um 11:37 schrieb Guillermo Pérez-Hernández:

> yup, indexes. To my question. self._skipped_trajs or self.skipped trajs?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/379#issuecomment-115186491.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
agreed.

**Comment by marscher** [comment]
The log statement should go into self._param_finish

**Comment by gph82** [comment]
scratch that. You mean like that newest commit, i think

**Comment by gph82** [comment]
Okay, after a bit of rebasing and squashing, that should be it

**Comment by marscher** [comment]
perfect!

**Pull request merged**
