### PR TITLE
[plots/networks] bugfix for no arrow labels

### LINKED ISSUE #808: pyemma.plots.plot_markov_model doesn't accept arrow_labels=None anymore
In `pyemma.plots.plot_markov_model`, `arrow_labels=None` used to work before, but now leads to the following failure. I guess this is due to #793 that I unfortunately merged. I think we will have to add tests for the plots as well - not necessarily test the output as that is visual, but at least test for non failing using the Agg backend.

``` python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-26-3574d4368b3c> in <module>()
----> 1 plots.plot_markov_model(Pplot, arrow_labels=None)

/Users/noe/data/software_projects/pyemma/pyemma/plots/networks.pyc in plot_markov_model(P, pos, state_sizes, state_scale, state_colors, state_labels, minflux, arrow_scale, arrow_curvature, arrow_labels, arrow_label_format, max_width, max_height, figpadding, show_frame, **textkwargs)
    417                            max_width=max_width, max_height=max_height,
    418                            figpadding=figpadding, xticks=False, yticks=False, show_frame=show_frame,
--> 419                            **textkwargs)
    420     return ax, plot.pos
    421 

/Users/noe/data/software_projects/pyemma/pyemma/plots/networks.pyc in plot_network(self, state_sizes, state_scale, state_colors, state_labels, arrow_scale, arrow_curvature, arrow_labels, arrow_label_format, max_width, max_height, figpadding, xticks, yticks, show_frame, **textkwargs)
    250                     self._draw_arrow(self.pos[i, 0], self.pos[i, 1],
    251                                      self.pos[j, 0], self.pos[j, 1], Dx, Dy,
--> 252                                      label=arrow_label_format%L[i, j],
    253                                      width=arrow_scale * self.A[i, j],
    254                                      arrow_curvature=arrow_curvature,

TypeError: float argument required, not str
```

### PR DESCRIPTION
**Pull request by gph82**
fixes #808

### CODE REVIEW

**Comment by marscher** [comment]
Do you mind adding a test?

**Comment by gph82** [comment]
sure! You mean explicitly for the arrow_labels=None?

**Comment by marscher** [comment]
Thank you!

**Pull request merged**
