### PR TITLE
[coor/save_trajs] added stride parameter.

### PR DESCRIPTION
**Pull request by marscher**
@gph82 can you please check, I did not brake any functionality? The new testcase is very basic.

### CODE REVIEW

**Comment by gph82** [comment]
Hi, I'll check, but I first, some thoughts off the top of my head:
- The stride parameter can be used to slice the index array directly,
  right? I mean, if I parse the strided index array, i get the same effect
  as parsing full index array and then striding it internally.
- Also, striding makes most sense if one is saving entire trajectories.
  and not samples. I guess if one is generating samples (of PCCA-sets, of
  the stationary distribution, etc, of a given microstate), one can
  generate the sample with the adequate size N (no need to stride). And
  even if one overshoots N, you can still use the strided index (see above).
- Only when using save_trajs to save entire, time-sequential
  trajectories the stride really makes sense...for which save_trajs can be
  very inefficient (because of the appending of geometries in each step,
  instead of a regular geom[::stride].save('strided.pdb)

Am I missing sth here?

On 18.05.2015 16:24, Martin K. Scherer wrote:

> @gph82 https://github.com/gph82 can you please check, I did not brake
> any functionality? The new testcase is very basic.
> 
> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
>   https://github.com/markovmodel/PyEMMA/pull/309
> 
> ```
>     Commit Summary
> ```
> - [coor/save_trajs] added stride parameter.
>   
>   ```
>   File Changes
>   ```
> - _M_ pyemma/coordinates/api.py
>   https://github.com/markovmodel/PyEMMA/pull/309/files#diff-0 (46)
> - _M_ pyemma/coordinates/data/frames_from_file.py
>   https://github.com/markovmodel/PyEMMA/pull/309/files#diff-1 (25)
> - _M_ pyemma/coordinates/tests/test_save_trajs.py
>   https://github.com/markovmodel/PyEMMA/pull/309/files#diff-2 (14)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/markovmodel/PyEMMA/pull/309.patch
> - https://github.com/markovmodel/PyEMMA/pull/309.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/pull/309.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

## http://userpage.fu-berlin.de/gph82/

**Comment by marscher** [comment]
If the users passes stridden indices to these functions right now, he will get the wrong indices.

To your first point: Do you mean to stride the index array being passed to the function internally? Not sure, if you will get the same results, since the underlying reader (mdtraj) might handle the stride parameter differently than Numpy. So it might be better to pass the same stride parameter to mdtraj as used during transforming the data.

second and third point: agreed, I'll remove the stride param from save_traj then.

**Comment by gph82** [comment]
On 18.05.2015 16:43, Martin K. Scherer wrote:

> If the users passes stridden indices to these functions right now, he
> will get the wrong indices.
> 
> To your first point: Do you mean to stride the index array being passed
> to the function internally? Not sure, if you will get the same results,
> since the underlying reader (mdtraj) might handle the stride parameter
> differently than Numpy. So it might be better to pass the same stride
> parameter to mdtraj as used during transforming the data.
> had not thought of this, i'll get back to you
> 
> second and third point: agreed, I'll remove the stride param from
> save_traj then.
> ok
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/pull/309#issuecomment-103083076.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

## http://userpage.fu-berlin.de/gph82/

**Comment by marscher** [comment]
since save_traj is the workhorse of save_trajs it also needs to support the stride parameter or am I wrong?

**Comment by franknoe** [comment]
Yes I think that's true.

Am 18/05/15 um 17:09 schrieb Martin K. Scherer:

> since save_traj is the workhorse of save_trajs it also needs to 
> support the stride parameter or am I wrong?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/309#issuecomment-103090885.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
i think so. I'll look into this and get back to you.

On 18.05.2015 17:09, Martin K. Scherer wrote:

> since save_traj is the workhorse of save_trajs it also needs to support
> the stride parameter or am I wrong?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/pull/309#issuecomment-103090885.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

## http://userpage.fu-berlin.de/gph82/

**Pull request closed without merging**
