### PR TITLE
[msm] Fix doctests

### PR DESCRIPTION
**Pull request by trendelkampschroer**

### CODE REVIEW

**Comment by marscher** [comment]
Travis does currently not perform doctests on this branch. Are all msm related doctests now passing?

**Comment by marscher** [comment]
some tests are failing due to numerical precision, eg.
`File "/home/marscher/workspace/pyemma/pyemma/msm/analysis/api.py", line 1270, in pyemma.msm.analysis.api.expectation
Failed example:
    m_a
Expected:
    0.90909090909090917       
Got:
    0.90909090909090939`

You should only give the first few significant digits of the result and omit the rest with ... (three dots), so they are not being checked.

**Comment by marscher** [comment]
I can fix it locally and just merge it, if you want.

**Comment by franknoe** [comment]
ok

Am 27/07/15 um 14:18 schrieb Martin K. Scherer:

> I can fix it locally and just merge it, if you want.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/447#issuecomment-125184405.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
merged with  #450

**Pull request closed without merging**
