### PR TITLE
Tests for coordinates.api.input(...)

### PR DESCRIPTION
**Pull request by clonker**
Some minor refactoring and tests for coordinates.api.input, see commit messages.

### CODE REVIEW

**Comment by marscher** [comment]
?

**Comment by clonker** [comment]
Accidentally deleted the branch on my fork

**Comment by marscher** [comment]
why are feature_reader tests failing? Eg.
https://travis-ci.org/markovmodel/PyEMMA/builds/57603849#L741

another strange thing is, that stridden access does not work anymore here:
https://travis-ci.org/markovmodel/PyEMMA/builds/57603849#L836

**Comment by marscher** [comment]
I've just pulled your changes in my refactoring branch which works before applying your changes.

**Comment by clonker** [comment]
The problem is likely in the feature_reader, this method:
```python
@classmethod
def init_from_featurizer(cls, trajectories, featurizer):
    if not isinstance(featurizer, MDFeaturizer):
        raise ValueError("given featurizer is not of type Featurizer, but is %s"
                         % type(featurizer))
    cls.featurizer = featurizer
    return cls(trajectories, featurizer.topologyfile)
```

Here the featurizer gets set on the *class* not on the *object* to be created, thus creating these strange side effects when used. A possible way to circumvent this would be to accept a MDFeaturizer as optional input parameter of the FeatureReader. Any thoughts on this?

**Comment by franknoe** [comment]
Yes, I think the FeatureReader should either receive the topology file 
or the featurizer as an argument, so both should be optional. Since the 
user is not supposed to instantiate FeatureReader directly, the correct 
version must be called from e.g. the input or the load methods.

I don't understand why we should pass a class and do the instantiation 
dynamically. I don't think there's an advantage of this over passing 
actual objects and we loose the ability to detect syntax errors by code 
checking.

Am 10/04/15 um 13:20 schrieb Moritz Hoffmann:
>
> The problem is likely in the feature_reader, this method:
>
> @classmethod
> def  init_from_featurizer(cls,trajectories,featurizer):
>      if  not  isinstance(featurizer, MDFeaturizer):
>          raise  ValueError("given featurizer is not of type Featurizer, but is%s"
>                           %  type(featurizer))
>      cls.featurizer=  featurizer
>      return  cls(trajectories, featurizer.topologyfile)
>
> Here the featurizer gets set on the /class/ not on the /object/ to be 
> created, thus creating these strange side effects when used. A 
> possible way to circumvent this would be to accept a MDFeaturizer as 
> optional input parameter of the FeatureReader. Any thoughts on this?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/pull/206#issuecomment-91520392>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
I agree.

**Comment by marscher** [comment]
@clonker can you please rebase on latest dev_release_1.2?

**Comment by franknoe** [comment]
@marscher  and @clonker : This is a large PR and I am a bit uncomfortable with doing it now because:
1. our feature freeze has already expired and we have 3 days left til the release. 
2. It is still causing failures
3. It is introducing a dependency to pandas. Yes, it's an efficient and powerful package, but we're using functionality that is also provided by core python packages.

I suggest to: 
1. not include the functionality to read arbitrary files in this release
2. instead just fix the current impl of input, which only constructs a FeatureReader - that is much easier to handle.
3. Discuss the various changes involved in this PR when I'm back in Berlin and postpone it to the next release.

Sorry guys, it's good work, but since the deadline is approaching we should be conservative at this point.

Do you agree? If yes, I can do the fixing of input today (Saturday). Please still leave the PR open as I might steal little parts of it for the fix of the input function.

**Comment by franknoe** [comment]
I am on it now. I'm using and testing part of Moritz' changes to create a new PR. I am not using the raw data file access at the moment for the reasons described above. After the release, we'll have to discuss this and Moritz and I need to do some synching to create a new PR for the changes not yet merged.

Please don't work on input or feature_reader until I submit my PR. Thanks.

**Comment by marscher** [comment]
Am 11.04.2015 um 02:39 schrieb Frank Noe:
> @marscher <https://github.com/marscher> and @clonker
> <https://github.com/clonker> : This is a large PR and I am a bit
> uncomfortable with doing it now because:
> 1. our feature freeze has already expired and we have 3 days left til
> the release.
True, true...
> 2. It is still causing failures
> 3. It is introducing a dependency to pandas. Yes, it's an efficient and
> powerful package, but we're using functionality that is also provided by
> core python packages.
We already have pandas as an indirect dependency through mdtraj (try 
installing mdtraj with conda in an empty environment). So it is not new 
in any sense, we just started to use it.
>
> I suggest to:
> 1. not include the functionality to read arbitrary files in this release
> 2. instead just fix the current impl of input, which only constructs a
> FeatureReader - that is much easier to handle.
> 3. Discuss the various changes involved in this PR when I'm back in
> Berlin and postpone it to the next release.
>
> Sorry guys, it's good work, but since the deadline is approaching we
> should be conservative at this point.

>
> Do you agree? If yes, I can do the fixing of input today (Saturday).
> Please still leave the PR open as I might steal little parts of it for
> the fix of the input function.
Maybe thats the best solution. Despite the wiring in the API 
(redirecting to various readers), I'm still struggeling with stridden 
lagged chunked access for both NumPy and CSVReaders, so before they are 
not stable, it makes not sense to support them in the API.

But be aware, that DataInMemory also did not support lagged stridden 
access correctly and it now is not able to load files anymore (split up 
the functionality in two classes NPYfilereader and DataInMemory only 
gives access to underlying loaded arrays).

**Comment by franknoe** [comment]
OK, mdtraj depends on a ton of things, but I would like to minimize the 
direct dependencies of emma. I think we can restrict ourselves to:

numpy
scipy
mdtraj
psutil
matplotlib

pystallone and sklearn can be removed from the dependencies in the 
subsequent release.

Best
Frank.

Maybe we can in the future convince the mdtraj guys to provide a light 
version.

Am 11/04/15 um 12:00 schrieb Martin K. Scherer:
> Am 11.04.2015 um 02:39 schrieb Frank Noe:
> > @marscher <https://github.com/marscher> and @clonker
> > <https://github.com/clonker> : This is a large PR and I am a bit
> > uncomfortable with doing it now because:
> > 1. our feature freeze has already expired and we have 3 days left til
> > the release.
> True, true...
> > 2. It is still causing failures
> > 3. It is introducing a dependency to pandas. Yes, it's an efficient and
> > powerful package, but we're using functionality that is also provided by
> > core python packages.
> We already have pandas as an indirect dependency through mdtraj (try
> installing mdtraj with conda in an empty environment). So it is not new
> in any sense, we just started to use it.
> >
> > I suggest to:
> > 1. not include the functionality to read arbitrary files in this release
> > 2. instead just fix the current impl of input, which only constructs a
> > FeatureReader - that is much easier to handle.
> > 3. Discuss the various changes involved in this PR when I'm back in
> > Berlin and postpone it to the next release.
> >
> > Sorry guys, it's good work, but since the deadline is approaching we
> > should be conservative at this point.
>
> >
> > Do you agree? If yes, I can do the fixing of input today (Saturday).
> > Please still leave the PR open as I might steal little parts of it for
> > the fix of the input function.
> Maybe thats the best solution. Despite the wiring in the API
> (redirecting to various readers), I'm still struggeling with stridden
> lagged chunked access for both NumPy and CSVReaders, so before they are
> not stable, it makes not sense to support them in the API.
>
> But be aware, that DataInMemory also did not support lagged stridden
> access correctly and it now is not able to load files anymore (split up
> the functionality in two classes NPYfilereader and DataInMemory only
> gives access to underlying loaded arrays).
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/markovmodel/PyEMMA/pull/206#issuecomment-91729891>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/pull/206#issuecomment-91814997>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
Am 11.04.2015 um 12:07 schrieb Frank Noe:
> OK, mdtraj depends on a ton of things, but I would like to minimize the
> direct dependencies of emma. I think we can restrict ourselves to:
>
> numpy
> scipy
> mdtraj
> psutil
> matplotlib
>
> pystallone and sklearn can be removed from the dependencies in the
> subsequent release.
>
> Best
> Frank.
>
> Maybe we can in the future convince the mdtraj guys to provide a light
> version.
I think they distinct between the conda and pypi release. The conda 
release is feature rich, since it does not cost anything despite hard 
disc space to provide those features, while pypi users would have to 
compile a ton of things.

So you suggest writing a chunked csv reader (optionally with c-extension 
for good performance) for the subsequent release? Or do not support csv 
until then. First dragging pandas in to kick it out in the subsequent 
release is not very straight forward.

**Comment by marscher** [comment]
actually I vote for using pandas, since it would avoid reinventing the 
wheel (now in the case of csv reading and probably in the future 
supporting new stuff).

**Comment by gph82** [comment]
and don't we need sklearn for all the clustering flexibility?

On 04/11/2015 12:18 PM, Martin K. Scherer wrote:
> actually I vote for using pandas, since it would avoid reinventing the
> wheel (now in the case of csv reading and probably in the future
> supporting new stuff).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markovmodel/PyEMMA/pull/206#issuecomment-91821177>.
>

-- 
Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

**Comment by marscher** [comment]
Am 11.04.2015 um 12:22 schrieb Guillermo Pérez-Hernández:
> and don't we need sklearn for all the clustering flexibility?

If we make coordinates a separate package, we can keep the dependency 
overhead of msm part low.

But I would also postpone that for the subsequent rel, since it requires 
a lot of work to do it.

**Comment by franknoe** [comment]
No. At the moment sklearn is only used for k-means and it is rather an 
abuse really, because sklearn cannot stream data (so we just accumulate 
a lot of data in memory and hope for the best) - so we'll have to get 
rid of this anyway.

The user is still free to use sklearn complementary to pyemma. If our 
own functions don't need it, why create this dependency?

Am 11/04/15 um 12:22 schrieb Guillermo Pérez-Hernández:
> and don't we need sklearn for all the clustering flexibility?
>
> On 04/11/2015 12:18 PM, Martin K. Scherer wrote:
> > actually I vote for using pandas, since it would avoid reinventing the
> > wheel (now in the case of csv reading and probably in the future
> > supporting new stuff).
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/markovmodel/PyEMMA/pull/206#issuecomment-91821177>.
> >
>
> -- 
> Dr. Guillermo Pérez-Hernández
> Freie Universität Berlin
> Institute for Mathematics
> Arnimallee 6
> D-14195 Berlin
> tel 0049 30 838 75776
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/pull/206#issuecomment-91822358>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
Sure, I meant to remove sklearn only in the subsequent rel (e.g. 1.3), 
because now we do use it for k-means.

Am 11/04/15 um 12:24 schrieb Martin K. Scherer:
> Am 11.04.2015 um 12:22 schrieb Guillermo Pérez-Hernández:
> > and don't we need sklearn for all the clustering flexibility?
>
> If we make coordinates a separate package, we can keep the dependency
> overhead of msm part low.
>
> But I would also postpone that for the subsequent rel, since it requires
> a lot of work to do it.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/pull/206#issuecomment-91822541>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
What about using the standard package for csv reading?

     https://docs.python.org/2/library/csv.html

I'd like to be conservative with dependencies, because once we include 
them usages tend to explode and pandas doesn't appear to be essential 
for the functionality of EMMA.


Am 11/04/15 um 12:18 schrieb Martin K. Scherer:
> actually I vote for using pandas, since it would avoid reinventing the
> wheel (now in the case of csv reading and probably in the future
> supporting new stuff).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/pull/206#issuecomment-91821177>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
Am 11.04.2015 um 12:30 schrieb Frank Noe:
> What about using the standard package for csv reading?
> 
> https://docs.python.org/2/library/csv.html
> 

I've choosen pandas reader since it supports chunk based reading. But it
should be possible to achieve the same with python's csv (though more
custom work which have to be tested).

**Comment by franknoe** [comment]
is is more like a few hours or more like a day or more to do that? In 
the first case I would suggest to do it, in the latter case I would 
suggest to not add the csv functionality in this release and discuss it 
a bit more.

Am 11/04/15 um 12:33 schrieb Martin K. Scherer:
> Am 11.04.2015 um 12:30 schrieb Frank Noe:
> > What about using the standard package for csv reading?
> >
> > https://docs.python.org/2/library/csv.html
> >
>
> I've choosen pandas reader since it supports chunk based reading. But it
> should be possible to achieve the same with python's csv (though more
> custom work which have to be tested).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/pull/206#issuecomment-91824193>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
We can also try to import pandas, and fallback to pythons csv, if we did
not succeed. I'm sure pandas is more optimized.

**Comment by franknoe** [comment]
OK - provided you can fix the csv Reader today. Otherwise it's out of 
this release anyway.

Am 11/04/15 um 12:37 schrieb Martin K. Scherer:
> We can also try to import pandas, and fallback to pythons csv, if we did
> not succeed. I'm sure pandas is more optimized.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/pull/206#issuecomment-91824293>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
Closing this PR. @clonker : A large part of your changes are part of my PR that has just been merged. Please merge current version of dev_release_1.2 into your branch and do a new PR after the 1.2 release and discussion next week.

Your fixes and tests for MD trajectory reading worked very well. Thank you!

**Pull request closed without merging**
