### PR TITLE
added a minRMSD feature.

### PR DESCRIPTION
**Pull request by gph82**
./source/api/generated/pyemma.coordinates.data.MDFeaturizer.rst has also been changed, but we're not tracking these files

There is a TODO regarding duplicates when parsing the same trajectory through different rajectory objects. The hashed trajectory objects are different.

Also, pretty verbose feat.describe() output, it is a tentative format.

### CODE REVIEW

**Comment by franknoe** [comment]
Looks good. Thanks.

**Comment by marscher** [comment]
Looks very good. The hashing stuff is not that an important issue. Trajectory object do not provide a custom hashing function, thats why the most basic implementation of object is being called, which causes collisions. One might consider sending them a PR, to implement proper hashing (it might be interesting if you want to lookup e.g Trajectory objects in a cache really fast).

If you want to fix this behaviour, you can write your own hash function for Trajectory (which should consider the topology, coords and time arrays) and call it in the features hash function.

**Comment by marscher** [comment]
send in a PR to mdtraj

**Comment by gph82** [comment]
Thanks for the quick merge. 

@marscher , what do we do with ./source/api/generated/pyemma.coordinates.data.MDFeaturizer.rst and the like?

**Comment by marscher** [comment]
Sorry, I do not understand your question at all.

**Comment by gph82** [comment]
You can ignore it safely ;)

**Pull request merged**
