### PR TITLE
[clustering] Fix minRMSD assignment.

### LINKED ISSUE #835: problem with minRMSD assignment to clustercenters
The assignment of trajectories to clustercenters (obtained from the same trajectories) using a minRMSD metric produces a completely different result for PyEMMA 2.2 than for previous PyEMMA versions and leaves about 15 % of all centers with no frames assigned. This is most likely an error.

### PR DESCRIPTION
**Pull request by marscher**
Since version 2.1 only the first center has been pre-centered correctly, while
the rest was ignored.

Fixes #835.

### CODE REVIEW

**Comment by franknoe** [comment]
thanks!

Am 20/06/16 um 17:03 schrieb Martin K. Scherer:

> Since version 2.1 only the first center has been pre-centered 
> correctly, while
> the rest was ignored.
> 
> Fixes #835 https://github.com/markovmodel/PyEMMA/issues/835.
> 
> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
> https://github.com/markovmodel/PyEMMA/pull/837
> 
> ```
>     Commit Summary
> ```
> - [clustering] Fix minRMSD assignment.
>   
>   ```
>   File Changes
>   ```
> - _M_ pyemma/coordinates/clustering/src/clustering.c
>   https://github.com/markovmodel/PyEMMA/pull/837/files#diff-0 (63)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/markovmodel/PyEMMA/pull/837.patch
> - https://github.com/markovmodel/PyEMMA/pull/837.diff
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/837, or mute the thread 
> https://github.com/notifications/unsubscribe/AGMeQst8-yThyi6aQtO_1ZNbtBnrseAUks5qNqvegaJpZM4I5yxW.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by jchodera** [comment]
Good catch, @marscher!

**Comment by marscher** [comment]
@jchodera I hope this didn't ruined a lot of results so far!

**Comment by jchodera** [comment]
It's OK!  We have been struggling to get this to produce good results for us, and now we know why!

Will there be a new point release for this bug?

**Comment by marscher** [comment]
> Will there be a new point release for this bug?
> I'll be happy to cut a service release now.

@franknoe: do you agree?

**Comment by franknoe** [comment]
yes, go ahead.

Am 21/06/16 um 12:31 schrieb Martin K. Scherer:

> > Will there be a new point release for this bug?
> > I'll be happy to cut a service release now.
> 
> @franknoe: do you agree?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/837#issuecomment-227402025, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AGMeQmWiuKEvBN-mJd8fULGZty50VYEmks5qN72cgaJpZM4I5yxW.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by jchodera** [comment]
Thanks!

**Pull request merged**
