### PR TITLE
Kmeans quick fix and Pipeline.parametrize() stride fix

### LINKED ISSUE #196: [coordinates.api.pipeline]: Trying to pass argument to parametrize function
In line coordinates.api.pipeline the call:
        p.parametrize(param_stride)
is attempted, which results in an "Unexpected argument error" in PyCharm because Pipeline.parametrize does not accept arguments.

I'm not sure how to fix this, but if possible avoid passing arguments into parametrize.

### PR DESCRIPTION
**Pull request by franknoe**
* Quick Fix for k-means: Now accumulating data in memory and running full k-means from sklearn
* Fixes #196
* New input checking for trajector data in coordinates.api. Uses new ensure_traj and ensure_trajs in util.types

### CODE REVIEW

**Comment by marscher** [comment]
just a question to the data argument of actual transformers in the api:
Didn't we discussed they take arbitrary input (files, arrays, data_in_memory?)

**Comment by marscher** [comment]
the quick fix should at least state, that it will blow up the memory, since you now doubled memory requirements, which might be a bit unexpected when using the pipeline.

**Comment by franknoe** [comment]
OK, no problem. How do I do it? Just change and push again, or do I need 
to close and open the PR again?

Am 10/04/15 um 12:11 schrieb Martin K. Scherer:
>
> the quick fix should at least state, that it will blow up the memory, 
> since you now doubled memory requirements, which might be a bit 
> unexpected when using the pipeline.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/pull/215#issuecomment-91505606>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
We can add that later

Am 10/04/15 um 12:10 schrieb Martin K. Scherer:
>
> just a question to the data argument of actual transformers in the api:
> Didn't we discussed they take arbitrary input (files, arrays, 
> data_in_memory?)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/pull/215#issuecomment-91505258>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
you just add your changes to your branch - they will show up in this pr.

**Comment by marscher** [comment]
I thought we would then use the input/load function accordingly. Sorry
for being offtopic now.

**Comment by franknoe** [comment]
I'm not sure about the usecase of this flexibility for transformers. Are 
you thinking of mapping input files to transformed output files? If we 
want that we can write a utility function which does that for an 
abritrary transformer, we don't need to change transformer.

Anyway, new features are at this point not a good idea. Let's take what 
we have and try to fix+debug it.

Am 10/04/15 um 12:14 schrieb Martin K. Scherer:
> I thought we would then use the input/load function accordingly. Sorry
> for being offtopic now.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/pull/215#issuecomment-91506417>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
ok.

**Comment by franknoe** [comment]
done

Am 10/04/15 um 12:11 schrieb Martin K. Scherer:
>
> the quick fix should at least state, that it will blow up the memory, 
> since you now doubled memory requirements, which might be a bit 
> unexpected when using the pipeline.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/pull/215#issuecomment-91505606>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
Thank you! I think you have to rebase on latest state.

**Comment by franknoe** [comment]
Please tell me how to do this. I'm on the kmeans_quick_fix branch and I 
have done a push to remote

Am 10/04/15 um 14:54 schrieb Martin K. Scherer:
>
> Thank you! I think you have to rebase on latest state.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/pull/215#issuecomment-91545747>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
1. git checkout dev_release_1.2
2. git pull
3. git checkout kmeans_quick_fix
4. git rebase dev_release_1.2
5. handle merge issues and commit. 
6. git push -f  myfork kmeans_quick_fix # to overwrite the remote changes on your fork

**Comment by marscher** [comment]
or if you want I can do the merging.

**Comment by franknoe** [comment]
Please do. I'm still in talks and not concentrated enough to handle real 
problems.

Am 10/04/15 um 15:01 schrieb Martin K. Scherer:
>
> or if you want I can do the merging.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/pull/215#issuecomment-91547451>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
no problem.

**Comment by franknoe** [comment]
thanks

Am 10/04/15 um 15:03 schrieb Martin K. Scherer:
>
> no problem.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/pull/215#issuecomment-91549022>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Pull request merged**
