### PR TITLE
[utility][coordinates] added function to compute autocorrelation functio...

### PR DESCRIPTION
**Pull request by fabian-paul**
Hi Martin, I just moved the code from the old mm_acf into a new module and cleaned it up. 
Can you merge this please? Of course, you are free to move the new module (pyemma.coordinates.acf) somewhere else in the hierarchy if it fits better.
Fabian

### CODE REVIEW

**Comment by marscher** [comment]
Thank you! This feature would actually nicely fit into the transformer logic, so we can process large data. Is it possible to calculate FFT chunkwise?

**Comment by marscher** [comment]
have a look at transformers.tica to get an idea for the logic.

**Comment by fabian-paul** [comment]
Yes, it should be possible to calculate the acf chunk-wise for lag times tau_max < chunk_size.
Besides that, there are many possible optimizations:
- calculate the FFT for one trajectory at a time
- calculate the FFT for one observable at a time
- subsample the trajectory with a stride to fit data with a longer lag time into one chunk.

**Comment by marscher** [comment]
it then would be nice to have this in the transformer pipeline also. Should not be to hard to refactor.

**Pull request merged**
