### PR TITLE
Change ipywidgets version check to use __version__. Fixes #1571.

### LINKED ISSUE #1571: ipywidgets.version_info is deprecated since version a6 causing progress.reporter__init__.py to fail
Error:
```
  File "/lila/data/chodera/paynea/fah-analysis-tmem175/fah_analysis/core/dimensionality_reduction.py", line 5, in run_2d_tica
    my_data = pma.coordinates.load(fn_list, stride=100)
  File "/home/paynea/miniconda3/envs/fah-analysis-tmem175/lib/python3.7/site-packages/pyemma/coordinates/api.py", line 245, in load
    reader = create_file_reader(trajfiles, top, features, chunksize=cs, **kw)
  File "/home/paynea/miniconda3/envs/fah-analysis-tmem175/lib/python3.7/site-packages/pyemma/coordinates/data/util/reader_utils.py", line 114, in create_file_reader
    reader = NumPyFileReader(input_list, chunksize=chunksize)
  File "/home/paynea/miniconda3/envs/fah-analysis-tmem175/lib/python3.7/site-packages/pyemma/coordinates/data/numpy_filereader.py", line 65, in __init__
    self.filenames = filenames
  File "/home/paynea/miniconda3/envs/fah-analysis-tmem175/lib/python3.7/site-packages/pyemma/coordinates/data/_base/datasource.py", line 118, in filenames
    pg.register(len(filename_list), 'Obtaining file info')
  File "/home/paynea/miniconda3/envs/fah-analysis-tmem175/lib/python3.7/site-packages/pyemma/_base/progress/reporter/__init__.py", line 220, in register
    self._progress_register(amount_of_work=amount_of_work, description=description, stage=stage, tqdm_args=tqdm_args)
  File "/home/paynea/miniconda3/envs/fah-analysis-tmem175/lib/python3.7/site-packages/pyemma/_base/progress/reporter/__init__.py", line 143, in _progress_register
    if _attached_to_ipy_notebook_with_widgets():
  File "/home/paynea/miniconda3/envs/fah-analysis-tmem175/lib/python3.7/site-packages/pyemma/_base/progress/reporter/__init__.py", line 10, in wrapper
    f.res = f()
  File "/home/paynea/miniconda3/envs/fah-analysis-tmem175/lib/python3.7/site-packages/pyemma/_base/progress/reporter/__init__.py", line 20, in _attached_to_ipy_notebook_with_widgets
    if ipywidgets.version_info[0] < 4:
AttributeError: module 'ipywidgets' has no attribute 'version_info'
```

Line 20 should use __getattr_ or something to have it not fail.

https://discourse.jupyter.org/t/where-is-version-info-for-ipywidgets-version-8-which-versions-are-at-which-stage-stable-development-test-etc/11852

https://github.com/jupyter-widgets/ipywidgets/commit/04d42174b3580f1f1b44ced0c79f4c3e60ad4084

[env.txt](https://github.com/markovmodel/PyEMMA/files/9414128/env.txt)

### PR DESCRIPTION
**Pull request by clonker**

### CODE REVIEW

**Comment by apayne97** [comment]
Note that for earlier versions of ipywidgets, `__version__` doesn't exist so you may have to be creative with checking

**Comment by apayne97** [comment]
Maybe you should do something like:
```
if getattr(ipywidgets, version_info, False):
    if ipywidgets.version_info[0] < 4:
        raise ImportError()
```
If the ipywidgets version is stored in `__version__` instead, then you know that the version is greater than 4!

**Comment by apayne97** [comment]
Woo!

**Comment by clonker** [comment]
Test failures are unrelated, merging

**Pull request merged**
