### PR TITLE
Feature msmrevpi

### PR DESCRIPTION
**Pull request by marscher**
- Rebased on latest devel

Only the Python3 jobs are failing with: 
`RuntimeError: Failed to converge after 100 iterations, residuum is 1.844134e-15` 
But isn't that error pretty good? So maybe the check is somehow faulty.

### CODE REVIEW

**Comment by marscher** [comment]
The convergence check is by the way in msmtools.

**Comment by trendelkampschroer** [comment]
https://github.com/markovmodel/msmtools/commit/92a642eb712694d244664a39f5399283562a4a74 should have fixed the tolerance problem. Does the build use the latest msmtools version

**Comment by marscher** [comment]
indeed. It used the old one - maybe it was not available on conda that moment

**Comment by marscher** [comment]
seems like the python3 conda packages have not been updated... I'll report upstream.

**Comment by marscher** [comment]
omnia-md/conda-recipes#320

**Comment by marscher** [comment]
everything fine now. 1 Appveyor job failed because of #509

**Comment by franknoe** [comment]
I have actually fixed that in a PR that was merged this morning.

Am 01/09/15 um 03:46 schrieb Martin K. Scherer:

> everything fine now. 1 Appveyor job failed because of #509 
> https://github.com/markovmodel/PyEMMA/issues/509
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/538#issuecomment-136547982.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Pull request merged**
