### PR TITLE
Refactoring thermo API

### PR DESCRIPTION
**Pull request by cwehmeyer**

### CODE REVIEW

**Comment by franknoe** [comment]
Thank you! Minor things:
- Please cite this one for WHAM (you can cite Kumar et al in addition): Ferrenberg AM, Swendsen RH (1989) Optimized Monte Carlo data analysis. Phys. Rev. Lett. 63:1195–1198.
- I am a bit unhappy with plotting functions outside the plots subpackage, because we have always been doubtful about the dependency on matplotlib which as caused problems in the past. Logically pyemma.plots is a higher-level subpackage than the other ones and could in principle be moved out of PyEMMA to a separate package, but then with dependency on PyEMMA. So I would rather create a thermoplots module under pyemma.plots than defining those plots under pyemma.thermo and then importing them into pyemma.plots.

**Comment by cwehmeyer** [comment]
OK, I will take care of this.

**Comment by franknoe** [comment]
OK. Sorry I misunderstood the thermo/plots relation, this is perfectly fine. Ready to merge once the test issues are sorted.

**Comment by marscher** [comment]
We still need to add the notebooks to ipython.rst in doc/source so they will show up on the website.

ping @cwehmeyer

**Pull request merged**
