### PR TITLE
[coordinates/api] Implemented save trajs (and minor changes to save_traj)

### PR DESCRIPTION
**Pull request by gph82**
The inmemory option has to be tested in bigger files for efficiency. For everything else, see tests here:

http://page.mi.fu-berlin.de/gph82/test_save_traj_and_save_trajs.html

(i'll write the proper tests tomorrow in the office)

### CODE REVIEW

**Comment by franknoe** [comment]
Thanks. One note: This code
python```
   if fmt is None:
       fmt = traj_inp.trajfiles[0][-4:]
```
is unsafe because extensions are not necessarily 3 letters, e.g. "*.hdf5". This should be done by os.path.splitext(). 

No problem though, I'll merge this, do that change myself and then merge our branches into a new feature branch for the release. Give me a min...

**Comment by gph82** [comment]
Careful with files that have periods in them 


--
Sent from my phone. 
Apologies for typos, unusual tone or brevity 

-------- Original message --------

**Comment by franknoe** [comment]
Periods? I don't understand.

-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by gph82** [comment]
traj.001.dt_0.25.xtc


--
Sent from my phone. 
Apologies for typos, unusual tone or brevity 

-------- Original message --------

**Comment by franknoe** [comment]
No problem. In this case splitext will give 'traj.001.dt_0.25' and 'xtc'

-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Pull request merged**
