### PR TITLE
[coor refactoring] Fix regspace clustering

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by marscher** [comment]
note that this is a work in progress PR for a refactoring branch. The tests for regspace clustering are now all passing.

For backward compat I've added a deprecated "parametrize" method to Transformer, which just calls estimate.

**Comment by marscher** [comment]
@clonker for Kmeans we'll need to know when we're on the last_chunk during initializing the centers. Do you think it could be feasible to add another flag to iterables, so they return a dict of meta information (itraj, timestep, last_chunk), which can the be used in estimators?

**Comment by clonker** [comment]
I think we can provide these just as (maybe in a meta map or configuration object like the iterator context?) members in the iterators themselves.. so something along the lines

```
it = X.iterator()
for chunk in it:
    t = it.timestep
    last_chunk = it.last_chunk
```

**Comment by marscher** [comment]
This looks practical (members).

**Pull request merged**
