### PR TITLE
[feat] all distance based features allow optarg periodic

### PR DESCRIPTION
**Pull request by gph82**
And the tests checks specifically a case where periodic=True and periodic=False yield different results

### CODE REVIEW

**Comment by marscher** [comment]
looks like mdtraj.compute_contacts is not aware of the periodic keyword (which makes no sense, since it computes a distance matrix with compute_distances first).

**Comment by marscher** [comment]
looks like mdtraj.compute_contacts is not aware of the periodic keyword (which makes no sense, since it computes a distance matrix with compute_distances first).

**Comment by franknoe** [comment]
I think we have added that in the current development version.

Am 15/04/16 um 18:10 schrieb Martin K. Scherer:

> looks like mdtraj.compute_contacts is not aware of the periodic 
> keyword (which makes no sense, since it computes a distance matrix 
> with compute_distances first).
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/773#issuecomment-210523780

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Could be, but there is not mdtraj-dev version on conda we could test against.

**Comment by franknoe** [comment]
OK, then this has to stay on hold until the next release.

Am 15/04/16 um 19:42 schrieb Martin K. Scherer:

> Could be, but there is not mdtraj-dev version on conda we could test 
> against.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/773#issuecomment-210560510

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
Indeed, here https://github.com/mdtraj/mdtraj/pull/1072 ... so we wait until it's released, right?

**Comment by marscher** [comment]
Yes. Otherwise everybody using devel versions of pyemma would have to use devel of mdtraj too.

**Comment by marscher** [comment]
@gph82 the new mdtraj release is there, can you please rebase your branch on devel and run the tests again?

**Comment by marscher** [comment]
We should have made mdtraj-1.7 as minimum version requirement in 2.2. I've already added this to the local meta.yaml, but we should maybe release another micro soon, because people will run into problems with that.

@franknoe do you think we should do it ASAP or wait until next week?

**Pull request merged**
