### PR TITLE
Introduced optional chunksize parameter for the coordinates api

### PR DESCRIPTION
**Pull request by clonker**
This PR should fix issue #282.

### CODE REVIEW

**Comment by franknoe** [comment]
Can someone explain why we need this parameter? Load loads everything into memory, right?

**Comment by marscher** [comment]
Sure it does, but IO efficiency clearly depends on the chosen chunksize, so there might be users who want to overwrite our arbitrary defined default values.

**Comment by marscher** [comment]
It can also be necessary to run things at a smaller chunksize than the default, which is right now not possible.

**Comment by franknoe** [comment]
OK.

I guess if the chunksize is larger than the trajectory size that would 
be caught, no?

Am 12/05/15 um 14:33 schrieb Martin K. Scherer:

> It can also be necessary to run things at a smaller chunksize than the 
> default, which is right now not possible.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/303#issuecomment-101259552.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
It would then process the trajectory at once, which might fail with
MemoryError.

**Comment by franknoe** [comment]
I was thinking of short trajectories ( < 100 steps). There would be no 
memoryerror, just curious if the case junksize > trajlength is caught.

Am 12/05/15 um 14:37 schrieb Martin K. Scherer:

> It would then process the trajectory at once, which might fail with
> MemoryError.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/303#issuecomment-101260187.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
If chunksize > traj_len, then the slice is out of bounds which will then stop on the last possible element. So there will be no error at all.

**Comment by marscher** [comment]
merged manually

**Pull request closed without merging**
