### PR TITLE
Part of the coordinates.api.input(...) method, a few minor things

### PR DESCRIPTION
**Pull request by clonker**
- propagates max_clusters argument of the api into the regular space method
- small fix the the catch_unhashable method of the coordinates featurizer
- added way to instantiate the feature_reader by featurizer rather than just by input files and topology file
- input method of the coordinates api up to case 1.1

### CODE REVIEW

**Comment by fabian-paul** [comment]
Hi Moritz,
could you please unify your implementation of load with coordinates.api.input, case 1? 
For input case 1, we would have exactly the same code safe for the final operate_in_memory, map_to_memory,...
I suggest to move your code into a new function and call this function in load and in input case 1.
Best, Fabian

**Comment by fabian-paul** [comment]
Oops, I got this the wrong way round. Of course I mean: could you please extend your implementation of input such that it can be used in load?

**Comment by marscher** [comment]
Thanks for the changes! Please move _get_file_reader to an impl package 
(maybe io.util) - We do not want impl detail in API module.

**Comment by marscher** [comment]
superseeded by #180  (which includes this commits)

**Pull request closed without merging**
