### PR TITLE
[config] implemented save/load. Do not try to create a cfg dir by default.

### PR DESCRIPTION
**Pull request by marscher**
Only on invocation of cfg_dir setter or save method files/directories will be
created.

Adresses #760

### CODE REVIEW

**Comment by marscher** [comment]
TODO: adopt docstrings.

**Comment by franknoe** [comment]
Please explain in the PR description what this PR does and how it changes behavior. It shouldn't be necessary to read the code in order to know what's in the PR, but anyway I don't understand it even based on reading the code.
Also the documentation needs to be in detail in the doc pages, not just docstrings.
Thanks!

**Comment by marscher** [comment]
Sure. It changes the code from always building the config values first on the default configuration file we ship with the package, then it tries to read existing config files from the hidden directory ".pyemma" in the users home directory. If there is a user-config found, these values will precede the existing ones.

If the user has set a environment variable "PYEMMA_CFG_DIR" to some path, this location will be probed for a configuration directory. If it is not there, the defaults will be used again.

New features:
- save: tries to save the current runtime configuration to the specified configuration directory (which defaults to $HOME/.pyemma/, but can be set via config.cfg_dir = path or os.environ['PYEMMA_CFG_DIR'] = path).
- load: read configuration from a given filename (should be useful for batch scripting purposes).

**Comment by franknoe** [comment]
Sorry, I don't understand:
- It changes the code _from_ ... to what?
- these values will precede the existing ones. What does that mean? Do you mean override the existing ones?

**Comment by marscher** [comment]
Before this PR, pyemma's config module tries to copy over the default files shipped with the package to the users home directory. Now this only happens if the user requests this explicitly by invoking the setter of cfg_dir or by calling save.

Your intuition about the second question is correct, it will just override existing values. The priority is given by (highest: User-cfg, lowest:default-cfg).

**Comment by marscher** [comment]
I will also add a notice in the changelog for 2.1.1

**Comment by franknoe** [comment]
OK, this i my understanding of the PR. Please comment if correct:
- Old behavior
  - If `$HOME/.pyemma/` exists, read the configuration from there and use it.
  - Else: try to create `$HOME/.pyemma/` and copy the default configuration there.
- New behavior
  - If a config is found under PYEMMA_CFG_DIR or `$HOME/.pyemma/`, read the configuration from there and use it. 
  - Else: use default configuration 
  - When calling save, write the current config settings to PYEMMA_CFG_DIR or `$HOME/.pyemma/` for future use.

And all of this happens when calling `import pyemma`. Correct?

**Comment by marscher** [comment]
Am 18.04.2016 um 14:43 schrieb Frank Noe:

> OK, this i my understanding of the PR. Please comment if correct:
> - Old behavior
>     o If |$HOME/.pyemma/| exists, read the configuration from there
>       and use it.
>     o Else: try to create |$HOME/.pyemma/| and copy the default
>       configuration there.
>   Correct.
> - New behavior
>     o If a config is found under PYEMMA_CFG_DIR or |$HOME/.pyemma/|,
>       read the configuration from there and use it.
>     o Else: use default configuration
>     o When calling save, write the current config settings to
>       PYEMMA_CFG_DIR or |$HOME/.pyemma/| for future use.
> 
> And all of this happens when calling |import pyemma|. Correct?
> Precisely.

One question to the "make_my_life_easy" option: I guess the name should 
be something like "show_config_notifications" = True, which by default 
prints instructions how to change/save things, once pyemma is imported.

These notifications could then be turned off by changing this setting.

Would this actually make ones life easier, when we force them to run 
some lines of code just to get rid of messages?

**Comment by gph82** [comment]
trying now to see if #775 is indeed gone...

**Pull request merged**
