### PR TITLE
Simulate Trajectories for MSM and HMSM

### PR DESCRIPTION
**Pull request by alexlafleur**
This is our proposal for issue #889.
We implemented a simulate function for both MSM and HMSM to generate trajectories from a given model.

Alexandra and Tara

### CODE REVIEW

**Comment by greenTara** [comment]
In the process of writing these extensions, we noted a few opportunities to improve the code, but wanted to discuss this before proceeding.
1. There are differences in naming conventions between the MSM and HMSM class (aliases np and _np for numpy respectively)
2. There is inconsistent documentation in HMSM (attribute P is called Pcoarse, attribute pobs is called Pobs)

**Comment by franknoe** [comment]
I'll take care of reviewing this. However, already a few changes:
- please use identical nomenclature as in msmtools.generation.generate_traj.
- generate one trajectory only with this function, otherwise the return value is unclear.
- never use the rv_discrete function inside a loop, because that's expensive. Pre-generate all needed distributions before the loop, and possible save them to the object, then just sample from them inside the loop.
- There are no tests, both functions need to be tested.

**Comment by franknoe** [comment]
P.S.: hmsm.simulate() is actually not that easy to do, especially if the user wants to specify an observable state rather than a hidden state to start from (that's possible). I have code for this, better leave it to me and just to the msm.simulate binding now.

**Comment by franknoe** [comment]
PPS: by "identical nomenclature as in msmtools.generation.generate_traj" I mean input parameters and names for start, stop, length etc.

**Comment by franknoe** [comment]
I currently don't have enough bandwidth to pull, so I'm just giving an example for a simple HMSM.simulate here. This doesn't have the option to start from observable states. This feature can be added later, but if you wanna give it a shot: If the first observed state is given, then the first hidden state needs to be sampled from the distribution 

```
p(hidden | observed) = p(hidden) p(observed | hidden) // normalized.
```

Here, `p(hidden)` is the stationary distribution of the hidden transition matrix, `p(observed | hidden)` is the output distribution, //normalized indicates normalization to sum 1 by hidden state. That can be written in two lines of matrix operations, but since I don't have the up-to-date code here I won't write it, otherwise I'll just get the variable names wrong.

This code snip is not tested, please adapt if needed and add tests. MSM can be according (that doesn't really need to be more than a line)

``` python
    def simulate(self, N, start=None, stop=None, dt=1):
    """ Generates a realization of the Hidden Markov model.

    Parameters
    ----------
    N : int
        trajectory length in steps of the lag time
    start : int, optional, default = None
        starting hidden state. If not given, will sample from the stationary 
        distribution of the hidden transition matrix.
    stop : int or int-array-like, optional, default = None
        stopping hidden set. If given, the trajectory will be stopped before 
        N steps once a hidden state of the stop set is reached
    dt : int
        trajectory will be saved every dt time steps.
        Internally, the dt'th power of P is taken to ensure a more efficient simulation.

    Returns
    -------
    htraj : (N/dt, ) ndarray
        The hidden state trajectory with length N/dt
    otraj : (N/dt, ) ndarray
        The observable state discrete trajectory with length N/dt

    """
    from scipy import stats
    # generate output distributions
    output_distributions = [stats.rv_discrete(values=(np.arange(pobs.shape[1]), pobs_i)) for pobs_i in pobs]
    # sample hidden trajectory
    htraj = msmtools.generation.generate_traj(self.transition_matrix, N, start=start, stop=stop, dt=dt)
    otraj = np.zeros(htraj.size, dtype=int)
    # for each time step, sample microstate
    for t, h in enumerate(htraj):
        otraj[t] = output_distributions[h].rvs()  # current cluster
    return htraj, otraj
```

**Comment by alexlafleur** [comment]
We assumed that the start parameter would indicate the hidden start state.

**Comment by franknoe** [comment]
Thank you very much.

**Pull request merged**
