### PR TITLE
Upgrade mdtraj1.5

### LINKED ISSUE #613: PyEMMA broken with mdtraj 1.5
PyEMMA is using hidden variables and functions in mdtraj. In the 1.5 release some of those have changed or disappeared, such that PyEMMA is broken with mdtraj 1.5. For example:

``` python
/Users/noe/data/software_projects/pyemma/pyemma/coordinates/data/featurizer.py in <module>()
     24 
     25 import mdtraj
---> 26 from mdtraj.geometry.dihedral import (_get_indices_phi,
     27                                       _get_indices_psi,
     28                                       _atom_sequence,
```

We need to avoid using hidden variables and functions. These are not API functions and we can't blame the mdtraj guys for changing those.

This needs to be fixed asap and go into 2.0.2.

### PR DESCRIPTION
**Pull request by franknoe**
- Fixes #613
- Upgrades to mdtraj 1.5 and avoids using fake trajectories for computing phi/psi indices
- Synchronized numpy and mdtraj requirements in pip and conda

### CODE REVIEW

**Comment by franknoe** [comment]
@marscher : I have synched the requirements for mdtraj/numpy in pip with those in conda. I assume the difference in requirements was by mistake. Please check.

**Comment by marscher** [comment]
Thank you!

**Comment by franknoe** [comment]
Is the numpy version setting >= 1.7 in both setup.py and conda/meta.yaml 
ok, or was it different (1.7/1.6) on purpose?

Am 08/11/15 um 13:55 schrieb Martin K. Scherer:

> Merged #614 https://github.com/markovmodel/PyEMMA/pull/614.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/614#event-458152724.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
This was a mistake you've just corrected. The first releases had been compatible with numpy-1.6, but we've dropped that on the way and forgot to adopt these.

**Comment by franknoe** [comment]
OK, please go through the other dependencies too. There were differences 
in setup.py vs meta.yaml in more package dependencies.

Am 08/11/15 um 13:59 schrieb Martin K. Scherer:

> This was a mistake you've just corrected. The first releases has been 
> compatible with numpy-1.6, but we've dropped that on the way and 
> forgot to adopt these.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/614#issuecomment-154825264.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Of course there are some differences, since it is a different python environment (names on pypi are not necessarily the same in conda for instance). Are you talking about version specifiers or packages in general? The list in setup.py is a bit fragmented for good reasons (but complete IMHO). 

The conda-build tool refuses to download dependencies on the fly and enforces you to declare them. Therefore all dependencies of setup.py are obeyed. So finally the list in setup.py dictates the final set of dependencies.

If you belive that there is anything wrong or incomplete, please be more specific :+1:

**Comment by franknoe** [comment]
Firstly, I think
bhmm<6
is wrong (in both setup.py and meta.yaml). Should it be 0.6?

Secondly, I was wondering why there are different version requirements. 
The difference in numpy was one such example, which is now corrected. 
Remaining differences are:

setup.py:
scipy>=0.11
     joblib==0.8.4
psutil>=3.1.1
decorator>=4.0.0

meta.yaml:
     scipy
     joblib
     psutil
     decorator

What's the reason for having different version requirements in these two 
environments ?

Am 08/11/15 um 14:21 schrieb Martin K. Scherer:

> Of course there are some differences, since it is a different python 
> environment (names on pypi are not necessarily the same in conda for 
> instance). Are you talking about version specifiers or packages in 
> general? The list in setup.py is a bit fragmented for good reasons 
> (but complete IMHO).
> 
> The conda-build tool refuses to download dependencies on the fly and 
> enforces you to declare them. Therefore all dependencies of setup.py 
> are obeyed. So finally the list in setup.py dictates the final set of 
> dependencies.
> 
> If you belive that there is anything wrong or incomplete, please be 
> more specific :+1:
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/614#issuecomment-154826263.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
bhmm<6 is wrong. Should be 0.6.

Actually there is no good reason for having two distinct sets of version specifications (undetermined vs constrained). But setup.py will finally the one instance complaining about not met version specs.

People tend to adopt dependencies only in one spot and not update version specs in both places. We should definitely synchronize them.

**Pull request merged**
