### PR TITLE
[msm-model] minor improvements

### PR DESCRIPTION
**Pull request by marscher**
- added setter for transition matrix
- explicit exception handling (AttributeError)
- pcca: convert argument to int

### CODE REVIEW

**Comment by marscher** [comment]
Thanks to @cwehmeyer for pointing out that passing strings to MSM.pcca leads to hard to detect errors like:

"requested 5 metastable states for 666 micro-states is not possible" :+1:

**Comment by franknoe** [comment]
I think setting in Model should go through `set_model_params`. I haven't quite understood the problem - why do we need this setter exactly?

**Comment by marscher** [comment]
To check if it is a valid transition matrix.

**Comment by franknoe** [comment]
shouldn't that be in set_model_params then?

Am 08/06/16 um 16:53 schrieb Martin K. Scherer:

> To check if it is a valid transition matrix.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/828#issuecomment-224614952, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AGMeQlOEUPXREG96c8mU5xKR7pyxbSkcks5qJtdwgaJpZM4Iw_wp.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
actually the setter should also be invoked by set_model_params, but because we have this duplication/or intended alias to "transition_matrix" we should chain these setters and implement it only in one spot.

**Comment by franknoe** [comment]
why is it a duplication? I am arguing that you should always go through 
set_model_params, so there's no duplication.

Am 08/06/16 um 16:56 schrieb Martin K. Scherer:

> actually the setter should also be invoked by set_model_params, but 
> because we have this duplication/or intended alias to 
> "transition_matrix" we should chain these setters and implement it 
> only in one spot.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/828#issuecomment-224615994, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AGMeQvlvr12xsC3wnBVXYqCXk0t-sz_dks5qJtgtgaJpZM4Iw_wp.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
yes.

**Comment by marscher** [comment]
Am 08.06.2016 um 17:07 schrieb Frank Noe:

> why is it a duplication? I am arguing that you should always go through
> set_model_params, so there's no duplication.
> In principle the user can modify this attribute like he wants, and we can not check it then.
> So actually providing setters for these attributes will be the best solution.

**Comment by franknoe** [comment]
But that's true for every attribute. I don't think we wanna start 
implementing setters for every attribute.
I don't think the user will set anything here, because the user doesn't 
usually instantiate models.

The reason for using set_model_params (from within PyEMMA) is that we 
check consistency between different parameters. For example, for a 
reversible MSM it is not enough to just ensure that we have a transition 
matrix, etc.

Am 08/06/16 um 17:16 schrieb Martin K. Scherer:

> Am 08.06.2016 um 17:07 schrieb Frank Noe:
> 
> > why is it a duplication? I am arguing that you should always go through
> > set_model_params, so there's no duplication.
> > In principle the user can modify this attribute like he wants, and we 
> > can not check it then.
> > So actually providing setters for these attributes will be the best 
> > solution.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/828#issuecomment-224622375, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AGMeQj3VCwkS0W1_jKlKViAaH57kr4UHks5qJtzVgaJpZM4Iw_wp.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I have removed the setter again.

**Pull request merged**
