### PR TITLE
[frames_from_files] removed progress bar

### LINKED ISSUE #840: Issue solving PCCA samples in release version 2.2
So we have run into some problems saving frames that would correspond to a series of PCCA states. 

To be precise, calling pyemma.coordinates.save_trajs() to save pcca sampled snapshots was not saving any files and lead to an error termination finishing with the following statement.

```
/home/soft/miniconda2/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/_base/progress/bar/_impl.pyc in set_numerator(self, numerator, calculate)
  148         # Validate
  149         if self._timing_data and numerator < self._timing_data[-1][1]:
--> 150             raise ValueError('numerator cannot decrement.')
  151 
  152         # Update data.

ValueError: numerator cannot decrement.

I traced back the error to a class called ProgressReporter() called in

~ /pyemma/coordinates/data/util/frames_from_file.py
```

Commenting out lines 126 127 132 and 133 of that file seemed to get rid off the error and now the files are saved correctly, though this is obviously quite a dirty solution. 
Here is the exact call in which the error occurs:

```
M = bayesian_markov_model(dtrajs,lagtime)
Import pyemma.coordinates as coor
inp=coor.source(trajfiles, topology)
[…]
pcca = M.pcca(8)
ppca_dist = M.metastable_distributions
pcca_samples = M.sample_by_distribution(pcca_dist,1000/500/100) #(same behaviour)
coor.save_trajs(inp,pcca_samples,outfiles=[8 str], inmemory =True/False )# (same behaviour)
```

### PR DESCRIPTION
**Pull request by marscher**
fixes #840

### CODE REVIEW

**Comment by franknoe** [comment]
Hm, is this the only way to fix this error to give up the progress reporting here?

**Comment by marscher** [comment]
At 34°C, it seems to be

**Comment by franknoe** [comment]
:-)

Am 24/06/16 um 11:54 schrieb Martin K. Scherer:

> At 34°C, it seems to be
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/842#issuecomment-228305851, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AGMeQrf76gqV-lzY838VUGvHmYzzXUfzks5qO6llgaJpZM4I9n2x.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Actually it did not make much sense to use a progress bar with a default
chunksize of 1000 and estimating how long 1 chunk takes for only a
couple of frames, since it is finished in no time.

**Comment by franknoe** [comment]
ok. I guess it used to makes sense in the beginning. Fine with removing 
them.

Am 24/06/16 um 11:58 schrieb Martin K. Scherer:

> Actually it did not make much sense to use a progress bar with a default
> chunksize of 1000 and estimating how long 1 chunk takes for only a
> couple of frames, since it is finished in no time.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/842#issuecomment-228306505, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AGMeQixsCwnmOeFJPp-4vBgF5iDQ0KObks5qO6pEgaJpZM4I9n2x.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Pull request merged**
