### PR TITLE
[doc] switch to msmb_theme, as it is up to date with readthedocs theme.

### PR DESCRIPTION
**Pull request by marscher**
Our approach of hacking the versions combo box into the original theme was
crude and is fairly out of sync now, since it required continuous rebasing
on the upstream code.

The folks at msmbuilder solved this more elegantly by extending the original theme in sphinx
theme defined manner, not by forking the code.

Solves some problems:
* Used to show a scrolling bar for the menu even if there is no content to scroll (Firefox).
* The blue background didn't fit the logo background.

### CODE REVIEW

**Comment by marscher** [comment]
You can preview the theme eg. here or there:
http://mdtraj.org
http://msmbuilder.org

**Comment by marscher** [comment]
or here: http://www.emma-project.org/test/

**Comment by mpharrigan** [comment]
Nice! Let us know if you run into any issues

**Comment by marscher** [comment]
A minor issue is the cross-site request denial if one specifies the version_json_url to "http://www.something.org" but the user browses to "http://something.org".

**Pull request merged**
