### PR TITLE
[coordinates] add skip parameter to estimators to skip initial n_frames of each file.

### PR DESCRIPTION
**Pull request by marscher**
The interface seems redundant at the first view (eg. for a pipeline one has to give the same skip parameter for each element in the pipeline), ... but it totally fits into the logic of separating the IteratorState from the actual DataSource.

It also makes sense to store skip as estimation parameter, since it behaves like stride: it manipulates how much data we are using.

PS: I hope I have not forgotten to pass any "skip"

### CODE REVIEW

**Comment by marscher** [comment]
@jchodera this is now a much cleaner impl as it does not fiddle around with lengths internally but just use the already present skip parameter. Please note that the in case of a pipeline, you have to use the same skip parameter in every step, otherwise your "faulty" data would be used again!

**Comment by jchodera** [comment]
How does it work now? Previously, we just added `skip` to

``` python
coordinates_source = pyemma.coordinates.source(trajectory_filenames, features=featurizer)
```

to make

``` python
coordinates_source = pyemma.coordinates.source(trajectory_filenames, features=featurizer, skip=nskip)
```

**Comment by jchodera** [comment]
Would I just change

``` python
clustering = pyemma.coordinates.cluster_uniform_time(data=coordinates_source, k=nstates, stride=stride, metric=metric)
```

to

``` python
clustering = pyemma.coordinates.cluster_uniform_time(data=coordinates_source, k=nstates, stride=stride, metric=metric, skip=nskip)
```

?

**Comment by marscher** [comment]
yes, the skip argument has to be passed to the actual step reading the data during estimation.

**Comment by jchodera** [comment]
Thanks!

**Pull request merged**
