### PR TITLE
minor fixes in plots, pca and discrete traj sampling

### PR DESCRIPTION
**Pull request by franknoe**

### CODE REVIEW

**Comment by franknoe** [comment]
These are doctest failures. I will fix them later but merge this now to make this feature available.

**Comment by marscher** [comment]
nice and now I have to redo my work essentially.

**Comment by franknoe** [comment]
?

Am 28/07/15 um 13:44 schrieb Martin K. Scherer:

> nice and now I have to redo my work essentially.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/457#issuecomment-125570826.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
You can revert the change and I can re-merge after your merge if needed.

Am 28/07/15 um 13:44 schrieb Martin K. Scherer:

> nice and now I have to redo my work essentially.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/457#issuecomment-125570826.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I was wrong, sorry. I thought you moved code, I've changed in my
previous opened PR in the subsequent one, which would have led to merge
conflicts. But that was not the case.

**Pull request merged**
