### PR TITLE
MSM will return n_sparse_vec eigenvectors automatically, also other chan...

### PR DESCRIPTION
**Pull request by gph82**
...ges needed for this behavior, introduced a new option n_sparse_vec = 10 and an internal parameter n_force_dense to keep users from using sparse = True for cases when it's not needed. See this notebook for rationale:
http://page.mi.fu-berlin.de/gph82/MSM_extension.html

### CODE REVIEW

**Comment by franknoe** [comment]
Hi,

I'll have a look, but I won't accept any PR's for MSM like that because
1) I'm still in the process of changing things
2) MSM is exhaustively tested - see msm.tests.test_msm.py. No PR 
modifying msm will be accepted unless it updates these tests, because 
I'm sure that when you change msm the tests will break down.

Please leave it open, I will check and if I agree I will copy stuff.

Thanks
Frank

Am 08/04/15 um 16:35 schrieb Guillermo Pérez-Hernández:
>
> ...ges needed for this behaviour, introduced a new option n_sparse_vec 
> = 10 and an internal parameter n_force_dense to keep users from using 
> sparse = True for cases when it's not needed. See this notebook for 
> rationale:
> http://page.mi.fu-berlin.de/gph82/MSM_extension.html
>
> ------------------------------------------------------------------------
>
>
>         You can view, comment on, or merge this pull request online at:
>
> https://github.com/markovmodel/PyEMMA/pull/207
>
>
>         Commit Summary
>
>   * MSM will return n_sparse_vec eigenvectors automatically, also
>     other changes
>
>
>         File Changes
>
>   * *M* pyemma/msm/ui/msm.py
>     <https://github.com/markovmodel/PyEMMA/pull/207/files#diff-0> (34)
>
>
>         Patch Links:
>
>   * https://github.com/markovmodel/PyEMMA/pull/207.patch
>   * https://github.com/markovmodel/PyEMMA/pull/207.diff
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/pull/207>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by gph82** [comment]
On 08.04.2015 17:34, Frank Noe wrote:
> Hi,
> 
> I'll have a look, but I won't accept any PR's for MSM like that because
> 1) I'm still in the process of changing things

sure, it was just a working idea of the type of behaviour I woud like to
have. Perhaps an issue instead of PR was better. Anyway, the notebook
exemplifies what my idea is.

> 2) MSM is exhaustively tested - see msm.tests.test_msm.py. No PR
> modifying msm will be accepted unless it updates these tests, because
> I'm sure that when you change msm the tests will break down.
Sorry, what dou you mean "update these tests". Do you mean to include
new tests like that test the new features? What do we make out of the
fact that the new features don't break the old tests?

> 
> Please leave it open, I will check and if I agree I will copy stuff.
> 
> Thanks
> Frank
> 
> Am 08/04/15 um 16:35 schrieb Guillermo Pérez-Hernández:
>>
>> ...ges needed for this behaviour, introduced a new option n_sparse_vec
>> = 10 and an internal parameter n_force_dense to keep users from using
>> sparse = True for cases when it's not needed. See this notebook for
>> rationale:
>> http://page.mi.fu-berlin.de/gph82/MSM_extension.html
>>
>> ------------------------------------------------------------------------
>>
>>
>> You can view, comment on, or merge this pull request online at:
>>
>> https://github.com/markovmodel/PyEMMA/pull/207
>>
>>
>> Commit Summary
>>
>> * MSM will return n_sparse_vec eigenvectors automatically, also
>> other changes
>>
>>
>> File Changes
>>
>> * *M* pyemma/msm/ui/msm.py
>> <https://github.com/markovmodel/PyEMMA/pull/207/files#diff-0> (34)
>>
>>
>> Patch Links:
>>
>> * https://github.com/markovmodel/PyEMMA/pull/207.patch
>> * https://github.com/markovmodel/PyEMMA/pull/207.diff
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/markovmodel/PyEMMA/pull/207>.
>>
> 
> 
> -- 
> 
> ----------------------------------------------
> Prof. Dr. Frank Noe
> Head of Computational Molecular Biology group
> Freie Universitaet Berlin
> 
> Phone: (+49) (0)30 838 75354
> Web: research.franknoe.de
> Mail: Arnimallee 6, 14195 Berlin, Germany
> ----------------------------------------------
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markovmodel/PyEMMA/pull/207#issuecomment-90952597>.
> 

-- 
Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776
http://userpage.fu-berlin.de/gph82/
--

**Comment by franknoe** [comment]
When you make changes to tested code you have to run the test. If it 
fails, you will have to update the tests to accomodate your changes. For 
instance if a function becomes an attribute, all tests using it will 
fail. A PR cannot be accepted if it breaks the code consistency.

There is no necessity to do a PR in order to communicate an idea. Simply 
play around on your own fork and send an issue or email to point out 
what you did. The acceptance threshold for a PR is higher.

Am 08/04/15 um 17:40 schrieb Guillermo Pérez-Hernández:
>
>
> On 08.04.2015 17:34, Frank Noe wrote:
> > Hi,
> >
> > I'll have a look, but I won't accept any PR's for MSM like that because
> > 1) I'm still in the process of changing things
>
> sure, it was just a working idea of the type of behaviour I woud like to
> have. Perhaps an issue instead of PR was better. Anyway, the notebook
> exemplifies what my idea is.
>
> > 2) MSM is exhaustively tested - see msm.tests.test_msm.py. No PR
> > modifying msm will be accepted unless it updates these tests, because
> > I'm sure that when you change msm the tests will break down.
> Sorry, what dou you mean "update these tests". Do you mean to include
> new tests like that test the new features? What do we make out of the
> fact that the new features don't break the old tests?
>
> >
> > Please leave it open, I will check and if I agree I will copy stuff.
> >
> > Thanks
> > Frank
> >
> > Am 08/04/15 um 16:35 schrieb Guillermo Pérez-Hernández:
> >>
> >> ...ges needed for this behaviour, introduced a new option n_sparse_vec
> >> = 10 and an internal parameter n_force_dense to keep users from using
> >> sparse = True for cases when it's not needed. See this notebook for
> >> rationale:
> >> http://page.mi.fu-berlin.de/gph82/MSM_extension.html
> >>
> >> 
> ------------------------------------------------------------------------
> >>
> >>
> >> You can view, comment on, or merge this pull request online at:
> >>
> >> https://github.com/markovmodel/PyEMMA/pull/207
> >>
> >>
> >> Commit Summary
> >>
> >> * MSM will return n_sparse_vec eigenvectors automatically, also
> >> other changes
> >>
> >>
> >> File Changes
> >>
> >> * *M* pyemma/msm/ui/msm.py
> >> <https://github.com/markovmodel/PyEMMA/pull/207/files#diff-0> (34)
> >>
> >>
> >> Patch Links:
> >>
> >> * https://github.com/markovmodel/PyEMMA/pull/207.patch
> >> * https://github.com/markovmodel/PyEMMA/pull/207.diff
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/markovmodel/PyEMMA/pull/207>.
> >>
> >
> >
> > --
> >
> > ----------------------------------------------
> > Prof. Dr. Frank Noe
> > Head of Computational Molecular Biology group
> > Freie Universitaet Berlin
> >
> > Phone: (+49) (0)30 838 75354
> > Web: research.franknoe.de
> > Mail: Arnimallee 6, 14195 Berlin, Germany
> > ----------------------------------------------
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/markovmodel/PyEMMA/pull/207#issuecomment-90952597>.
> >
>
> -- 
> Dr. Guillermo Pérez-Hernández
> Freie Universität Berlin
> Institute for Mathematics
> Arnimallee 6
> D-14195 Berlin
> tel 0049 30 838 75776
> http://userpage.fu-berlin.de/gph82/
> --
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/pull/207#issuecomment-90954972>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
I'm not planning to fix the sparse mode for this release. This requires 
much more testing to be reliable. The dense mode is ready to use, we can 
think about a more sophisticated or easier sparse usage later.


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
I'll integrate the idea. However, checks like asking for k>n should be 
handled in the low-level API, because in principle all commands in 
msm.analysis should be independent of whether you input a sparse or 
dense array. Making this case decision in the msm object is at the wrong 
level.

I'll post an issue for Ben on this.

Am 08/04/15 um 16:35 schrieb Guillermo Pérez-Hernández:
>
> ...ges needed for this behaviour, introduced a new option n_sparse_vec 
> = 10 and an internal parameter n_force_dense to keep users from using 
> sparse = True for cases when it's not needed. See this notebook for 
> rationale:
> http://page.mi.fu-berlin.de/gph82/MSM_extension.html
>
> ------------------------------------------------------------------------
>
>
>         You can view, comment on, or merge this pull request online at:
>
> https://github.com/markovmodel/PyEMMA/pull/207
>
>
>         Commit Summary
>
>   * MSM will return n_sparse_vec eigenvectors automatically, also
>     other changes
>
>
>         File Changes
>
>   * *M* pyemma/msm/ui/msm.py
>     <https://github.com/markovmodel/PyEMMA/pull/207/files#diff-0> (34)
>
>
>         Patch Links:
>
>   * https://github.com/markovmodel/PyEMMA/pull/207.patch
>   * https://github.com/markovmodel/PyEMMA/pull/207.diff
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/pull/207>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
See:

     https://github.com/markovmodel/PyEMMA/issues/208

I'll take care of the rest.

Am 08/04/15 um 16:35 schrieb Guillermo Pérez-Hernández:
>
> ...ges needed for this behaviour, introduced a new option n_sparse_vec 
> = 10 and an internal parameter n_force_dense to keep users from using 
> sparse = True for cases when it's not needed. See this notebook for 
> rationale:
> http://page.mi.fu-berlin.de/gph82/MSM_extension.html
>
> ------------------------------------------------------------------------
>
>
>         You can view, comment on, or merge this pull request online at:
>
> https://github.com/markovmodel/PyEMMA/pull/207
>
>
>         Commit Summary
>
>   * MSM will return n_sparse_vec eigenvectors automatically, also
>     other changes
>
>
>         File Changes
>
>   * *M* pyemma/msm/ui/msm.py
>     <https://github.com/markovmodel/PyEMMA/pull/207/files#diff-0> (34)
>
>
>         Patch Links:
>
>   * https://github.com/markovmodel/PyEMMA/pull/207.patch
>   * https://github.com/markovmodel/PyEMMA/pull/207.diff
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/pull/207>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Pull request closed without merging**
