### PR TITLE
[msm] changed reversible ML T-matrix estimator to accept non-integer counts

### PR DESCRIPTION
**Pull request by fabian-paul**

### CODE REVIEW

**Comment by franknoe** [comment]
That was fast, thank you!
I think with that all c-extensions for transition matrix MLE's do accept float counts. Please confirm.

**Comment by fabian-paul** [comment]
No, dense MLE for reversible T with fixed stationary distribution only accepts integers. The other algorithms are fine.
The reversible T matrix estimator with fixed pi has to be revised anyway because the current implementation uses a regularization parameter which is not really needed.

**Comment by franknoe** [comment]
Am 15/06/15 um 15:08 schrieb fabian-paul:

> No, dense MLE for reversible T with fixed stationary distribution only 
> accepts integers.
> 
> But that is currently not used, right? For dense the python 
> implementation is used which does work with float counts.
> 
> The other algorithms are fine.
> The reversible T matrix estimator with fixed pi has to be revised 
> anyway because the current implementation uses a regularization 
> parameter which is not really needed.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/359#issuecomment-112063896.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by fabian-paul** [comment]
I guess right now nobody (except me) uses the T estimator with fixed stationary distribution. 
Are you sure, you're not mixing up the dense implementation with unconstrained pi and the one with constrained pi?

**Comment by franknoe** [comment]
I was speaking of the dense reversible implementation without pi 
constraint. That one works with float counts. And I guess that is the 
one which uses the python but not the C-extension, right?

Am 15/06/15 um 15:34 schrieb fabian-paul:

> I guess right now nobody (except me) uses the T estimator with fixed 
> stationary distribution.
> Are you sure, you're not mixing up the dense implementation with 
> unconstrained pi and the one with constrained pi?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/359#issuecomment-112071619.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by fabian-paul** [comment]
That's correct.

**Pull request merged**
