### PR TITLE
pin down bhmm to version 0.5.1

### LINKED ISSUE #516: require exact bhmm version for PyEMMA 2.0
The bhmm API is likely to change. Thus PyEMMA 2.0 needs to get a hard requirement to the exact current bhmm release in order to be functional in the future. We can relax that constraint once the bhmm API is stable.

### PR DESCRIPTION
**Pull request by marscher**
Fixes #516

### CODE REVIEW

**Comment by franknoe** [comment]
Thanks!

**Comment by franknoe** [comment]
Should it be == instead of = ?

**Comment by marscher** [comment]
in setup.py its ==, in conda recipes it is = ...

**Comment by marscher** [comment]
Actually you're right :-)

**Pull request merged**
