### PR TITLE
plots2d_cbar

### PR DESCRIPTION
**Pull request by cwehmeyer**
This PR passes the orientation parameter to fig.colorbar() in the plots2d module.

### CODE REVIEW

**Review by thempel — CHANGES_REQUESTED** [review]
Good idea, a very handy feature!

- For some reason when plotting a horizontal cbar, x-axis label, cbar label and cbar tick labels are completely intermixed and unreadable (w/ and w/o `tight_layout()`). I assume that didn't happen for you, or does it require a trick? 
- Can you check for valid input and raise an informative error message? If an invalid value is passed, e.g. `cbar_orientation='asdf'` (or even `None`), I get `ValueError: Position accepts only 'top' or 'bottom'`. 

I tested with tutorial notebook 4.1 by horizontalizing cbars.

**Comment by cwehmeyer** [comment]
@thempel thanks for the review and for catching the problem with the default placement.

**Review by thempel — APPROVED** [review]

**Comment by marscher** [comment]
appveyor fails, because this branch has not been forked of a recent devel branch. I guess this is fine on windows as well. Thanks for the PR.

**Comment by cwehmeyer** [comment]
travis fails due to an unrelated issue.

**Pull request merged**
