### PR TITLE
[msm/estimators/estimated_msm] fraction_of_frames method added

### PR DESCRIPTION
**Pull request by gph82**

### CODE REVIEW

**Comment by franknoe** [comment]
- The term 'frame' has no meaning outside MD. Use 'timestep'
- Avoid overly using bold face in comments, Remove Notes header, because this is the normal method description.

**Comment by gph82** [comment]
Same behavior as in #341 (msm.api.its.fraction_of_frames for trajectories with different lengths). 

Closes #373 

Thanks to @clonker for helping me!

**Comment by gph82** [comment]
What about fraction of data?

**Comment by franknoe** [comment]
Actually neither: What you have programmed is something like 'fraction_of_timesteps_in_used_trajectories'. I understand what you want, but I'm not sure if this is what we want as a general method.

A proper measurement of the fraction of data is more complex and should take the lag time and counting mode into account. For a single trajectory of length 10, using lag time 1 or using lag time 5 makes a difference. But that depends on whether you use sliding window or something else. 

I'll need to think about this a bit. Pls don't merge this yet even if tests pass.

Sorry for being such a Wolfgang Schäuble, but whatever we add to the API should ideally stay there forever, so I'm rather conservative.

**Comment by gph82** [comment]
I totally understand, and though you might not remember this, we had this exact conversation already, what does it mean to "use" 100% of your data at different lagtimes and with different counting-methods?

I want something that informs me about the amount of data that I am literally throwing away vs. the data I am keeping (what I am doing with the kept data is a different, more complex story). 

However, and following your example, I'd actually want something that says 100% on both of the cases (lag 1 and lag 5), irrespective of how I counted. The fact that I extracted more total-counts at lag 1 than at lag 5 is inherent to the use of a lagtime, something the user is aware of. In essence all the data was used in both estimations, regardless of having extracted more counts at lag 1.

**Comment by gph82** [comment]
BTW, even If we might not even merge this, where should I add a test of this? The test_msm.py or test_bayesian_msm.py? I know we might not use this or even refactor heavily, still I'd like it to be a coherent PR

**Comment by franknoe** [comment]
I remember this conversation, but I disagree. With a trajectory size of 
10 and lag 5 we are only using time steps 1 to 5 to extract statistics. 
This is what is relevant for the error. Think of the extreme case that 
you have 1000 trajectories of length 1000 and you are using lag time 
1000. I think it is highly confusing to say that 100% of the data is 
used - you are actually using 0.1 %. And I believe that you should 
actually look at this figure.

Am 15/07/15 um 11:37 schrieb Guillermo Pérez-Hernández:

> I totally understand, and though you might not remember this, we had 
> this exact conversation already, what does it mean to "use" 100% of 
> your data at different lagtimes and with different counting-methods?
> 
> I want something that informs me about the amount of data that I am 
> literally throwing away vs. the data I am keeping (what I am doing 
> with the kept data is a different, more complex story).
> 
> However, and following your example, I'd actually want something that 
> says 100% on both of the cases (lag 1 and lag 5), irrespective of how 
> I counted. The fact that I extracted more total-counts at lag 1 than 
> at lag 5 is inherent to the use of a lagtime, something the user is 
> aware of. In essence all the data was used in both estimations, 
> regardless of having extracted more counts at lag 1.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/422#issuecomment-121551313.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
Also, we might consider outsourcing to some util file, s.t. no code is duplicated (its.fraction_of_frames)

**Comment by franknoe** [comment]
test_msm.py

SampledMSM derives from MSM, so we don't need to test MSM properties in 
SampledMSMs (such as Bayesian MSMs)

Am 15/07/15 um 11:43 schrieb Guillermo Pérez-Hernández:

> BTW, even If we might not even merge this, where should I add a test 
> of this? The test_msm.py or test_bayesian_msm.py? I know we might not 
> use this or even refactor heavily, still I'd like it to be a coherent PR
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/422#issuecomment-121556216.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
Now we're getting into the semantics of the word "use" 

Having the possibility to actually skip 999 frames is "using" them for me. If they were not there, you could not have estimated at lag 1000. Only because you have them, you can "use" them to actually be capable of extracting a (bad) estimate. So I see your .1% argument, but I would not call it "actually use %1. of your data". 

However, I think we can split what you want and what I want into two different things. What about something like "fraction_discarded_data" for what I want?

**Comment by franknoe** [comment]
Let's talk later

Am 15/07/15 um 11:52 schrieb Guillermo Pérez-Hernández:

> Now we're getting into the semantics of the word "use"
> 
> Having the possibility to actually skip 999 frames is "using" them for 
> me. If they were not there, you could not have estimated at lag 1000. 
> Only because you have them, you can "use" them to actually be capable 
> of extracting a (bad) estimate. So I see your .1% argument, but I 
> would not call it "actually use %1. of your data".
> 
> However, I think we can split what you want and what I want into two 
> different things. What about something like "fraction_discarded_data" 
> for what I want?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/422#issuecomment-121559754.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Pull request closed without merging**
