### PR TITLE
Split transformer and added notification framework

### PR DESCRIPTION
**Pull request by marscher**
- Transformer is now a slim interface. The pipeline transformer is called StreamingTransformer.
- The notification framework comes with a easy to use decorator ("inform_children_upon_change"), which should be placed on attributes relevant for children of the current class.

We can discuss, if this new interface needs to be improved further.

### CODE REVIEW

**Comment by franknoe** [comment]
Thanks!

I think the Estimator/Transformer relation is still not really clean, but this is as clean as sklearn wants it to be (In sklearn language almost everything is an Estimator, and a Transformer is a specialized estimator that assumes that there is a fit - in reality a Transformer doesn't need to be estimated). So this is something which is fine for now. We can break it up later if needed.

I am puzzled by the fact that the order of inheritance can break functionality in the StreamingTransformer. 
It seems to indicate that we have two different methods with equal names in the tree, and it one of the versions work for us, that probably means we just don't notice what is broken in this version (because we just test for one version of the janus method)

What exactly is broken there?

**Comment by marscher** [comment]
I've removed the DataStreamingElement again to solve the janus problem. Now the interface looks a bit cleaner.

**Comment by franknoe** [comment]
What was the problem?

Am 15/01/16 um 17:02 schrieb Martin K. Scherer:

> I've removed the DataStreamingElement again to solve the janus 
> problem. Now the interface looks a bit cleaner.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/673#issuecomment-172000759.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 15.01.2016 um 17:03 schrieb Frank Noe:

> What was the problem?
> Like you said, a property has been defined two times in the hierarchy 
> (in DataStreamElement and DataSource, which both used to be interfaces 
> of StreamingTransformer).

**Pull request merged**
