### PR TITLE
Removed dataset file util/tests/data/2well_traj_100K.dat and replaced…

### PR DESCRIPTION
**Pull request by franknoe**
… by call to pyemma.datasets

### CODE REVIEW

**Comment by marscher** [comment]
ah you merged the datasets PR before deleting the 100k lines file

**Comment by franknoe** [comment]
Yes, I did it in two steps.

**Comment by marscher** [comment]
Just to mention that this file now lives in our repo until we rewrite
history someday.

**Comment by franknoe** [comment]
Well it has been there a long time. This was used as a test file for the 
msm package all since 1.2.

I have no idea to remove it from the history. Do you?

Am 14/07/15 um 20:01 schrieb Martin K. Scherer:

> Just to mention that this file now lives in our repo until we rewrite
> history someday.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/415#issuecomment-121324380.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I'm sorry, I thought you just added it your last PR containing the
dataset package.

**Comment by franknoe** [comment]
No. But after that PR there were temporarily two such datafiles, one as 
text, one as npz.

Am 14/07/15 um 20:04 schrieb Martin K. Scherer:

> I'm sorry, I thought you just added it your last PR containing the
> dataset package.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/415#issuecomment-121325040.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Pull request merged**
