### PR TITLE
Include tica correlations

### LINKED ISSUE #268: Correlation function in TICA relating input to output
Provide a function that computes the linear correlation between TICA input features and IC's

### PR DESCRIPTION
**Pull request by gph82**
closes #268

### CODE REVIEW

**Comment by franknoe** [comment]
I would have liked to review that first. Can we please create a new branch dev_release_1.2.1 ?
I'm a bit worried about creating a broken devel branch by merging things quickly.

**Comment by marscher** [comment]
depends on how you define "broken". In this PR no single test is broken.
@gph82 added a new test case for his feature and it works, so I simply
merged it.

Nevertheless, if the feature is not doing what it should or we want to
undo things, it is a git no-brainer (git revert hash).

What should be the purpose of the devel branch, if we create a new
release branch then? I do not see the opportunity in this extra effort,
despite having more merge headaches.

**Comment by franknoe** [comment]
OK, by broken I mean the feature is not doing what we want, or we affect downstream things that aren't explicitly tested yet. It is a good idea if a person who is both experienced with MSMs and has the overall picture of pyemma looks over a new feature before merging it.

I agree that reverting a single feature is simple. But if features pile up, get used by other features etc, this becomes a nightmare. So it doesn't hurt to park the new features outside devel until we are certain that the overall functionality works.

In terms of branches I suggest:
- use devel to directly merge bugfixes
- collect new features in a separate branch for the new release.
  I don't think this creates any headaches. We have done the same for 1.2 and that worked very well in my opinion.

**Comment by marscher** [comment]
agreed. We should then update the development guide, since this is not
reflected there yet.

**Comment by franknoe** [comment]
thanks

Am 29/04/15 um 17:15 schrieb Martin K. Scherer:

> agreed. We should then update the development guide, since this is not
> reflected there yet.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/277#issuecomment-97462488.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Pull request merged**
