### PR TITLE
[coor/pca] remove memory optimization (temporaries for sum, dot)

### LINKED ISSUE #631: [coor/pca] when using NumpyFileReader
Hi, I am observing this behavior...seems like Xm and self._dot_prod_tmp have different dimensions?
snap10

### PR DESCRIPTION
**Pull request by marscher**
Since it fails if chunks are smaller than expected.Fixes #631

### CODE REVIEW

**Comment by franknoe** [comment]
@fabian-paul please review.

**Comment by fabian-paul** [comment]
Ok, for some reason setting the out parameter in numpy.dot is not compatible with memaps. Looks like a numpy bug.
The code (that was reverted to the unoptimized version) is ok.

**Comment by gph82** [comment]
Thanks for quick revision! If I understand correctly, the memmap option is intact, it was the optimization that was not compatible with it, right?

I kinda need this bugfix for the weekend, so, if we can merge this soon...

**Comment by fabian-paul** [comment]
Yes, it seems to be a numpy problem. Who knows where else this can pop up. 
But since we get no other error messages, I think our code is fine now.

This is a pure numpy example with the same problem:

``` Python
import numpy as np
np.save('file.npy',np.random.rand(10,10))
f = np.load('file.npy',mmap_mode='r')
a = np.empty(shape=f.shape) 
f.dot(f,out=a)
```

**Comment by franknoe** [comment]
ok, we can merge as soon as tests have passed. But who knows how long AppVeyor will need

**Comment by marscher** [comment]
Appveyor should have finished 10 hours ago...

**Comment by marscher** [comment]
Thanks for the precision fix @fabian-paul. How did you commit to the PR? Didn't know it is possible to do so.

**Comment by fabian-paul** [comment]
Well I just commited to the branch. Because it is in the Markovmodel repo, I have access to it.

**Comment by marscher** [comment]
Ah never mind. I thought this lied on my fork.

**Comment by fabian-paul** [comment]
BTW, if I replace np.empty(shape=f.shape) in the example above by np.empty_like(f), it works. I think that's because the resulting array is then a memmap as well. This is kind of strange, it's a memmap not linked to a file...

**Comment by marscher** [comment]
Maybe it creates a temporary file for that.

**Comment by fabian-paul** [comment]
Or it's an anonymous memmap?
https://en.wikipedia.org/wiki/Mmap#File-backed_and_anonymous
In computer science, everything one can imagine exists.

**Pull request merged**
