### PR TITLE
[pyemma.plots]: Network plotting functionalities

### PR DESCRIPTION
**Pull request by franknoe**

### CODE REVIEW

**Comment by marscher** [comment]
What a nice improvement! Grandalf does not seem to be on PyPI, so thats why you imported it into the tree, right?

There is still one issue:
    Traceback (most recent call last):  
      File "C:\Python27_32\lib\unittest\case.py", line 329, in run  
        testMethod()  
      File "C:\Python27_32\lib\site-packages\nose\loader.py", line 420, in loadTestsFromName
        addr.filename, addr.module)  
      File "C:\Python27_32\lib\site-packages\nose\importer.py", line 47, in importFromPath
        return self.importFromDir(dir_path, fqname)  
      File "C:\Python27_32\lib\site-packages\nose\importer.py", line 94, in importFromDir
        mod = load_module(part_fqname, fh, filename, desc)  
      File "C:\projects\pyemma\pyemma\plots\grandalf\routing.py", line 16, in <module>
        from grandalf.utils import \*  
    ImportError: No module named grandalf.utils

So the imports have to be made relative to the current location. If you want I can do it.

**Comment by franknoe** [comment]
Am 20/05/15 um 15:55 schrieb Martin K. Scherer:

> What a nice improvement! Grandalf does not seem to be on PyPI, so 
> thats why you imported it into the tree, right?
> 
> Yes. It also doesn't look very professional, so I wouldn't trust that 
> there is a continuous development line and we can rely on the API. 
> Anyway its GPL, so it should be fine to include it.
> 
> There is still one issue:
> Traceback (most recent call last):
> 
> File "C:\Python27_32\lib\unittest\case.py", line 329, in run
> 
> testMethod()
> 
> File "C:\Python27_32\lib\site-packages\nose\loader.py", line 420, in 
> loadTestsFromName
> addr.filename, addr.module)
> 
> File "C:\Python27_32\lib\site-packages\nose\importer.py", line 47, in 
> importFromPath
> return self.importFromDir(dir_path, fqname)
> 
> File "C:\Python27_32\lib\site-packages\nose\importer.py", line 94, in 
> importFromDir
> mod = load_module(part_fqname, fh, filename, desc)
> 
> File "C:\projects\pyemma\pyemma\plots\grandalf\routing.py", line 16, in
> from grandalf.utils import *
> 
> ImportError: No module named grandalf.utils
> 
> So the imports have to be made relative to the current location. If 
> you want I can do it.
> 
> Ah, true. Yes, please do it.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/314#issuecomment-103895729.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
So it seems everything is well, I'm ready to merge.

**Comment by marscher** [comment]
Shall we add some kind of readme which contains info and licenses of external libraries we use?

**Comment by franknoe** [comment]
Yes we can do that in our readme

Am 21/05/15 um 15:54 schrieb Martin K. Scherer:

> Shall we add some kind of readme which contains info and licenses of 
> external libraries we use?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/314#issuecomment-104284133.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Now i'm running the London tpt flux example (since 5 minutes, grandalf is trying to optimize the positions). That's prohibitive slow. Is there some kind of cutoff parameter?

**Comment by franknoe** [comment]
That's not good. But it's meant to plot only small networks, and in the 
London tpt flux example I only used a few (6 or so) states to be
visualized, and they had fixed positions on the TICA plot. Are you 
trying to plot the un-coarse-grained flux?

Am 22/05/15 um 18:56 schrieb Martin K. Scherer:

> Now i'm running the London tpt flux example (since 5 minutes, grandalf 
> is trying to optimize the positions). That's prohibitive slow. Is 
> there some kind of cutoff parameter?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/314#issuecomment-104712662.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
yes. That was my mistake. Thanks

**Comment by marscher** [comment]
It would be nice if the scaling factor of the fluxes is performed by the plotting routing, rather than performing that ourselfs before plotting. But anyway I like the syntax of reactive_flux.netflux[:] *= factor, did not know that this is even possible.

**Comment by franknoe** [comment]
It is determined automatically in the new plotting routine! You can use 
that an just override grandalf by setting the node positions by hand.

Am 22/05/15 um 19:14 schrieb Martin K. Scherer:

> It would be nices if the scaling factor of the fluxes is performed by 
> the plotting routing, rather than performing that ourselfs before 
> plotting. But anyway I like the syntax of reactive_flux.netflux[:] *= 
> factor, did not know that this is even possible.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/314#issuecomment-104717969.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Sure. Grandalf _is_ pretty slow, but this is partially because the 
method itself is quite expensive.
I meant to use it only for the visualization of coarse-grained networks 
(max. a few 10s of states).
I suggest to give a warning when the user is trying to use it with a lot 
of states, say > 50.

Am 22/05/15 um 19:08 schrieb Martin K. Scherer:

> yes. That was my mistake. Thanks
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/314#issuecomment-104715504.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I've added the warning in the NetworkPlot class.

**Pull request merged**
