### PR TITLE
Making thermo.estimate_umbrella_sampling() robust

### PR DESCRIPTION
**Pull request by cwehmeyer**
This PR addresses #812 

I refactored  the protected `thermo.util` functions which are called during `thermo.estimate_umbrella_sampling()` and added unit tests to check that all data formats which should be accepted are handled correctly.

### CODE REVIEW

**Comment by franknoe** [comment]
Awesome, thanks. @fabian-paul , can you review it?

**Comment by cwehmeyer** [comment]
FYI: the failed test on appveyor was not due to changes from this PR:

```
======================================================================
FAIL: test_ca_distances_with_all_atom_geometries (pyemma.coordinates.tests.test_featurizer.TestFeaturizer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\miniconda-x64\envs\_test\lib\site-packages\pyemma-2.2+16.g8ff4e97-py2.7-win-amd64.egg\pyemma\coordinates\tests\test_featurizer.py", line 195, in test_ca_distances_with_all_atom_geometries
    assert(np.allclose(D_aa, D_ca))
AssertionError: 
-------------------- >> begin captured logging << --------------------
pyemma.coordinates.data.featurization.featurizer.MDFeaturizer[154]: WARNING: The 1D arrays input for add_distances() have been sorted, and index duplicates have been eliminated.
Check the output of describe() to see the actual order of the features
--------------------- >> end captured logging << ---------------------
```

**Comment by cwehmeyer** [comment]
@fabian-paul @marscher 
Your recommended changes have been pushed to this PR. Do I have your OK to merge?

**Comment by fabian-paul** [comment]
Hi @cwehmeyer,

everything is solved but the problem with inconsistent trajectory lengths. Three tests out of the original list still give cryptic error messages.

``` python
import numpy as np
import pyemma
```

``` python
class TestRaises(object):
    def __init__(self, exception, do_raise=False):
        self.exception = exception
        self.do_raise = do_raise
    def __enter__(self):
        pass
    def __exit__(self, type, value, traceback):
        if type is not None and issubclass(type, self.exception):
            print 'ok:', value
        else:
            print 'failed:', value, type
        return not self.do_raise
```

``` python
us_dtrajs = [np.ones((100,), dtype=int), np.ones((100,), dtype=int)]
us_trajs = [np.ones((100,1)), np.ones((100,1))]
us_centers = [0, 0]
us_force_constants = [10, 10]
```

``` python
# dtrajs have wrong dimension 
wrong_us_dtrajs = [np.ones((100,)), np.ones((100,2))]
with TestRaises(Exception):
    pyemma.thermo.estimate_umbrella_sampling(us_trajs, wrong_us_dtrajs, us_centers, us_force_constants)
```

```
ok: too many indices for array
```

``` python
# length of elements of us_trajs and us_dtrajs is inconsistent
wrong_us_dtrajs = [np.ones((100,), dtype=int), np.ones((200,), dtype=int)]
with TestRaises(Exception):
    pyemma.thermo.estimate_umbrella_sampling(us_trajs, wrong_us_dtrajs, us_centers, us_force_constants)
```

```
ok: index 100 is out of bounds for axis 0 with size 100
```

``` python
md_trajs = [np.ones((100,1)), np.ones((100,1))]

# elements of md_trajs and md_dtrajs have inconsistent lengths
wrong_md_dtrajs = [np.ones((100,), dtype=int), np.ones((200,), dtype=int)]
with TestRaises(Exception):
    pyemma.thermo.estimate_umbrella_sampling(us_trajs, us_dtrajs, us_centers, us_force_constants, 
                                             md_dtrajs=wrong_md_dtrajs, md_trajs=md_trajs)
```

```
ok: index 100 is out of bounds for axis 0 with size 100
```

**Pull request merged**
