### PR TITLE
Move msmtools.flux.ReactiveFlux to pyemma.msm.models

### PR DESCRIPTION
**Pull request by marscher**
see #416 

In a follow up we should then remove the ReactiveFlux class from msmtools?

### CODE REVIEW

**Comment by marscher** [comment]
The tests passed on Travis. About to merge.

**Comment by franknoe** [comment]
I think that makes sense. Do we need to do it for 2.2, or can we 
postpone this?

Am 17/05/16 um 21:21 schrieb Martin K. Scherer:

> see #416 https://github.com/markovmodel/PyEMMA/issues/416
> 
> In a follow up we should then remove the ReactiveFlux class from msmtools?
> 
> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
> https://github.com/markovmodel/PyEMMA/pull/807
> 
> ```
>     Commit Summary
> ```
> - [msm] moved msmtools.flux.ReactiveFlux to pyemma.msm.models
> - fix test
> - reactiveflux became a model
>   
>   ```
>   File Changes
>   ```
> - _M_ pyemma/msm/**init**.py
>   https://github.com/markovmodel/PyEMMA/pull/807/files#diff-0 (5)
> - _M_ pyemma/msm/api.py
>   https://github.com/markovmodel/PyEMMA/pull/807/files#diff-1 (99)
> - _M_ pyemma/msm/models/**init**.py
>   https://github.com/markovmodel/PyEMMA/pull/807/files#diff-2 (1)
> - _A_ pyemma/msm/models/reactive_flux.py
>   https://github.com/markovmodel/PyEMMA/pull/807/files#diff-3 (378)
> - _A_ pyemma/msm/tests/test_reactive_flux.py
>   https://github.com/markovmodel/PyEMMA/pull/807/files#diff-4 (203)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/markovmodel/PyEMMA/pull/807.patch
> - https://github.com/markovmodel/PyEMMA/pull/807.diff
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/807

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
some failures, but I don't understood what's wrong here.

**Comment by franknoe** [comment]
sorry, I had closed by mistake

**Comment by marscher** [comment]
The failures are caused because I've pushed the branch to origin instead to my fork, so travis opened up another special build for that, but in the meantime (while this job was running), I deleted the branch.

**Comment by franknoe** [comment]
BTW, I guess that also means that we will remove ReactiveFlux from msmtools in a future version? We should deprecate it then.

**Comment by marscher** [comment]
Yes, we should not have this "duplicate" for a long time.

**Pull request merged**
