### PR TITLE
Merge 1.3 release branch into devel

### PR DESCRIPTION
**Pull request by franknoe**
The previously experimental Estimator/Model framework is now more mature. Merging this feature branch into devel to prepare for the next release.

### CODE REVIEW

**Comment by franknoe** [comment]
OK, this merge has worked. Travis runs without errors.

@trendelkampschroer I manually carries your changes made to the msm.generation and msm.analysis in the pyEMMA's devel version over to msmtools and merged them into the devel branch there. 

I suspect this will still have the windows file I/O failure. We should fix that before merging into devel. @fabian-paul can you have a look when AppVeyor has finished, and try to fix that problem if it occurs?

**Comment by franknoe** [comment]
OK, everything works apart from this failure on Windows, which is due to a non-closed file. @fabian-paul  and @gph82  please look into it. You can fix it on the branch FN_merge_1.3_into_devel and just re-push that, which will trigger a new round of tests.

``` python
======================================================================
ERROR: test suite for <class 'pyemma.coordinates.tests.test_featurizer.TestFeaturizer'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27_32\lib\site-packages\nose\suite.py", line 209, in run
    self.setUp()
  File "C:\Python27_32\lib\site-packages\nose\suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "C:\Python27_32\lib\site-packages\nose\suite.py", line 315, in setupContext
    try_run(context, names)
  File "C:\Python27_32\lib\site-packages\nose\util.py", line 471, in try_run
    return func()
  File "C:\projects\pyemma\pyemma\coordinates\tests\test_featurizer.py", line 92, in setUpClass
    traj.save(cls.asn_leu_traj)
  File "C:\Python27_32\lib\site-packages\mdtraj-1.4.2-py2.7-win32.egg\mdtraj\core\trajectory.py", line 1228, in save
    return saver(filename, **kwargs)
  File "C:\Python27_32\lib\site-packages\mdtraj-1.4.2-py2.7-win32.egg\mdtraj\core\trajectory.py", line 1333, in save_xtc
    with XTCTrajectoryFile(filename, 'w', force_overwrite=force_overwrite) as f:
  File "xtc.pyx", line 233, in xtc.XTCTrajectoryFile.__cinit__ (mdtraj/formats/xtc/xtc.c:2794)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\appveyor\\appdata\\local\\temp\\1\\tmp4nivaf.xtc'

----------------------------------------------------------------------
Ran 396 tests in 65.481s

```

**Comment by gph82** [comment]
we've already started to look into this 4-eyed, not sure if our problem
or mdtraj's. Updates will follow

On 08/03/2015 03:39 PM, Frank Noe wrote:

> OK, everything works apart from this failure on Windows, which is due to
> a non-closed file. @fabian-paul https://github.com/fabian-paul and
> @gph82 https://github.com/gph82 please look into it. You can fix it on
> the branch FN_merge_1.3_into_devel and just re-push that, which will
> trigger a new round of tests.
> 
> # 
> 
> ## ERROR: test suite for <class 'pyemma.coordinates.tests.test_featurizer.TestFeaturizer'>
> 
> Traceback (most recent call last):
>   File "C:\Python27_32\lib\site-packages\nose\suite.py", line 209, in run
>     self.setUp()
>   File "C:\Python27_32\lib\site-packages\nose\suite.py", line 292, in setUp
>     self.setupContext(ancestor)
>   File "C:\Python27_32\lib\site-packages\nose\suite.py", line 315, in setupContext
>     try_run(context, names)
>   File "C:\Python27_32\lib\site-packages\nose\util.py", line 471, in try_run
>     return func()
>   File "C:\projects\pyemma\pyemma\coordinates\tests\test_featurizer.py", line 92, in setUpClass
>     traj.save(cls.asn_leu_traj)
>   File "C:\Python27_32\lib\site-packages\mdtraj-1.4.2-py2.7-win32.egg\mdtraj\core\trajectory.py", line 1228, in save
>     return saver(filename, **kwargs)
>   File "C:\Python27_32\lib\site-packages\mdtraj-1.4.2-py2.7-win32.egg\mdtraj\core\trajectory.py", line 1333, in save_xtc
>     with XTCTrajectoryFile(filename, 'w', force_overwrite=force_overwrite) as f:
>   File "xtc.pyx", line 233, in xtc.XTCTrajectoryFile.**cinit** (mdtraj/formats/xtc/xtc.c:2794)
> WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\users\appveyor\appdata\local\temp\1\tmp4nivaf.xtc'
> 
> ---
> 
> Ran 396 tests in 65.481s
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/pull/477#issuecomment-127237142.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

## http://userpage.fu-berlin.de/gph82/

**Comment by franknoe** [comment]
Thanks!

Am 03/08/15 um 15:48 schrieb Guillermo Pérez-Hernández:

> we've already started to look into this 4-eyed, not sure if our problem
> or mdtraj's. Updates will follow
> 
> On 08/03/2015 03:39 PM, Frank Noe wrote:
> 
> > OK, everything works apart from this failure on Windows, which is due to
> > a non-closed file. @fabian-paul https://github.com/fabian-paul and
> > @gph82 https://github.com/gph82 please look into it. You can fix it on
> > the branch FN_merge_1.3_into_devel and just re-push that, which will
> > trigger a new round of tests.
> > 
> > # 
> > 
> > ERROR: test suite for <class 
> > 
> > ## 'pyemma.coordinates.tests.test_featurizer.TestFeaturizer'>
> > 
> > Traceback (most recent call last):
> > File "C:\Python27_32\lib\site-packages\nose\suite.py", line 209, in run
> > self.setUp()
> > File "C:\Python27_32\lib\site-packages\nose\suite.py", line 292, in 
> > setUp
> > self.setupContext(ancestor)
> > File "C:\Python27_32\lib\site-packages\nose\suite.py", line 315, in 
> > setupContext
> > try_run(context, names)
> > File "C:\Python27_32\lib\site-packages\nose\util.py", line 471, in 
> > try_run
> > return func()
> > File 
> > "C:\projects\pyemma\pyemma\coordinates\tests\test_featurizer.py", line 
> > 92, in setUpClass
> > traj.save(cls.asn_leu_traj)
> > File 
> > "C:\Python27_32\lib\site-packages\mdtraj-1.4.2-py2.7-win32.egg\mdtraj\core\trajectory.py", 
> > line 1228, in save
> > return saver(filename, **kwargs)
> > File 
> > "C:\Python27_32\lib\site-packages\mdtraj-1.4.2-py2.7-win32.egg\mdtraj\core\trajectory.py", 
> > line 1333, in save_xtc
> > with XTCTrajectoryFile(filename, 'w', 
> > force_overwrite=force_overwrite) as f:
> > File "xtc.pyx", line 233, in xtc.XTCTrajectoryFile.**cinit** 
> > (mdtraj/formats/xtc/xtc.c:2794)
> > WindowsError: [Error 32] The process cannot access the file because 
> > it is being used by another process: 
> > 'c:\users\appveyor\appdata\local\temp\1\tmp4nivaf.xtc'
> > 
> > ---
> > 
> > Ran 396 tests in 65.481s
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/markovmodel/PyEMMA/pull/477#issuecomment-127237142.
> 
> ## 
> 
> Dr. Guillermo Pérez-Hernández
> Freie Universität Berlin
> Institute for Mathematics
> Arnimallee 6
> D-14195 Berlin
> tel 0049 30 838 75776
> 
> ## http://userpage.fu-berlin.de/gph82/
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/477#issuecomment-127241048.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by fabian-paul** [comment]
Ok, I have found the error and fixed it but I can't compile the FN_merge_1.3_into_devel branch under Windows. devel branch works find and I've tested my fix there.
That what I get:

```
Processing dependencies for pyEMMA==1.2.2+145.gb79564f.dirty
Searching for bhmm
Reading https://pypi.python.org/simple/bhmm/
Best match: bhmm 0.3.0
Downloading https://pypi.python.org/packages/source/b/bhmm/bhmm-0.3.0.tar.gz#md5
=6fe276a1edc5732e44baf037b50e05de
Processing bhmm-0.3.0.tar.gz
Writing c:\users\paul_l\appdata\local\temp\easy_install-ssrboq\bhmm-0.3.0\setup.
cfg
Running bhmm-0.3.0\setup.py -q bdist_egg --dist-dir c:\users\paul_l\appdata\loca
l\temp\easy_install-ssrboq\bhmm-0.3.0\egg-dist-tmp-ke6cws
Traceback (most recent call last):
  File "setup.py", line 277, in <module>
    setup(**metadata)
  File "D:\Program Files (x86)\Anaconda\lib\distutils\core.py", line 151, in set
up
    dist.run_commands()
  File "D:\Program Files (x86)\Anaconda\lib\distutils\dist.py", line 953, in run
_commands
    self.run_command(cmd)
  File "D:\Program Files (x86)\Anaconda\lib\distutils\dist.py", line 972, in run
_command
    cmd_obj.run()
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
7.egg\setuptools\command\develop.py", line 32, in run
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
7.egg\setuptools\command\develop.py", line 132, in install_for_development
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
7.egg\setuptools\command\easy_install.py", line 709, in process_distribution
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
7.egg\pkg_resources\__init__.py", line 836, in resolve
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
7.egg\pkg_resources\__init__.py", line 1081, in best_match
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
7.egg\pkg_resources\__init__.py", line 1093, in obtain
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
7.egg\setuptools\command\easy_install.py", line 629, in easy_install
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
7.egg\setuptools\command\easy_install.py", line 659, in install_item
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
7.egg\setuptools\command\easy_install.py", line 842, in install_eggs
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
7.egg\setuptools\command\easy_install.py", line 1070, in build_and_install
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
7.egg\setuptools\command\easy_install.py", line 1056, in run_setup
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
7.egg\setuptools\sandbox.py", line 240, in run_setup
  File "D:\Program Files (x86)\Anaconda\lib\contextlib.py", line 35, in __exit__

    self.gen.throw(type, value, traceback)
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
7.egg\setuptools\sandbox.py", line 193, in setup_context
  File "D:\Program Files (x86)\Anaconda\lib\contextlib.py", line 35, in __exit__

    self.gen.throw(type, value, traceback)
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
7.egg\setuptools\sandbox.py", line 164, in save_modules
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
7.egg\setuptools\sandbox.py", line 139, in resume
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
7.egg\setuptools\sandbox.py", line 152, in save_modules
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
7.egg\setuptools\sandbox.py", line 193, in setup_context
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
7.egg\setuptools\sandbox.py", line 237, in run_setup
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
7.egg\setuptools\sandbox.py", line 267, in run
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
7.egg\setuptools\sandbox.py", line 236, in runner
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
7.egg\setuptools\sandbox.py", line 46, in _execfile
  File "c:\users\paul_l\appdata\local\temp\easy_install-ssrboq\bhmm-0.3.0\setup.
py", line 173, in <module>
    def initialize_options(self):
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\Cython\Build\Dependenc
ies.py", line 754, in cythonize
    aliases=aliases)
  File "D:\Program Files (x86)\Anaconda\lib\site-packages\Cython\Build\Dependenc
ies.py", line 647, in create_extension_list
    raise TypeError(pattern)
TypeError: <setuptools.extension.Extension instance at 0x000000000EFFC188>
```

**Comment by franknoe** [comment]
The current pyEMMA dev_release_1.3 branch (and the branch you are 
working on) requires the bhmm Master branch that is not yet released. 
This is for being able to run tests and merge branches while we are 
developing two things in parallel. I believe if you want to install you 
might have to install bhmm from the git separately. Below it's instead 
trying to use the last release.
The same holds for msmtools devel.

Am 03/08/15 um 16:12 schrieb fabian-paul:

> Ok, I have found the error and fixed it but I can't compile the 
> FN_merge_1.3_into_devel branch under Windows. devel branch works find 
> and I've tested my fix there.
> That what I get:
> 
> |Processing dependencies for pyEMMA==1.2.2+145.gb79564f.dirty
> Searching for bhmm
> Reading https://pypi.python.org/simple/bhmm/
> Best match: bhmm 0.3.0
> Downloading https://pypi.python.org/packages/source/b/bhmm/bhmm-0.3.0.tar.gz#md5
> =6fe276a1edc5732e44baf037b50e05de
> Processing bhmm-0.3.0.tar.gz
> Writing c:\users\paul_l\appdata\local\temp\easy_install-ssrboq\bhmm-0.3.0\setup.
> cfg
> Running bhmm-0.3.0\setup.py -q bdist_egg --dist-dir c:\users\paul_l\appdata\loca
> l\temp\easy_install-ssrboq\bhmm-0.3.0\egg-dist-tmp-ke6cws
> Traceback (most recent call last):
>    File "setup.py", line 277, in <module>
>      setup(**metadata)
>    File "D:\Program Files (x86)\Anaconda\lib\distutils\core.py", line 151, in set
> up
>      dist.run_commands()
>    File "D:\Program Files (x86)\Anaconda\lib\distutils\dist.py", line 953, in run
> _commands
>      self.run_command(cmd)
>    File "D:\Program Files (x86)\Anaconda\lib\distutils\dist.py", line 972, in run
> _command
>      cmd_obj.run()
>    File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
> 7.egg\setuptools\command\develop.py", line 32, in run
>    File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
> 7.egg\setuptools\command\develop.py", line 132, in install_for_development
>    File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
> 7.egg\setuptools\command\easy_install.py", line 709, in process_distribution
>    File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
> 7.egg\pkg_resources__init__.py", line 836, in resolve
>    File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
> 7.egg\pkg_resources__init__.py", line 1081, in best_match
>    File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
> 7.egg\pkg_resources__init__.py", line 1093, in obtain
>    File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
> 7.egg\setuptools\command\easy_install.py", line 629, in easy_install
>    File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
> 7.egg\setuptools\command\easy_install.py", line 659, in install_item
>    File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
> 7.egg\setuptools\command\easy_install.py", line 842, in install_eggs
>    File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
> 7.egg\setuptools\command\easy_install.py", line 1070, in build_and_install
>    File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
> 7.egg\setuptools\command\easy_install.py", line 1056, in run_setup
>    File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
> 7.egg\setuptools\sandbox.py", line 240, in run_setup
>    File "D:\Program Files (x86)\Anaconda\lib\contextlib.py", line 35, in **exit**
> 
> ```
>  self.gen.throw(type, value, traceback)
> ```
> 
>    File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
> 7.egg\setuptools\sandbox.py", line 193, in setup_context
>    File "D:\Program Files (x86)\Anaconda\lib\contextlib.py", line 35, in **exit**
> 
> ```
>  self.gen.throw(type, value, traceback)
> ```
> 
>    File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
> 7.egg\setuptools\sandbox.py", line 164, in save_modules
>    File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
> 7.egg\setuptools\sandbox.py", line 139, in resume
>    File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
> 7.egg\setuptools\sandbox.py", line 152, in save_modules
>    File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
> 7.egg\setuptools\sandbox.py", line 193, in setup_context
>    File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
> 7.egg\setuptools\sandbox.py", line 237, in run_setup
>    File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
> 7.egg\setuptools\sandbox.py", line 267, in run
>    File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
> 7.egg\setuptools\sandbox.py", line 236, in runner
>    File "D:\Program Files (x86)\Anaconda\lib\site-packages\setuptools-17.1.1-py2.
> 7.egg\setuptools\sandbox.py", line 46, in _execfile
>    File "c:\users\paul_l\appdata\local\temp\easy_install-ssrboq\bhmm-0.3.0\setup.
> py", line 173, in <module>
>      def initialize_options(self):
>    File "D:\Program Files (x86)\Anaconda\lib\site-packages\Cython\Build\Dependenc
> ies.py", line 754, in cythonize
>      aliases=aliases)
>    File "D:\Program Files (x86)\Anaconda\lib\site-packages\Cython\Build\Dependenc
> ies.py", line 647, in create_extension_list
>      raise TypeError(pattern)
> TypeError: <setuptools.extension.Extension instance at 0x000000000EFFC188>
> |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/477#issuecomment-127256463.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Yay, now it's building under Windoof too. Thank a lot for the quick fix guys. I am merging.

**Comment by franknoe** [comment]
BTW, coverage decrease is due to the removal of msmtools from the package which is "news" for the devel branch. The relative coverages of the parts didn't change, and therefore this rather big apparent decrease is not a problem of this merge. We still need a few more tests for the Model/Estimator world before considering a release though.

**Pull request merged**
