### PR TITLE
Add stride for save trajs

### PR DESCRIPTION
**Pull request by gph82**
This  closes #309 i'm trying to merge to the same branch as @marscher was doing in #309 , but now there are some conflicts. Not sure how to handle this best.

Now frames_from_file gets its own test (tests for save_trajs have also been extended to test the stride functionality). 

I think we should anyways take save_traj out of the api and give save_trajs a "flatten" option. Otherwise it's a bit confusing. I'll do that next.

### CODE REVIEW

**Comment by franknoe** [comment]
Why is that confusing? save_traj is e.g. for saving a single trajectory 
generated by MSM.generate_traj. Might be more confusing to have to go 
through the save_trajs interface for that.

Am 20/05/15 um 12:44 schrieb Guillermo Pérez-Hernández:

> This close #309 https://github.com/markovmodel/PyEMMA/pull/309 i'm 
> trying to merge to the same branch as @marscher 
> https://github.com/marscher was doing in #309 
> https://github.com/markovmodel/PyEMMA/pull/309 , but now there are 
> some conflicts. Not sure how to handle this best.
> 
> Now frames_from_file gets its own test (tests for save_trajs have also 
> been extended to test the stride functionality).
> 
> I think we should anyways take save_traj out of the api and give 
> save_trajs a "flatten" option. Otherwise it's a bit confusing. I'll do 
> that next.
> 
> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
> https://github.com/markovmodel/PyEMMA/pull/313
> 
> ```
>     Commit Summary
> ```
> - [coor/save_trajs] added stride parameter.
> - Added and tested the stride functionality for save_trajs
>   
>   ```
>   File Changes
>   ```
> - _M_ pyemma/coordinates/api.py
>   https://github.com/markovmodel/PyEMMA/pull/313/files#diff-0 (46)
> - _M_ pyemma/coordinates/data/frames_from_file.py
>   https://github.com/markovmodel/PyEMMA/pull/313/files#diff-1 (25)
> - _A_ pyemma/coordinates/tests/test_frames_from_file.py
>   https://github.com/markovmodel/PyEMMA/pull/313/files#diff-2 (114)
> - _M_ pyemma/coordinates/tests/test_save_trajs.py
>   https://github.com/markovmodel/PyEMMA/pull/313/files#diff-3 (14)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/markovmodel/PyEMMA/pull/313.patch
> - https://github.com/markovmodel/PyEMMA/pull/313.diff
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/313.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
Ok let's merge (if wanted) and I'll explain afterwards. Haven't started anything yet, anyway

## 

Sent from my phone. 
Apologies for typos, unusual tone or brevity 

-------- Original message --------

**Comment by marscher** [comment]
You wanna merge save_traj with save_trajs? You might consider doing that on a new rebased branch against devel, as I am going to merge dev_release_1.2.1 back into devel

**Comment by gph82** [comment]
No, or not right now. 

My PR keeps everything as is, only with the stride parameter. 

## 

Sent from my phone. 
Apologies for typos, unusual tone or brevity 

-------- Original message --------

**Pull request closed without merging**
