### PR TITLE
LGPLv3 headers

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by franknoe** [comment]
I noticed a commit change in pyemma-ipython. Is that on purpose? Please make sure this is still pointing to the right branch (which was devel when I set it).

**Comment by franknoe** [comment]
Sorry for being unclear: the licence holder needs to include the institution. Let's better be complete:

```
Copyright (c) 2015, 2014 Computational Molecular Biology Group, Freie Universitaet Berlin (GER)
```

**Comment by marscher** [comment]
the ipython commit was an accident. Actually the repo contains a lot of files under version control which should not be there (like generated images etc.). So my copy was dirty and I used commit -a...

I hope the change will be just a copy and replace. Fuddling around with sed and copyright_headers is not fun at all...

**Comment by franknoe** [comment]
Am 30/08/15 um 22:54 schrieb Martin K. Scherer:

> the ipython commit was an accident. Actually the repo contains a lot 
> of files under version control which should not be there (like 
> generated images etc.). So my copy was dirty and I used commit -a...
> 
> Are you talking about a commit of the IPython Repo? That's no problem. I 
> was just worried the setting of the branch in the pyemma-ipython 
> submodule got switched back to master.
> 
> I hope the change will be just a copy and replace. Fuddling around 
> with sed and copyright_headers is not fun at all...
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/529#issuecomment-136189544.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
not to master, but a local commit of mine - should have led to an error actually.

**Pull request merged**
