### PR TITLE
implemented the save traj function in the api. Tested

### PR DESCRIPTION
**Pull request by gph82**
See the test here: http://page.mi.fu-berlin.de/gph82/test_save_traj.html

Once I learn how to write tests properly (test_save_traj.py) I will write one

Next one will be save_trajs

### CODE REVIEW

**Comment by franknoe** [comment]
Thanks! Have a look at the coordinates/tests directory to see how this 
is done.

Basic idea:
- In one test module you test the functionalities of another module.
- In the setup method you compute stuff you need for multiple tests
- Every test method needs to start with 'test' and compares the results 
of the tested method with the expected results.
- Simple tests should include: Do I get a trajectory that is readable? 
Do I get the right number of trajectories? Etc.

Am 03/04/15 um 02:25 schrieb Guillermo Pérez-Hernández:
>
> See the test here: http://page.mi.fu-berlin.de/gph82/test_save_traj.html
>
> Once I learn how to write tests properly (test_save_traj.py) I will 
> write one
>
> Next one will be save_trajs
>
> ------------------------------------------------------------------------
>
>
>         You can view, comment on, or merge this pull request online at:
>
> https://github.com/markovmodel/PyEMMA/pull/182
>
>
>         Commit Summary
>
>   * [discretizer] base class is now Pipeline
>   * [transformer] made operate_in_memory a setter for in_memory
>   * [pipeline] fixes
>   * [readers] made them transformers, since they share 90% of the
>     interface
>   * [transformer] made map_to_memory private, since its called from
>     in_memory
>   * [mdtraj-patch] log critical message if traj is being loaded completly
>   * [setup] minor changes
>   * [datainmemory-test] wip
>   * [discretizer-test] use api functions
>   * [DataInMemory] reset time if itraj is incremented.
>   * removed dbg statements
>   * [coor/api] * discretizer does not use a default instance, since
>     this leads dramatic side effects.
>   * [coor/api] add featurizer to api
>   * [coor] hide impl detail in transformers (fixes #169)
>   * fix imports
>   * [corr/util/patches] fix bug in iterload. Fixes #174
>   * Described (and partially did) discussed coordinate API changes
>   * Described (and partially did) discussed coordinate API changes
>   * Merge branch 'refactor_discretizer' of
>     https://github.com/markovmodel/pyemma into refactor_discretizer
>   * added function headers for save_traj
>   * implemented save_traj, test pending to be ported from ipynb to .py
>
>
>         File Changes
>
>   * *M* pyemma/cli/.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-0> (2)
>   * *M* pyemma/cli/mm_ipython.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-1> (4)
>   * *M* pyemma/coordinates/api.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-2> (330)
>   * *M* pyemma/coordinates/clustering/assign.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-3> (4)
>   * *M* pyemma/coordinates/clustering/interface.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-4> (27)
>   * *M* pyemma/coordinates/clustering/kmeans.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-5> (23)
>   * *M* pyemma/coordinates/clustering/regspace.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-6> (10)
>   * *M* pyemma/coordinates/clustering/uniform_time.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-7> (14)
>   * *D* pyemma/coordinates/discretizer.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-8> (184)
>   * *M* pyemma/coordinates/io/data_in_memory.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-9> (73)
>   * *M* pyemma/coordinates/io/feature_reader.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-10> (89)
>   * *M* pyemma/coordinates/io/featurizer.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-11> (2)
>   * *A* pyemma/coordinates/io/frames_from_file.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-12> (47)
>   * *D* pyemma/coordinates/io/reader.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-13> (23)
>   * *M* pyemma/coordinates/io/writer.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-14> (8)
>   * *A* pyemma/coordinates/pipeline.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-15> (275)
>   * *A* pyemma/coordinates/tests/data/bpti_001-033.xtc
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-16> (0)
>   * *A* pyemma/coordinates/tests/data/bpti_034-066.xtc
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-17> (0)
>   * *A* pyemma/coordinates/tests/data/bpti_067-100.xtc
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-18> (0)
>   * *A* pyemma/coordinates/tests/data/test_save_trajs.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-19> (0)
>   * *M* pyemma/coordinates/tests/test_datainmemory.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-20> (89)
>   * *M* pyemma/coordinates/tests/test_discretizer.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-21> (22)
>   * *M* pyemma/coordinates/tests/test_featurereader.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-22> (2)
>   * *M* pyemma/coordinates/tests/test_featurereader_and_tica.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-23> (2)
>   * *M*
>     pyemma/coordinates/tests/test_featurereader_and_tica_projection.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-24> (2)
>   * *M* pyemma/coordinates/tests/test_regspace.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-25> (4)
>   * *M* pyemma/coordinates/tests/test_tica.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-26> (2)
>   * *M* pyemma/coordinates/transform/pca.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-27> (12)
>   * *M* pyemma/coordinates/transform/tica.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-28> (37)
>   * *M* pyemma/coordinates/transform/transformer.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-29> (201)
>   * *M* pyemma/coordinates/util/chaining.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-30> (5)
>   * *M* pyemma/coordinates/util/patches.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-31> (3)
>   * *M* setup.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-32> (8)
>   * *M* versioneer.py
>     <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-33> (2)
>
>
>         Patch Links:
>
>   * https://github.com/markovmodel/PyEMMA/pull/182.patch
>   * https://github.com/markovmodel/PyEMMA/pull/182.diff
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/pull/182>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by gph82** [comment]
Hi!
Hmm....
I don't know how I did it but my PR also has a lot of stuff that i did not 
"touch"...did I mess something up? I only noticed today

On 04/03/2015 02:32 AM, Frank Noe wrote:
> Thanks! Have a look at the coordinates/tests directory to see how this
> is done.
>
> Basic idea:
> - In one test module you test the functionalities of another module.
> - In the setup method you compute stuff you need for multiple tests
> - Every test method needs to start with 'test' and compares the results
> of the tested method with the expected results.
> - Simple tests should include: Do I get a trajectory that is readable?
> Do I get the right number of trajectories? Etc.
>
> Am 03/04/15 um 02:25 schrieb Guillermo Pérez-Hernández:
>  >
>  > See the test here: http://page.mi.fu-berlin.de/gph82/test_save_traj.html
>  >
>  > Once I learn how to write tests properly (test_save_traj.py) I will
>  > write one
>  >
>  > Next one will be save_trajs
>  >
>  > ------------------------------------------------------------------------
>  >
>  >
>  > You can view, comment on, or merge this pull request online at:
>  >
>  > https://github.com/markovmodel/PyEMMA/pull/182
>  >
>  >
>  > Commit Summary
>  >
>  > * [discretizer] base class is now Pipeline
>  > * [transformer] made operate_in_memory a setter for in_memory
>  > * [pipeline] fixes
>  > * [readers] made them transformers, since they share 90% of the
>  > interface
>  > * [transformer] made map_to_memory private, since its called from
>  > in_memory
>  > * [mdtraj-patch] log critical message if traj is being loaded completly
>  > * [setup] minor changes
>  > * [datainmemory-test] wip
>  > * [discretizer-test] use api functions
>  > * [DataInMemory] reset time if itraj is incremented.
>  > * removed dbg statements
>  > * [coor/api] * discretizer does not use a default instance, since
>  > this leads dramatic side effects.
>  > * [coor/api] add featurizer to api
>  > * [coor] hide impl detail in transformers (fixes #169)
>  > * fix imports
>  > * [corr/util/patches] fix bug in iterload. Fixes #174
>  > * Described (and partially did) discussed coordinate API changes
>  > * Described (and partially did) discussed coordinate API changes
>  > * Merge branch 'refactor_discretizer' of
>  > https://github.com/markovmodel/pyemma into refactor_discretizer
>  > * added function headers for save_traj
>  > * implemented save_traj, test pending to be ported from ipynb to .py
>  >
>  >
>  > File Changes
>  >
>  > * *M* pyemma/cli/.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-0> (2)
>  > * *M* pyemma/cli/mm_ipython.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-1> (4)
>  > * *M* pyemma/coordinates/api.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-2> (330)
>  > * *M* pyemma/coordinates/clustering/assign.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-3> (4)
>  > * *M* pyemma/coordinates/clustering/interface.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-4> (27)
>  > * *M* pyemma/coordinates/clustering/kmeans.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-5> (23)
>  > * *M* pyemma/coordinates/clustering/regspace.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-6> (10)
>  > * *M* pyemma/coordinates/clustering/uniform_time.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-7> (14)
>  > * *D* pyemma/coordinates/discretizer.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-8> (184)
>  > * *M* pyemma/coordinates/io/data_in_memory.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-9> (73)
>  > * *M* pyemma/coordinates/io/feature_reader.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-10> (89)
>  > * *M* pyemma/coordinates/io/featurizer.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-11> (2)
>  > * *A* pyemma/coordinates/io/frames_from_file.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-12> (47)
>  > * *D* pyemma/coordinates/io/reader.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-13> (23)
>  > * *M* pyemma/coordinates/io/writer.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-14> (8)
>  > * *A* pyemma/coordinates/pipeline.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-15> (275)
>  > * *A* pyemma/coordinates/tests/data/bpti_001-033.xtc
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-16> (0)
>  > * *A* pyemma/coordinates/tests/data/bpti_034-066.xtc
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-17> (0)
>  > * *A* pyemma/coordinates/tests/data/bpti_067-100.xtc
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-18> (0)
>  > * *A* pyemma/coordinates/tests/data/test_save_trajs.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-19> (0)
>  > * *M* pyemma/coordinates/tests/test_datainmemory.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-20> (89)
>  > * *M* pyemma/coordinates/tests/test_discretizer.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-21> (22)
>  > * *M* pyemma/coordinates/tests/test_featurereader.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-22> (2)
>  > * *M* pyemma/coordinates/tests/test_featurereader_and_tica.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-23> (2)
>  > * *M*
>  > pyemma/coordinates/tests/test_featurereader_and_tica_projection.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-24> (2)
>  > * *M* pyemma/coordinates/tests/test_regspace.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-25> (4)
>  > * *M* pyemma/coordinates/tests/test_tica.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-26> (2)
>  > * *M* pyemma/coordinates/transform/pca.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-27> (12)
>  > * *M* pyemma/coordinates/transform/tica.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-28> (37)
>  > * *M* pyemma/coordinates/transform/transformer.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-29> (201)
>  > * *M* pyemma/coordinates/util/chaining.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-30> (5)
>  > * *M* pyemma/coordinates/util/patches.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-31> (3)
>  > * *M* setup.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-32> (8)
>  > * *M* versioneer.py
>  > <https://github.com/markovmodel/PyEMMA/pull/182/files#diff-33> (2)
>  >
>  >
>  > Patch Links:
>  >
>  > * https://github.com/markovmodel/PyEMMA/pull/182.patch
>  > * https://github.com/markovmodel/PyEMMA/pull/182.diff
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  > <https://github.com/markovmodel/PyEMMA/pull/182>.
>  >
>
>
> --
>
> ----------------------------------------------
> Prof. Dr. Frank Noe
> Head of Computational Molecular Biology group
> Freie Universitaet Berlin
>
> Phone: (+49) (0)30 838 75354
> Web: research.franknoe.de
> Mail: Arnimallee 6, 14195 Berlin, Germany
> ----------------------------------------------
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markovmodel/PyEMMA/pull/182#issuecomment-89093545>.
>

-- 
Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

**Comment by franknoe** [comment]
These are all changes of the refactor_discretizer branch you have branched from with respect to devel with respect to which the merge appears to be.
@marscher: shouldn't we first merge into the refactor_discretizer branch before things are tested? I think we should keep a functional devel branch at any time.

**Comment by gph82** [comment]
This might be above my current git/branching know-how. Anyway, I'm pretty clear about where my changes happened. How do we fix this?

**Comment by franknoe** [comment]
I believe you don't need to do anything about this. Martin can decide 
which branch to merge with.
However, I would prefer If you put your tests in a Unit Test format (see 
description). We can help with that, but you should formalize what is 
the reference for each test and how one decides whether the test should 
be passed or not.

-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by gph82** [comment]
yeah, I'll look into that.

**Comment by franknoe** [comment]
@gph82 Please close this PR and try again with the right base branch (refactor_discretizer).
Thanks

**Pull request closed without merging**
