### PR TITLE
Enabling thermotools >=0.2

### PR DESCRIPTION
**Pull request by cwehmeyer**

### CODE REVIEW

**Comment by marscher** [comment]
Looks great, thank you!

**Comment by marscher** [comment]
@cwehmeyer did you change the API of pyemma.thermo or can we merge this for the 2.1.2 release?

**Comment by cwehmeyer** [comment]
The API changed only slightly, i.e., some functions have additional optional parameters. I think it can be merged.

**Comment by franknoe** [comment]
Are the PyEMMA devel branch tests running with this thermotools version?

Am 27/04/16 um 16:04 schrieb Christoph Wehmeyer:

> The API changed only slightly, i.e., some functions have additional 
> optional parameters. I think it can be merged.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/785#issuecomment-215094005

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by cwehmeyer** [comment]
Yes, they do. The failed tests on appveyor in this PR are not related to pyemma.thermo.

**Comment by franknoe** [comment]
Thanks.

This TICA test failure has been randomly reappearing, we should fix it.

Am 27/04/16 um 16:11 schrieb Christoph Wehmeyer:

> Yes, they do. The failed tests on appveyor in this PR are not related 
> to pyemma.thermo.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/785#issuecomment-215096265

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 27.04.2016 um 16:14 schrieb Frank Noe:

> Thanks.
> 
> This TICA test failure has been randomly reappearing, we should fix it.

I've set the tolerance too high high for this test. Will fix it

**Comment by marscher** [comment]
I've pushed that tiny change directly to devel.

**Pull request merged**
