### PR TITLE
Estimator cleanup

### PR DESCRIPTION
**Pull request by franknoe**

### CODE REVIEW

**Comment by franknoe** [comment]
@marscher , how can I rerun the CI tests? Those have failed because the server seems overloaded.

**Comment by marscher** [comment]
Am 22.07.2015 um 17:15 schrieb Frank Noe:

**Comment by franknoe** [comment]
no, I don't have that button even after signing in

**Comment by franknoe** [comment]
This is still the windows compilation issue. I'll merge this for now as this is a feature branch.

**Pull request merged**
