### PR TITLE
Docs organization for objects

### PR DESCRIPTION
**Pull request by clonker**
This PR deals with #321. There is now an extension of the .. autosummary:: directive that pulls all the attributes and methods of a class automatically.

### CODE REVIEW

**Comment by clonker** [comment]
FAIL: test_cov_tau (pyemma.coordinates.tests.test_tica.TestTICAExtensive)

This fails locally for me in average like every 5th time. Perhaps one should relax the 

``` python
assert (np.max(self.tica_obj.cov_tau - cov_tau_ref) < 3e-2)
```

condition?

**Comment by franknoe** [comment]
@fabian-paul, can you look into this?

Am 11/06/15 um 16:43 schrieb Moritz Hoffmann:

> FAIL: test_cov_tau (pyemma.coordinates.tests.test_tica.TestTICAExtensive)
> 
> This fails locally for me in average like every 5th time. Perhaps one 
> should relax the
> 
> assert  (np.max(self.tica_obj.cov_tau-  cov_tau_ref)<  3e-2)
> 
> condition?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/352#issuecomment-111158180.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by clonker** [comment]
@marscher Can this be merged?

**Comment by franknoe** [comment]
You are just adding a functionality to the doc generator, right? If so, 
I can also merge this.

Am 01/07/15 um 11:05 schrieb Moritz Hoffmann:

> @marscher https://github.com/marscher Can this be merged?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/352#issuecomment-117552802.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by clonker** [comment]
Yes, including the respective changes to the documentation in the source files. However, the PR was created before the dev_release_1.3 branch existed, so it refers to the devel branch and might lead to merge conflicts. Should I close and reopen with dev_release_1.3 or can it be merged anyways?

**Comment by franknoe** [comment]
I'll accept the PR to devel. Please then do a rebase on dev_release_1.3 
and handle possible conflicts if you can.

Am 01/07/15 um 11:11 schrieb Moritz Hoffmann:

> Yes, including the respective changes to the documentation in the 
> source files. However, the PR was created before the dev_release_1.3 
> branch existed, so it refers to the devel branch and might lead to 
> merge conflicts. Should I close and reopen with dev_release_1.3 or can 
> it be merged anyways?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/352#issuecomment-117555686.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by clonker** [comment]
It appears that this PR did not cause any further merge conflicts (so far) when merging dev_release_1.3 into devel.

**Comment by franknoe** [comment]
wait! merging dev_release_1.3 into devel is _not_ what we want to do as 
long we are in the refactoring stage. Please leave devel as it is and 
rebase dev_release_1.3 onto devel.

Am 01/07/15 um 11:20 schrieb Moritz Hoffmann:

> It appears that this PR did not cause any further merge conflicts (so 
> far) when merging dev_release_1.3 into devel.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/352#issuecomment-117558017.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Pull request merged**
