### PR TITLE
Update maximum_likelihood_hmsm.py

### PR DESCRIPTION
**Pull request by vargaslo**
format string to prevent error

### CODE REVIEW

**Comment by franknoe** [comment]
thank you.

**Comment by marscher** [comment]
This is exactly why all this string concatenation should be avoided and str.format should be used.

**Comment by franknoe** [comment]
I don't understand what you mean by that. Can you give an example?

Am 20/04/16 um 11:28 schrieb Martin K. Scherer:

> This is exactly why all this string concatenation should be avoided 
> and str.format should be used.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/777#issuecomment-212348709

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 20.04.2016 um 11:53 schrieb Frank Noe:

> I don't understand what you mean by that. Can you give an example?

float x = 42.42
my_str = "please format {whatever} to string for me".format(whatever=x)

Great source:
https://pyformat.info/

**Comment by franknoe** [comment]
That's very powerful, but I'm not sure we want to enforce using this 
approach everywhere.
For multiple strings lines and multiple values this approach looks more 
clumsy than the version `" print " + str(value1) + " and " + 
str(value2) ", too.".` in which everything is in sequence. Also the 
.format variant doesn't prevent exceptions from happening - for example 
the {} and the format args still have to match. So I don't see an 
immediate advantage if you're not actually using the extra features of 
this formatting approach.

Am 20/04/16 um 11:56 schrieb Martin K. Scherer:

> Am 20.04.2016 um 11:53 schrieb Frank Noe:
> 
> > I don't understand what you mean by that. Can you give an example?
> 
> float x = 42.42
> my_str = "please format {whatever} to string for me".format(whatever=x)
> 
> Great source:
> https://pyformat.info/
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/777#issuecomment-212357993

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Pull request merged**
