### PR TITLE
[doc/changelog] added some entries for 2.0.2

### LINKED ISSUE #596: missing changelog entries
Please have a look at the changes being made since 2.0.1 and add proper changelog entries (it is in doc/source/CHANGELOG.rst)

https://github.com/markovmodel/PyEMMA/compare/v2.0.1...devel

### PR DESCRIPTION
**Pull request by marscher**
**partially** fixes #596

### CODE REVIEW

**Comment by marscher** [comment]
Please add your changes to branch "changelog202"

**Comment by marscher** [comment]
@gph82 can you please summarize, what you have changed in the featurizer and the plotting package?

**Comment by franknoe** [comment]
Question for new releases: Are the ipython Tutorials on the pyemma.org 
page (devel) (1) re-run and re-generated or are they (2) just 
conversions of the output of the last saved ipynb file? I would prefer 
(1), because this would allow us to visually check these pages before 
the release and see if the algorithms still behave well, i.e. if the 
output makes sense. The ipython notebook tests currently only check if 
the notebooks execute without exception, but don't test for the validity 
of the results.

In this notebook:
     http://www.emma-project.org/vdevel/generated/MSM_BPTI.html
the version number shows as 2.0 rather than 2.0.1, which seems to 
suggest that we do (2) rather than (1).

Am 30/10/15 um 11:32 schrieb Martin K. Scherer:

> _partially_ fixes #596 https://github.com/markovmodel/PyEMMA/issues/596
> 
> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
> https://github.com/markovmodel/PyEMMA/pull/597
> 
> ```
>     Commit Summary
> ```
> - [doc/changelog] added some entries for 2.0.2
>   
>   ```
>   File Changes
>   ```
> - _M_ doc/source/CHANGELOG.rst
>   https://github.com/markovmodel/PyEMMA/pull/597/files#diff-0 (9)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/markovmodel/PyEMMA/pull/597.patch
> - https://github.com/markovmodel/PyEMMA/pull/597.diff
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/597.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
The notebooks are converted from the last state they were saved to have
control of the output. Of course we can change this policy to increase
"testing" coverage.

Since it is hard to test validity of notebook outcome (especially for
plots the (continuous) visual inspection prior releases will probably
catch some faults.

I think there is a Sphinx extension out there, which executes and
converts the notebooks during inclusion.

**Comment by franknoe** [comment]
OK. what about aiming for this in the next release and triggering the 
execution of all notebooks
manually in order to make this visual check up-to-date before the 
current release?

Am 30/10/15 um 14:27 schrieb Martin K. Scherer:

> The notebooks are converted from the last state they were saved to have
> control of the output. Of course we can change this policy to increase
> "testing" coverage.
> 
> Since it is hard to test validity of notebook outcome (especially for
> plots the (continuous) visual inspection prior releases will probably
> catch some faults.
> 
> I think there is a Sphinx extension out there, which executes and
> converts the notebooks during inclusion.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/597#issuecomment-152526206.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
yes, that is convenient. We also need to find a good way of how we provide the datasets needed by certain notebooks (eg. bpti trajs).

**Comment by franknoe** [comment]
We can't provide the bpti trajs. For the others, didn't we decide that 
we want to make the archive of all notebooks and the data downloadable? 
I thought that was already done.

Am 30/10/15 um 14:56 schrieb Martin K. Scherer:

> yes, that is convenient. We also need to find a good way of how we 
> provide the datasets needed by certain notebooks (eg. bpti trajs).
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/597#issuecomment-152532189.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I mean I need the data to run the notebooks somewhere, as for the latter you're right - it is already available online.

**Pull request merged**
