### PR TITLE
Datasource add skip parameter

### PR DESCRIPTION
**Pull request by marscher**
ping @jchodera: I guess this is what you like to have.

@clonker I'm struggling to pin down the failure of TestDCD.test_n_chunks. Funny enough it works for xtc, h5 etc... Would you be so kind to have a look? :)

### CODE REVIEW

**Comment by marscher** [comment]
```
======================================================================

FAIL: test_n_chunks (pyemma.coordinates.tests.test_coordinates_iterator.DCD)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/Users/travis/miniconda/envs/_test/lib/python2.7/site-packages/pyEMMA-2.2.2+65.ge9903fe-py2.7-macosx-10.6-x86_64.egg/pyemma/coordinates/tests/test_coordinates_iterator.py", line 83, in test_n_chunks

    self.assertEqual(chunks, it._n_chunks, "stride={s}, lag={t}".format(s=stride, t=lag))
E               AssertionError: 3 != 6 : stride=2, lag=0

```

However this only fails for DCD... The expectation, that we would get one chunk of size 30 and one of size 20 per trajectory does not hold. But how the heck can it hold for the other formats?! It uses exactly the same infrastructure.

**Comment by jchodera** [comment]
This is awesome, @marscher! Thanks so much!

@maxentile and @sonyahanson: We want to skip the initial portion of our Ensembler-seeded simulations to ensure the simulations have time to relax away from the initial highly-biased starting structures. This provides a very simple way to do that at the trajectory data source level simply by changing this

``` python
import pyemma.coordinates
from glob import glob
trajectory_filenames = glob(os.path.join(source_directory, 'run*-clone*.h5'))
coordinates_source = pyemma.coordinates.source(trajectory_filenames, features=featurizer)
```

to add the `skip` argument (e.g. dropping the first 40 frames [10 ns] from each trajectory):

``` python
import pyemma.coordinates
from glob import glob
trajectory_filenames = glob(os.path.join(source_directory, 'run*-clone*.h5'))
coordinates_source = pyemma.coordinates.source(trajectory_filenames, features=featurizer, skip=40)
```

**Comment by clonker** [comment]
Managed to track it down. The issue is how dcd treats `read_as_traj`: Apparently the argument `n_frames=chunksize` together with a stride argument already returns the correct trajectory, whereas for the other formats`n_frames=chunksize*stride` is necessary. Proposed fix on our side.

``` python
if self._extension not in _TOPOLOGY_EXTS:
    if self._extension in ('.dcd'):
        traj = self._f.read_as_traj(self._topology, n_frames=self._chunksize,
                                stride=self._stride, atom_indices=self._atom_indices, **self._kwargs)
    else:
        traj = self._f.read_as_traj(self._topology, n_frames=self._chunksize * self._stride,
                                    stride=self._stride, atom_indices=self._atom_indices, **self._kwargs)
else:
    traj = self._f.read_as_traj(n_frames=self._chunksize * self._stride,
                                stride=self._stride, atom_indices=self._atom_indices, **self._kwargs)
```

Also we catch the StopIteration exception in the FeatureReader and progress to the next file if the trajectory was too short (i.e., "too short" appears in the exception message). I believe we also have to do this for the "eof" one, otherwise another dcd test will fail. So:

``` python
if si.args and ("eof" in si.args[0] or "too short" in si.args[0]) and self._itraj < self._data_source.ntraj - 1:
    self._next_file()
    return ()
else:
    raise
```

Let me know what you think!

**Comment by marscher** [comment]
Thank you so much for looking into this! This all makes sense now!

**Comment by jchodera** [comment]
Hm. When I added `skip=40` to [this script](https://github.com/jchodera/MSMs/blob/master/jchodera/CK2/pyemma-equitemporal/cluster.py#L43), I now see this error:

```
[chodera@mskcc-ln1 pyemma-equitemporal]$ cat ~/pyemma-CK2-equitemporal-backbone.o7689349
Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
Wed Aug 17 12:15:35 EDT 2016
16
Wed Aug 17 12:15:35 EDT 2016
loading reference topology...
Initializing featurizer...
Featurizer has 2979 features.
Obtaining file info: 100% (585/585) [##############################] eta 00:00 /There are 1179914 frames total in 585 trajectories.
Clustering...
17-08-16 12:16:24 pyemma.coordinates.clustering.uniform_time.UniformTimeClustering[0] INFO     number of threads obtained from env variable 'OMP_NUM_THREADS'=16
Traceback (most recent call last):
  File "cluster.py", line 57, in <module>
    clustering = pyemma.coordinates.cluster_uniform_time(data=coordinates_source, k=nstates, stride=stride, metric=metric)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/pyemma/coordinates/api.py", line 1387, in cluster_uniform_time
    return _param_stage(data, res, stride=stride, chunk_size=chunk_size)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/pyemma/coordinates/api.py", line 843, in _param_stage
    this_stage.estimate(X=input_stage, stride=stride)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/pyemma/coordinates/transform/transformer.py", line 190, in estimate
    super(StreamingTransformer, self).estimate(X, **kwargs)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/pyemma/_base/estimator.py", line 356, in estimate
    self._model = self._estimate(X)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/pyemma/coordinates/clustering/uniform_time.py", line 87, in _estimate
    ra_stride = np.array([UniformTimeClustering._idx_to_traj_idx(x, cumsum) for x in linspace])
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/pyemma/coordinates/clustering/uniform_time.py", line 101, in _idx_to_traj_idx
    raise ValueError("Requested index %s was out of bounds [0,%s)" % (idx, cumsum[-1]))
ValueError: Requested index 1156730 was out of bounds [0,1156514)

real    0m49.324s
user    0m4.759s
sys 0m2.809s
Wed Aug 17 12:16:24 EDT 2016
```

None of the files have been touched for weeks, so the trajectories are not changing in length.

**Comment by jchodera** [comment]
I reproducibly get the same error:

```
[chodera@mskcc-ln1 pyemma-equitemporal]$ cat ~/pyemma-CK2-equitemporal-backbone.o7689378
Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
Wed Aug 17 13:26:20 EDT 2016
16
Wed Aug 17 13:26:20 EDT 2016
loading reference topology...
Initializing featurizer...
Featurizer has 2979 features.
Obtaining file info: 100% (585/585) [##############################] eta 00:01 /There are 1179914 frames total in 585 trajectories.
Clustering...
17-08-16 13:27:09 pyemma.coordinates.clustering.uniform_time.UniformTimeClustering[0] INFO     number of threads obtained from env variable 'OMP_NUM_THREADS'=16
Traceback (most recent call last):
  File "cluster.py", line 57, in <module>
    clustering = pyemma.coordinates.cluster_uniform_time(data=coordinates_source, k=nstates, stride=stride, metric=metric)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/pyemma/coordinates/api.py", line 1387, in cluster_uniform_time
    return _param_stage(data, res, stride=stride, chunk_size=chunk_size)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/pyemma/coordinates/api.py", line 843, in _param_stage
    this_stage.estimate(X=input_stage, stride=stride)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/pyemma/coordinates/transform/transformer.py", line 190, in estimate
    super(StreamingTransformer, self).estimate(X, **kwargs)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/pyemma/_base/estimator.py", line 356, in estimate
    self._model = self._estimate(X)
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/pyemma/coordinates/clustering/uniform_time.py", line 87, in _estimate
    ra_stride = np.array([UniformTimeClustering._idx_to_traj_idx(x, cumsum) for x in linspace])
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/pyemma/coordinates/clustering/uniform_time.py", line 101, in _idx_to_traj_idx
    raise ValueError("Requested index %s was out of bounds [0,%s)" % (idx, cumsum[-1]))
ValueError: Requested index 1156730 was out of bounds [0,1156514)

real    0m48.746s
user    0m4.748s
sys 0m2.825s
Wed Aug 17 13:27:09 EDT 2016
```

**Comment by marscher** [comment]
That is bad. The random access stuff is untested.

**Comment by marscher** [comment]
we are working on a solution.

**Comment by jchodera** [comment]
Thanks!

**Pull request merged**
