### PR TITLE
Allow to set nsamples for BMSM, BHMM and ITS

### PR DESCRIPTION
**Pull request by marscher**
please review @gph82

### CODE REVIEW

**Comment by marscher** [comment]
not sure what happened to the Appveyor tests, it seems like there is another run_test script on PATH which shadows the script we actually wanted to execute...

**Comment by marscher** [comment]
Since sampling in all three classes is a post-estimation thing, it still complies with the quoted sklearn patterns. Both MSM classes performed the sampling in the _estimate method, but for this step only "real" estimated quantities are used, so splitting the sampling from the actual estimation (code wise) increases both readability and functionality. Why would a convenience function avoid confusion or potential bugs (this function would have to "fiddle" around with internal estimator properties and people would expect such a functionality within the object)?

The PR is a bit messy, because I also fixed some other issues along the way.

Just a question about BHMM, why are there two discrete_hmm estimations? One by calling super()._estimate or use the hmm_init parameter and another for sampling input - I  could not spot a difference in the results produced.

**Comment by franknoe** [comment]
I don't understand. In the Bayesian classes, sampling is an integral part of the estimation, so estimation is not completed before sampling is.
As for this PR, maybe we can separate fixes needed anyway from this sampling issue, to make it more understandable. 


Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by marscher** [comment]
On 11.09.2017 19:52, Frank Noe wrote:
> 
>      
> I don't understand. In the Bayesian classes, sampling is an integral part of the estimation, so estimation is not completed before sampling is.
> As for this PR, maybe we can separate fixes needed anyway from this sampling issue, to make it more understandable.
I didn't say estimation is complete prior sampling. I'm just saying that 
there are two steps, generate a matrix to be sample and the sampling it 
self.

**Pull request closed without merging**
