### PR TITLE
Kmeans c extension

### PR DESCRIPTION
**Pull request by clonker**
New pull request of #280 in order to rebase onto dev_release_1.2.1.

### CODE REVIEW

**Comment by clonker** [comment]
kmeans_clustering.cluster is called in every add_data to avoid keeping the whole data in memory. Every time it is called a new batch of cluster centers is computed which then gets averaged after the last chunk was processed. So if C is a cluster center with data points x_1, ..., x_n, then one usually calculates
usual_kmeans
but here it is like
batch
where k is the chunk size and n the length of the trajectory.
However the obtained results are quite different from the sklearn mini-batch kmeans:

###### mini-batch:

screen shot 2015-04-30 at 12 45 27

###### c kmeans:

screen shot 2015-04-30 at 12 45 54

**Comment by franknoe** [comment]
First of all, please check if the assignment of figures is correct: The 
figure you show as "mini-batch" looks like full k-means whereas the 
figure you show as "c kmeans" looks like sklearn mini-batch kmeans 
output. Note also that the output of mini-batch kmeans very much depends 
on the batch size. Are you sure the figures are not the other way around?

Next, k-means and mini-batch k-means are completely different 
algorithms. We already had this issue because Martin had used sklearn's 
mini-batch k-means which led to outputs similar like the figure you have 
labeled "c kmeans" below. I have then replaced this by calling k-means, 
which required to first load all the data. Generally, if we are claiming 
to do k-means we should actually do k-means and not a different 
algorithm. I think sklearn might just assign clusters based on the first 
batch of the data and not do any averaging.

I'm not sure if what you describe as your algorithm below is equivalent 
to k-means or not, but I have the impression it is not the same. If they 
are not the same, we shouldn't use it, because again we are claiming to 
do k-means, so we have to do it.

In terms of loading: I am not sure if there is a more clever way of 
doing it, but it seems to me that for k-means you either have to load 
all data into memory and then can quickly do the k-means iterations 
(fast but high memory reqs), or you have to stream over the data for 
every iteration (slow but low memory reqs). If this is the case, we 
should try to load the data and then do it in memory and if not 
possible, fall back to the streaming option and print a warning that 
this is going the be slow and the user should better use a stride. Using 
a stride is always better than doing things in batches.

Am 30/04/15 um 12:52 schrieb Moritz Hoffmann:

> kmeans_clustering.cluster is called in every add_data to avoid keeping 
> the whole data in memory. Every time it is called a new batch of 
> cluster centers is computed which then gets averaged after the last 
> chunk was processed. So if C is a cluster center with data points x_1, 
> ..., x_n, then one usually calculates
> usual_kmeans 
> https://cloud.githubusercontent.com/assets/1685266/7411000/25ce8400-ef34-11e4-91e4-cb673bbc29e6.png
> but here it is like
> batch 
> https://cloud.githubusercontent.com/assets/1685266/7411301/19e70f38-ef37-11e4-84b9-7b5ca5e3d291.png
> where k is the chunk size and n the length of the trajectory.
> However the obtained results are quite different from the sklearn 
> mini-batch kmeans:
> 
> ```
>         mini-batch:
> ```
> 
> screen shot 2015-04-30 at 12 45 27 
> https://cloud.githubusercontent.com/assets/1685266/7411332/641ee8b4-ef37-11e4-8dad-50b2dd8fc7d6.png
> 
> ```
>         c kmeans:
> ```
> 
> screen shot 2015-04-30 at 12 45 54 
> https://cloud.githubusercontent.com/assets/1685266/7411335/6d6ed564-ef37-11e4-8be3-53ba48c9d35b.png
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/281#issuecomment-97736919.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
maybe this should help: http://papers.nips.cc/paper/3812-streaming-k-means-approximation.pdf

**Comment by franknoe** [comment]
We can look into other solutions. For now I would vote to do the data 
accumulation and then run k-means in memory. I think this should cover 
most reasonable situations. If you have too much data to fit into memory 
to do k-means at the time of clustering, you are probably using a too 
high-dimensional space to get anything reasonable out.

Am 04/05/15 um 17:54 schrieb Martin K. Scherer:

> maybe this should help: 
> http://papers.nips.cc/paper/3812-streaming-k-means-approximation.pdf
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/281#issuecomment-98764242.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I think this is in a mergeable state now. @fabian-paul can you also confirm please?

**Comment by franknoe** [comment]
Wait. @clonker can you comment how you did it in the end? We talked about doing the initialization of the centers like in sklearn, I'd like to understand how it works.
Also, can you demonstrate on the BPTI data above that we now get similar results like the sklearn k-means?

Thanks

**Comment by marscher** [comment]
The results are even better converged after less iterations and it is 10
times faster than sklearn kmeans according to clonkers benchmarks.

Of course I will wait with the merge until it is signed off.

**Comment by franknoe** [comment]
Sounds good. I'd like to understand the details of the initialization 
though, especially the computational complexity of the initialization step.

Am 11/05/15 um 15:51 schrieb Martin K. Scherer:

> The results are even better converged after less iterations and it is 10
> times faster than sklearn kmeans according to clonkers benchmarks.
> 
> Of course I will wait with the merge until it is signed off.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/281#issuecomment-100915324.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by clonker** [comment]
The initialisation is based on [this](http://ilpubs.stanford.edu:8090/778/1/2006-13.pdf) paper. The idea is to choose the initial cluster centers subsequently such that each chosen cluster center is not near any of the previously chosen ones. Therefore the (usually used) uniform distribution is replaced by a weighted distribution that uses the squared distances to the set of centers. In particular the initialisation algorithm is as follows:
1. Take one center chosen uniformly at random from the data set.
2. Take a new center chosen at random with the probability 
   distribution
   where D(x) is the shortest distance from a data point to the already assigned centers
3. If not all cluster centers have been assigned, repeat step 2.

I have compared the runtime of the kmeans++ c-extension with the sklearn-kmeans++ module and the c-extension gives indeed a speedup of factor ~10. Kmeans itself is trying to minimise the following expression:

kmeans
where S_i are the data points assigned to the i-th cluster center. Evaluating this sum I got approximately the same values for the sklearn-kmeans and this implementation. Some pictures:

##### sklearn with kmeans++

screenshot 2015-05-12 13 02 35

##### c-extension with kmeans++

screenshot 2015-05-12 13 04 01

##### sklearn with uniform distribution initialisation

screenshot 2015-05-12 13 09 46

##### c-extension with uniform distribution initialisation

screenshot 2015-05-12 13 04 57

In both the c-extension and the implementation provided by sklearn, there is a slight modification of the algorithm. Instead of choosing just one point in the second step, there are "2+ln(k)" points chosen of which the best one (in terms of its potential) then makes it into the centers list.
To initialize all centers the computational complexity for this implementation is something along the lines of
complexity
where n is the number of data points and k is the k of k-means.
Note however that only very few iterations are needed to get a good result: If executing kmeans++, the above mentioned expression to be minimised takes for the bpti data set on 10 iterations the value of about 6700. If initialised uniformly distributed the value averages about 7100 at 10 iterations and at around 40 iterations the value sometimes still is above 7000, sometimes is in the range of 6550 - 6700.

**Comment by franknoe** [comment]
Thank you. Excellent work Moritz! Please save this description, it 
should go either to the pyEMMA docs or to MSMdocs (we can discuss how to 
arrange docs next week).
If Fab agrees we can merge.

Am 12/05/15 um 13:35 schrieb Moritz Hoffmann:

> The initialisation is based on this 
> http://ilpubs.stanford.edu:8090/778/1/2006-13.pdf paper. The idea is 
> to choose the initial cluster centers subsequently such that each 
> chosen cluster center is not near any of the previously chosen ones. 
> Therefore the (usually used) uniform distribution is replaced by a 
> weighted distribution that uses the squared distances to the set of 
> centers. In particular the initialisation algorithm is as follows:
> 1. Take one center chosen uniformly at random from the data set.
> 2. Take a new center chosen at random with the probability
>    distribution
>    https://cloud.githubusercontent.com/assets/1685266/7585697/b35b9cd4-f8a5-11e4-815e-a7410b5f3146.png
>    where D(x) is the shortest distance from a data point to the
>    already assigned centers
> 3. If not all cluster centers have been assigned, repeat step 2.
> 
> I have compared the runtime of the kmeans++ c-extension with the 
> sklearn-kmeans++ module and the c-extension gives indeed a speedup of 
> factor ~10. Kmeans itself is trying to minimise the following expression:
> 
> kmeans 
> https://cloud.githubusercontent.com/assets/1685266/7585822/9afde2ea-f8a6-11e4-88fe-fe7602ce7b09.png
> where S_i are the data points assigned to the i-th cluster center. 
> Evaluating this sum I got approximately the same values for the 
> sklearn-kmeans and this implementation. Some pictures:
> 
> ```
>       sklearn with kmeans++
> ```
> 
> screenshot 2015-05-12 13 02 35 
> https://cloud.githubusercontent.com/assets/1685266/7585885/3aa9e5e6-f8a7-11e4-9f1b-d3aad66d16bc.png
> 
> ```
>       c-extension with kmeans++
> ```
> 
> screenshot 2015-05-12 13 04 01 
> https://cloud.githubusercontent.com/assets/1685266/7585897/6060af68-f8a7-11e4-8ae2-01f0b7bd475a.png
> 
> ```
>       sklearn with uniform distribution initialisation
> ```
> 
> screenshot 2015-05-12 13 09 46 
> https://cloud.githubusercontent.com/assets/1685266/7585970/2f101092-f8a8-11e4-8757-2e817d21d83d.png
> 
> ```
>       c-extension with uniform distribution initialisation
> ```
> 
> screenshot 2015-05-12 13 04 57 
> https://cloud.githubusercontent.com/assets/1685266/7585916/84233560-f8a7-11e4-9c0f-60686561b532.png
> 
> In both the c-extension and the implementation provided by sklearn, 
> there is a slight modification of the algorithm. Instead of choosing 
> just one point in the second step, there are "2+ln(k)" points chosen 
> of which the best one (in terms of its potential) then makes it into 
> the centers list.
> To initialize all centers the computational complexity for this 
> implementation is something along the lines of
> complexity 
> https://cloud.githubusercontent.com/assets/1685266/7586112/bc05fd9e-f8a9-11e4-968b-d04a2c601453.png
> where n is the number of data points and k is the k of k-means.
> Note however that only very few iterations are needed to get a good 
> result: If executing kmeans++, the above mentioned expression to be 
> minimised takes for the bpti data set on 10 iterations the value of 
> about 6700. If initialised uniformly distributed the value averages 
> about 7100 at 10 iterations and at around 40 iterations the value 
> sometimes still is above 7000, sometimes is in the range of 6550 - 6700.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/281#issuecomment-101246604.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by clonker** [comment]
@fabian-paul confirm?

**Comment by fabian-paul** [comment]
I have tested Moritz' implementation on a data set of peptide TICs and compared it with sklearn's. Here are some plots. The title contains the value of the objective function that is minimized in k-means.
image
image
The results look similar and the objective function too.

**Comment by fabian-paul** [comment]
Here are some result with 4-D data:
image
image

**Pull request merged**
