### PR TITLE
fixes the random failing of minRMSD tests

### PR DESCRIPTION
**Pull request by gph82**
See discussion in #355 for details

### CODE REVIEW

**Comment by gph82** [comment]
What's with "FAIL: test_cov_tau (pyemma.coordinates.tests.test_tica.TestTICAExtensive)"? Didn't we fix this alredy?

**Comment by franknoe** [comment]
Yes, I did in the kinetic_map PR

Am 16/06/15 um 15:43 schrieb Guillermo Pérez-Hernández:

> What's with "FAIL: test_cov_tau 
> (pyemma.coordinates.tests.test_tica.TestTICAExtensive)"? Didn't we fix 
> this alredy?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/362#issuecomment-112434361.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
I might be wrong, but isn't that PR already taken into account in my devel branch?
https://github.com/gph82/PyEMMA/commits/devel

**Comment by franknoe** [comment]
Yes, in this commit:

https://github.com/gph82/PyEMMA/commit/0ab3280c262786d16ac78b9a8b0a66c64b3fe6de

l. 178 in pyemma/coordinates/tests/test_tica.py
is the relevant change. Does the test failure stil occur?

Am 16/06/15 um 16:00 schrieb Guillermo Pérez-Hernández:

> I might be wrong, but isn't that PR already taken into account in my 
> devel branch?
> https://github.com/gph82/PyEMMA/commits/devel
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/362#issuecomment-112443149.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
yeah, that's what appveyor is saying

**Comment by franknoe** [comment]
I see you mean this:

```
======================================================================
FAIL: test_cov (pyemma.coordinates.tests.test_tica.TestTICAExtensive)
----------------------------------------------------------------------
Traceback (most recent call last):
File "C:\projects\pyemma\pyemma\coordinates\tests\test_tica.py", line 
174, in test_cov
assert (np.max(self.tica_obj.cov - cov_ref) < 3e-2)
AssertionError
======================================================================
FAIL: test_cov_tau (pyemma.coordinates.tests.test_tica.TestTICAExtensive)
----------------------------------------------------------------------
Traceback (most recent call last):
File "C:\projects\pyemma\pyemma\coordinates\tests\test_tica.py", line 
180, in test_cov_tau
assert (np.max(self.tica_obj.cov_tau - cov_tau_ref) < 3e-2)
AssertionError
----------------------------------------------------------------------
```

This is then indeed a stochastic problem I would guess. We can set

cls.T=40000

in line 132 and additionally increase the threshold to 0.05 in lines 174 
and 180. Can you do this in your PR and retry? I don't wanna open a PR 
for this.

Thanks
Frank.

Am 16/06/15 um 16:00 schrieb Guillermo Pérez-Hernández:

> I might be wrong, but isn't that PR already taken into account in my 
> devel branch?
> https://github.com/gph82/PyEMMA/commits/devel
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/362#issuecomment-112443149.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
done. Let's see

**Pull request merged**
