### PR TITLE
Kinetic map

### PR DESCRIPTION
**Pull request by franknoe**
- kinetic map transformation for TICA
- variance-based cutoff for PCA and TICA
- changed default parameters for PCA and TICA
- fixed failing TICA test function test_cov_tau

### CODE REVIEW

**Comment by franknoe** [comment]
minRMSD test in test_featurizer fails. @gph82 please check.

**Comment by gph82** [comment]
There's two random factors at the minRMSD test: 
reference frame (for all three tests)
reference indices (for two tests)

My observation so far is that sometimes (= only for _some_ reference frames) there is an absolute error ca. 1e-4 for low minRMSD values (<1e-1). Where this comes from, I don't know. To keep the test from failing, one could safely relax the atol in the np.allclose call to sth like 1e-3 or play around with the rtol value...not sure what do to next. 

In the meantime, this commit will produce more telling assertion error message whenever this happens again: e541a30421e0a248288c017f558570cc57fcedb7 

I will wait for a PR until i completely figure this out.

**Comment by franknoe** [comment]
I usally do

``` python
assert np.max(np.abs(A-B)) < mytol
```

for these "rough" tests. In my understanding np.allclose is to test 
equality within numerical precision and not to within statistical error.

Am 15/06/15 um 15:44 schrieb Guillermo Pérez-Hernández:

> There's two random factors at the minRMSD test:
> reference frame (for all three tests)
> reference indices (for two tests)
> 
> My observation so far is that sometimes (= only for /some/ reference 
> frames) there is an absolute error ca. 1e-4 for low minRMSD values 
> (<1e-1). Where this comes from, I don't know. To keep the test from 
> failing, one could safely relax the atol in the np.allclose call to 
> sth like 1e-3 or play around with the rtol value...not sure what do to 
> next.
> 
> In the meantime, this commit will produce more telling assertion error 
> message whenever this happens again: e541a30 
> https://github.com/markovmodel/PyEMMA/commit/e541a30421e0a248288c017f558570cc57fcedb7 
> 
> I will wait for a PR until i completely figure this out.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/355#issuecomment-112076032.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
that is essentially what would happen if we use rtol = 0 in the np.allclose call
(from http://docs.scipy.org/doc/numpy/reference/generated/numpy.allclose.html
"If the following equation is element-wise True, then allclose returns True.
 absolute(a - b) <= (atol + rtol \* absolute(b)) ")

But that does not really address what value of mytol (or ato) we're comfortable with. mdtraj has units of nm (i think), so we can go safely with atol 1e-3 , i would say

**Comment by franknoe** [comment]
Am 15/06/15 um 16:04 schrieb Guillermo Pérez-Hernández:

> that is essentially what would happen if we use rtol = 0 in the 
> np.allclose call
> (from 
> http://docs.scipy.org/doc/numpy/reference/generated/numpy.allclose.html
> "If the following equation is element-wise True, then allclose returns 
> True.
> absolute(a - b) <= (atol + rtol \* absolute(b)) ")
> 
> Yes, you can do that with np.allclose. My argument is that it is 
> confusing to use np.allclose when you have statistical error, because in 
> such a case we do not expect "almost equal" at all. On the other hand I 
> don't understand what the source of your error/randomness is.
> 
> But that does not really address what value of mytol (or ato) we're 
> comfortable with. mdtraj has units of nm (i think), so we can go 
> safely with atol 1e-3 , i would say
> 
> The units depend on the file type. In xtc's it's nm.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/355#issuecomment-112081319.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
On 15.06.2015 17:13, Frank Noe wrote:

> Am 15/06/15 um 16:04 schrieb Guillermo Pérez-Hernández:
> 
> > that is essentially what would happen if we use rtol = 0 in the
> > np.allclose call
> > (from
> > http://docs.scipy.org/doc/numpy/reference/generated/numpy.allclose.html
> > "If the following equation is element-wise True, then allclose returns
> > True.
> > absolute(a - b) <= (atol + rtol \* absolute(b)) ")
> > 
> > Yes, you can do that with np.allclose. My argument is that it is
> > confusing to use np.allclose when you have statistical error, 
> > why do I have statistical error?
> > because in
> > such a case we do not expect "almost equal" at all. On the other hand I
> > don't understand what the source of your error/randomness is.
> > me neither
> > 
> > But that does not really address what value of mytol (or ato) we're
> > comfortable with. mdtraj has units of nm (i think), so we can go
> > safely with atol 1e-3 , i would say
> > 
> > The units depend on the file type. In xtc's it's nm.
> > I think except for format-specific writing, mdtraj uses always uses
> > nanometers internally and displays things related to length in
> > nanometers (regardless of the file format etc)

http://mdtraj.org/latest/examples/introduction.html?highlight=nanometer
"All of the distances in the Trajectory are stored in nanometers"

> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/markovmodel/PyEMMA/pull/355#issuecomment-112081319.
> 
> ## 
> 
> ---
> 
> Prof. Dr. Frank Noe
> Head of Computational Molecular Biology group
> Freie Universitaet Berlin
> 
> Phone: (+49) (0)30 838 75354
> Web: research.franknoe.de
> 
> ## Mail: Arnimallee 6, 14195 Berlin, Germany
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/pull/355#issuecomment-112101766.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

## http://userpage.fu-berlin.de/gph82/

**Comment by franknoe** [comment]
If you don't have statistical error, then my comment is irrelevant. So 
why is there randomness in the test?

Am 15/06/15 um 17:24 schrieb Guillermo Pérez-Hernández:

> On 15.06.2015 17:13, Frank Noe wrote:
> 
> > Am 15/06/15 um 16:04 schrieb Guillermo Pérez-Hernández:
> > 
> > > that is essentially what would happen if we use rtol = 0 in the
> > > np.allclose call
> > > (from
> > > http://docs.scipy.org/doc/numpy/reference/generated/numpy.allclose.html
> > > "If the following equation is element-wise True, then allclose returns
> > > True.
> > > absolute(a - b) <= (atol + rtol \* absolute(b)) ")
> > > 
> > > Yes, you can do that with np.allclose. My argument is that it is
> > > confusing to use np.allclose when you have statistical error,
> > > why do I have statistical error?
> > > because in
> > > such a case we do not expect "almost equal" at all. On the other hand I
> > > don't understand what the source of your error/randomness is.
> > > me neither
> > > 
> > > But that does not really address what value of mytol (or ato) we're
> > > comfortable with. mdtraj has units of nm (i think), so we can go
> > > safely with atol 1e-3 , i would say
> > > 
> > > The units depend on the file type. In xtc's it's nm.
> > > I think except for format-specific writing, mdtraj uses always uses
> > > nanometers internally and displays things related to length in
> > > nanometers (regardless of the file format etc)
> 
> http://mdtraj.org/latest/examples/introduction.html?highlight=nanometer
> "All of the distances in the Trajectory are stored in nanometers"
> 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> > > https://github.com/markovmodel/PyEMMA/pull/355#issuecomment-112081319.
> > 
> > ## 
> > 
> > ---
> > 
> > Prof. Dr. Frank Noe
> > Head of Computational Molecular Biology group
> > Freie Universitaet Berlin
> > 
> > Phone: (+49) (0)30 838 75354
> > Web: research.franknoe.de
> > 
> > ## Mail: Arnimallee 6, 14195 Berlin, Germany
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/markovmodel/PyEMMA/pull/355#issuecomment-112101766.
> 
> ## 
> 
> Dr. Guillermo Pérez-Hernández
> Freie Universität Berlin
> Institute for Mathematics
> Arnimallee 6
> D-14195 Berlin
> tel 0049 30 838 75776
> 
> ## http://userpage.fu-berlin.de/gph82/
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/355#issuecomment-112106916.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
there is randomness in that 
1) The reference frame is chosen at random for the test (not always computing the miRMSD of the the traj wrt to frame 0, but wrt to frame = XXX), but this randomness is not a problem
2) for a given frame used as reference (e.g. frame 37), some traj frames will have absolute errors greater than atol (1e-5), but small compared to the value of the minRMSD itself:

```
AssertionError: Largest discrepancy between reference (ref_frame 37) and test: -5.13e-04, for the pair 0.000000, 0.000513 at frame 37
```

**Comment by franknoe** [comment]
I don't understand 2 because I don't know what the test is doing, but 
anyway can't we avoid random choices for these tests and just pick 
particular references for which we know the expected answer? Tests 
should be reliable. The only point where we need randomness in the test 
is when we test statistical algorithms, such as error estimation.

Am 15/06/15 um 17:34 schrieb Guillermo Pérez-Hernández:

> there is randomness in that
> 1) The reference frame is chosen at random for the test (not always 
> computing the miRMSD of the the traj wrt to frame 0, but wrt to frame 
> = XXX), but this randomness is not a problem
> 2) for a given frame used as reference (e.g. frame 37), some traj 
> frames will have absolute errors greater than atol (1e-5), but small 
> compared to the value of the minRMSD itself:
> 
> |AssertionError: Largest discrepancy between reference (ref_frame 37) and test: -5.13e-04, for the pair 0.000000, 0.000513 at frame 37
> |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/355#issuecomment-112111765.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
Okay, i'll do it that way and PR. Thanks!

**Pull request merged**
