### PR TITLE
added sparsifier

### LINKED ISSUE #559: Add sparsifyer
@gph82 or @marscher can you pls make a PR with your sparsifyer (contact - TICA preprocessor)?

### PR DESCRIPTION
**Pull request by marscher**
closes #559

### CODE REVIEW

**Comment by franknoe** [comment]
Thank you , I'll review this.

Am 28/09/15 um 16:26 schrieb Martin K. Scherer:

> closes #559 https://github.com/markovmodel/PyEMMA/issues/559
> 
> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
> https://github.com/markovmodel/PyEMMA/pull/569
> 
> ```
>     Commit Summary
> ```
> - added sparsifier
>   
>   ```
>   File Changes
>   ```
> - _A_ pyemma/coordinates/data/sparsifier.py
>   https://github.com/markovmodel/PyEMMA/pull/569/files#diff-0 (62)
> - _A_ pyemma/coordinates/tests/test_sparsifier.py
>   https://github.com/markovmodel/PyEMMA/pull/569/files#diff-1 (50)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/markovmodel/PyEMMA/pull/569.patch
> - https://github.com/markovmodel/PyEMMA/pull/569.diff
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/569.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
The sparsifier looks good on first sight, but has it been tested using TICA and contacts with real data?

However, now we are still missing the infrastructure, i.e. the sparsifyer needs to be used in a practical way. I guess when using TICA with contacts we'd always like to use it, but we need to somehow map the results back to a full feature set. 

Any suggestions how to make the sparsification available to users (API-level) in general?

**Comment by marscher** [comment]
To integrate the sparsifier, the suggestion is the following:
1. manual creation and pipeline insertion
2. semi-automatic insertion, if potentially sparse features have been selected.

The second point is way more complicated and involves that the Featurizer can be queried for potential sparse features (and maybe their column indices). The coor.source|load functions could take a sparsify=True|False|'auto' parameter to control this behaviour.

I'm currently testing the sparsifier on real data in combination with TICA.

**Comment by franknoe** [comment]
I think for TICA with contacts one should get sparsification by default, 
as this is an important application. Each feature can get a sparse flag 
(default False, currently only contacts are True). Perhaps we can couple 
the first pass with calculation of the mean, such that TICA doesn't 
waste a pass through the data.

Am 06/10/15 um 11:00 schrieb Martin K. Scherer:

> To integrate the sparsifier, the suggestion is the following:
> 1. manual creation and pipeline insertion
> 2. semi-automatic insertion, if potentially sparse features have been
>    selected.
> 
> The second point is way more complicated and involves that the 
> Featurizer can be queried for potential sparse features (and maybe 
> their column indices). The coor.source|load functions could take a 
> sparsify=True|False|'auto' parameter to control this behaviour.
> 
> I'm currently testing the sparsifier on real data in combination with 
> TICA.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/569#issuecomment-145790760.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 06.10.2015 um 13:59 schrieb Frank Noe:

> I think for TICA with contacts one should get sparsification by default,
> as this is an important application. Each feature can get a sparse flag
> (default False, currently only contacts are True). Perhaps we can couple
> the first pass with calculation of the mean, such that TICA doesn't
> waste a pass through the data.

To save a pass is a very nice idea. I will look into that.

**Pull request merged**
