### PR TITLE
Use networkx for automatic layout in plots/networks

### LINKED ISSUE #354: test_networks.TestNetworkPlot plots
The test

test_networks.TestNetworkPlot

actually plots a figure during the test run. I'm sure that's not desired.

### PR DESCRIPTION
**Pull request by marscher**
1. Grandalf is untested and of bad code quality; it implements its algorithms in pure Python
2. Networkx is well established; uses Numpy for algorithms.
3. Now the code looks much simpler.
4. Testing coverage will increase
5. Fix #354

### CODE REVIEW

**Comment by franknoe** [comment]
Nice, thanks!!!
Can you show some results?

**Comment by marscher** [comment]
figure_1

**Comment by franknoe** [comment]
something went wrong with the state order. The source state (0) must 
have committor 0 and the sink state (2) must have committor 1.

Am 19/06/15 um 22:53 schrieb Martin K. Scherer:

> figure_1 
> https://cloud.githubusercontent.com/assets/170287/8262849/fe0ca770-16d5-11e5-8f13-fcac90460e5a.png
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/371#issuecomment-113641921.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Ah, and the figure rescaling to make it approximately square can now 
maybe be switched back on. I think we had switched that off because of a 
grandalf issue.

Am 19/06/15 um 22:53 schrieb Martin K. Scherer:

> figure_1 
> https://cloud.githubusercontent.com/assets/170287/8262849/fe0ca770-16d5-11e5-8f13-fcac90460e5a.png
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/371#issuecomment-113641921.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
okay, will check this on Monday. Have a nice weekend!

**Comment by franknoe** [comment]
likewise!

Am 19/06/15 um 23:00 schrieb Martin K. Scherer:

> okay, will check this on Monday. Have a nice weekend!
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/371#issuecomment-113642997.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I was able to extract the spring_layout method from networkx, so we do not have a new dependency right now.

**Comment by franknoe** [comment]
Great! We can keep playing with networkx, perhaps we would like to use 
more of it's functionalities, but for now that's good.

Am 23/06/15 um 16:57 schrieb Martin K. Scherer:

> I was able to extract the spring_layout method from networkx, so we do 
> not have a new dependency right now.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/371#issuecomment-114534263.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
figure_1
From the test case the flux is being computed from state 0 to state 4, so the scale should be also fine right now.

**Comment by marscher** [comment]
I've also changed the number format, since it was not informative before (fluxes are usally very small right?)

**Comment by marscher** [comment]
plot_markov_model for the same toy system
figure_2

**Comment by franknoe** [comment]
looks great, thanks!

Am 23/06/15 um 17:22 schrieb Martin K. Scherer:

> plot_markov_model for the same toy system
> figure_2 
> https://cloud.githubusercontent.com/assets/170287/8309739/54b5ed36-19cc-11e5-9d9e-9d53f207d772.png
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/371#issuecomment-114543096.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Pull request merged**
