### PR TITLE
[Impliedtimescales] use joblib for parallel model estimation.

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by marscher** [comment]
Actually I'm not sure how to handle fail_fast parameter if there are multiple jobs.

**Comment by marscher** [comment]
the failing test is unrelated to this change: TypeError: bayesian_hmm() got an unexpected keyword argument 'transition_matrix_prior'

**Comment by franknoe** [comment]
I'll take care of it

Am 07/07/15 um 16:12 schrieb Martin K. Scherer:

> the failing test is unrelated to this change: TypeError: 
> bayesian_hmm() got an unexpected keyword argument 
> 'transition_matrix_prior'
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/395#issuecomment-119216657.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Ah! The problem is that I am using a recently implemented feature in 
bhmm. This is in the bhmm master branch but not in a release.
So the problem doesn't occur for me locally, but it does occur on the 
test server which tries to use the latest bhmm release.

Is it simple to make a new bhmm release (patch), or should we rather 
wait until we have something significant?

Am 07/07/15 um 16:12 schrieb Martin K. Scherer:

> the failing test is unrelated to this change: TypeError: 
> bayesian_hmm() got an unexpected keyword argument 
> 'transition_matrix_prior'
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/395#issuecomment-119216657.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I'll rebase it on dev_release_1.3 once the model refactor branch is merged.

**Comment by franknoe** [comment]
I just lost a big commit message because vi died on me... hold on

Am 09/07/15 um 17:04 schrieb Martin K. Scherer:

> I'll rebase it on dev_release_1.3 once the model refactor branch is 
> merged.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/395#issuecomment-120018229.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
OK done. Go ahead.

Am 09/07/15 um 17:04 schrieb Martin K. Scherer:

> I'll rebase it on dev_release_1.3 once the model refactor branch is 
> merged.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/395#issuecomment-120018229.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Ahm .. I did merge into dev_release_1.3, so I pushed to dev_release_1.3. 
Was that wrong?

Am 09/07/15 um 17:04 schrieb Martin K. Scherer:

> I'll rebase it on dev_release_1.3 once the model refactor branch is 
> merged.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/395#issuecomment-120018229.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Thank you so much!

**Comment by marscher** [comment]
no that was perfectly fine.

**Comment by marscher** [comment]
have to reopen to change base....

**Pull request closed without merging**
