### PR TITLE
[MLMSM] use pi from msmtools tmatrix estimation

### PR DESCRIPTION
**Pull request by marscher**
For reversible estimates we get pi directly from msmtools.estimation.tmatrix. So we use it for the cases where it applies. The tests were checking eigenvalues within a numerical tolerance of 1e-12, so we set max_err accordingly.

Done with the aid of @fabian-paul

### CODE REVIEW

**Comment by marscher** [comment]
@franknoe, @fabian-paul would it hurt anybody, if we increase the default max_err value to 1e-12?

**Comment by marscher** [comment]
https://travis-ci.org/markovmodel/PyEMMA/jobs/274658288 shows TPT pathway decomposition fails, because of using pi from the iteration formula instead of the eigendecomposition...

**Comment by marscher** [comment]
Since we have repaired sparse/dense estimation previously, the reactive flux decomposition now works as well. I guess there were some kind of inconsistencies if we estimated dense and then use sparse routines to decompose.

**Comment by marscher** [comment]
The estimation method returns an invalid pi for a symmetric estimate. Eg. even the stationary relation is violated (P.mu != mu).

If I add the following to the MLMSM._estimate method, the first numpy testing assertion already fails. I think this is something serious.
``` python
        # msmtools returns a tuple for statdist_active = None.
        if isinstance(P, tuple):
            P, statdist_active = P
            _np.testing.assert_allclose(P.dot(statdist_active), statdist_active)
            if self.reversible:
                _np.testing.assert_allclose(statdist_active.dot(P), P.T.dot(statdist_active))
```

yields:
```
>           _np.testing.assert_allclose(P.dot(statdist_active), statdist_active, atol=atol)
E           AssertionError: 
E           Not equal to tolerance rtol=1e-07, atol=1e-12
E           
E           (mismatch 100.0%)
E            x: array([ 0.250438,  0.249998,  0.250557,  0.250871])
E            y: array([ 0.239957,  0.266248,  0.252854,  0.24094 ])
```
However the estimation routine returned no error code and reported convergence.

**Comment by marscher** [comment]
Either we fix this issue in msmtools or we rely on diagonalizing the transition matrix for computing the stationary measure. What do you think?

**Comment by franknoe** [comment]
Huh, why does this happen now? Shouldn't the test have failed before the 2.5 release. 
We should go back to the last version that worked and retrace it from there. Or does this only happen with new numpy?


Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by marscher** [comment]
I computed the stationary measure wrong, sorry for spreading fake news!

**Comment by marscher** [comment]
This PR depends on markovmodel/msmtools#107

**Pull request merged**
