### PR TITLE
[cluster_regspace] produce ONLY ONE max_centers warning

### PR DESCRIPTION
**Pull request by gph82**
Trying to reduce the verbosity level which kill the notebooks when having thousands of trajectories.

### CODE REVIEW

**Comment by marscher** [comment]
didn't we agreed upon saving the indices of skipped trajectories in a list and log this once, the parameterization is finished?

**Comment by gph82** [comment]
@marscher  I think you are talking about #379 ?

**Comment by marscher** [comment]
You're right, sorry. But actually this warning should appear only one, because it should stop executing the loop producing this warning.

**Comment by gph82** [comment]
as a matter of fact, it does not (which I was wondering why in the first place).

 Perhaps, you can take a look at it?

**Comment by marscher** [comment]
will do. Thank you

**Pull request closed without merging**
