### PR TITLE
Trick to make long work on Python 3

### PR DESCRIPTION
**Pull request by Upabjojr**

### CODE REVIEW

**Comment by franknoe** [comment]
Thanks! But is long actually needed for any platform? In other words, is 
there any situation in which we need to check for int?

@marscher: If such a fix is needed, should it be included in six?

Am 24/02/16 um 13:39 schrieb Francesco Bonazzi:

> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
> https://github.com/markovmodel/PyEMMA/pull/706
> 
> ```
>     Commit Summary
> ```
> - trick to make plots work on Python 3
>   
>   ```
>   File Changes
>   ```
> - _M_ pyemma/thermo/util/util.py
>   https://github.com/markovmodel/PyEMMA/pull/706/files#diff-0 (4)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/markovmodel/PyEMMA/pull/706.patch
> - https://github.com/markovmodel/PyEMMA/pull/706.diff
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/706.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I'd prefer using pyemma.util.types.is_int(x) for this purpose. This should be Python major version agnostic.

**Comment by marscher** [comment]
Anyway the code which caused that problem is untested on devel, so we would not even see if it does not succeed. The solution of @Upabjojr is pretty straight-forward and should work.

**Comment by franknoe** [comment]
I agree: the right approach is to use ``pyemma.util.types` for the purpose of type-checking (it may be necessary to extend it to deal with this situation), and additionally make sure this code is properly tested.

**Comment by marscher** [comment]
In [4]: isinstance(long(1), numbers.Integral)
Out[4]: True

on Python 2

**Comment by franknoe** [comment]
perfect, then it's covered by types.

Am 24/02/16 um 13:56 schrieb Martin K. Scherer:

> In [4]: isinstance(long(1), numbers.Integral)
> Out[4]: True
> 
> on Python 2
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/706#issuecomment-188245892.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
We can quick fix this and release RC3 within 20-30 min.

**Comment by franknoe** [comment]
OK. Did you find a more convenient way to release RC's?

Am 24/02/16 um 13:58 schrieb Martin K. Scherer:

> We can quick fix this and release RC3 within 20-30 min.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/706#issuecomment-188246573.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
https://github.com/omnia-md/conda-recipes/issues/445

**Comment by marscher** [comment]
@Upabjojr can you please change your PR to use pyemma.util.types.is_int?

**Comment by marscher** [comment]
``` python
from pyemma.util import types
....
# line 66
elif types.is_int(candidate) or types.is_float(candidate):
```

**Comment by Upabjojr** [comment]
Done.

**Comment by marscher** [comment]
Thank you!

**Comment by marscher** [comment]
RC3 on PyPI
cc @franknoe

**Pull request merged**
