### PR TITLE
Feature runtime estimate

### PR DESCRIPTION
**Pull request by marscher**
requested by #160.

This implementation gives periodical update to the estimated time of arrival (ETA), which is being done by linear regression over the last 60 chunks. Maybe its too verbose at the moment, but I think in general users like it that way (something is happening).

See the current output here:
http://www.mi.fu-berlin.de/users/marscher/eta.html

### CODE REVIEW

**Comment by franknoe** [comment]
Thanks for adding this functionality! For my taste there are too many 
printouts though which clutter the notebook. Let's try to make this more 
compact.

Is there maybe a way to overwrite an output instead of making logs, i.e. 
something like
     5%    ETA: 10 s
and to overwrite that line instead of printing many of them?

Alternative: Fill up a bar with dots like that:
(text text text)          +----+----+----+----+
TICA mean progress |.........|....
(you just add dots until the right border is reached.

Am 17/04/15 um 23:27 schrieb Martin K. Scherer:

> requested by #160 https://github.com/markovmodel/PyEMMA/issues/160.
> 
> This implementation gives periodical update to the estimated time of 
> arrival (ETA), which is being done by linear regression over the last 
> 60 chunks. Maybe its too verbose at the moment, but I think in general 
> users like it that way (something is happening).
> 
> See the current output here:
> http://www.mi.fu-berlin.de/users/marscher/eta.html
> 
> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
> https://github.com/markovmodel/PyEMMA/pull/264
> 
> ```
>     Commit Summary
> ```
> - [license] updated year
> - [util] added estimated time of arrival module
> - [coor/tica] show eta for mean and cov calculation
> - [util/eta] use str concatenation since it is faster
> - [coor/transformer] added eta to get_output
> - [coor/transformer|tica] remember stride parameter in parametrize()
>   and respect it in eta.
> - [coor/pca] add eta
> - [coor/transformer] use a static counter instead of hex id as
>   logger name and remove logger upon deletion
> - [util/eta] use timediff to display eta
> - [coor/data/featurizer] made it a Transformer
>   
>   ```
>   File Changes
>   ```
> - _M_ LICENSE.txt
>   https://github.com/markovmodel/PyEMMA/pull/264/files#diff-0 (2)
> - _M_ pyemma/coordinates/data/featurizer.py
>   https://github.com/markovmodel/PyEMMA/pull/264/files#diff-1 (39)
> - _M_ pyemma/coordinates/transform/pca.py
>   https://github.com/markovmodel/PyEMMA/pull/264/files#diff-2 (23)
> - _M_ pyemma/coordinates/transform/tica.py
>   https://github.com/markovmodel/PyEMMA/pull/264/files#diff-3 (57)
> - _M_ pyemma/coordinates/transform/transformer.py
>   https://github.com/markovmodel/PyEMMA/pull/264/files#diff-4 (28)
> - _A_ pyemma/util/eta.py
>   https://github.com/markovmodel/PyEMMA/pull/264/files#diff-5 (186)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/markovmodel/PyEMMA/pull/264.patch
> - https://github.com/markovmodel/PyEMMA/pull/264.diff
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/264.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
I like the second answer of this one (the first one would add a dependency):

http://stackoverflow.com/questions/3002085/python-to-print-out-status-bar-and-percentage

Am 17/04/15 um 23:27 schrieb Martin K. Scherer:

> requested by #160 https://github.com/markovmodel/PyEMMA/issues/160.
> 
> This implementation gives periodical update to the estimated time of 
> arrival (ETA), which is being done by linear regression over the last 
> 60 chunks. Maybe its too verbose at the moment, but I think in general 
> users like it that way (something is happening).
> 
> See the current output here:
> http://www.mi.fu-berlin.de/users/marscher/eta.html
> 
> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
> https://github.com/markovmodel/PyEMMA/pull/264
> 
> ```
>     Commit Summary
> ```
> - [license] updated year
> - [util] added estimated time of arrival module
> - [coor/tica] show eta for mean and cov calculation
> - [util/eta] use str concatenation since it is faster
> - [coor/transformer] added eta to get_output
> - [coor/transformer|tica] remember stride parameter in parametrize()
>   and respect it in eta.
> - [coor/pca] add eta
> - [coor/transformer] use a static counter instead of hex id as
>   logger name and remove logger upon deletion
> - [util/eta] use timediff to display eta
> - [coor/data/featurizer] made it a Transformer
>   
>   ```
>   File Changes
>   ```
> - _M_ LICENSE.txt
>   https://github.com/markovmodel/PyEMMA/pull/264/files#diff-0 (2)
> - _M_ pyemma/coordinates/data/featurizer.py
>   https://github.com/markovmodel/PyEMMA/pull/264/files#diff-1 (39)
> - _M_ pyemma/coordinates/transform/pca.py
>   https://github.com/markovmodel/PyEMMA/pull/264/files#diff-2 (23)
> - _M_ pyemma/coordinates/transform/tica.py
>   https://github.com/markovmodel/PyEMMA/pull/264/files#diff-3 (57)
> - _M_ pyemma/coordinates/transform/transformer.py
>   https://github.com/markovmodel/PyEMMA/pull/264/files#diff-4 (28)
> - _A_ pyemma/util/eta.py
>   https://github.com/markovmodel/PyEMMA/pull/264/files#diff-5 (186)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/markovmodel/PyEMMA/pull/264.patch
> - https://github.com/markovmodel/PyEMMA/pull/264.diff
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/264.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
BTW, if we have a progress bar - which is relatively easy to do because 
we know which fraction of the data has been processed at every chunk - 
we might not even need a time estimate. We could centralize this more or 
less like that:

param_add_data(...)

```
 if pass == 1:
     if first_chunk:
         print "calculating mean : "
         self.pb = progressbar()

     # do work
     # update n = current step (out of N)

     if last_chunk:
         self.pb.close()
     else:
         self.pb.update(self.n / self.N) # update fraction of work done

 etc.
```

Am 17/04/15 um 23:27 schrieb Martin K. Scherer:

> requested by #160 https://github.com/markovmodel/PyEMMA/issues/160.
> 
> This implementation gives periodical update to the estimated time of 
> arrival (ETA), which is being done by linear regression over the last 
> 60 chunks. Maybe its too verbose at the moment, but I think in general 
> users like it that way (something is happening).
> 
> See the current output here:
> http://www.mi.fu-berlin.de/users/marscher/eta.html
> 
> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
> https://github.com/markovmodel/PyEMMA/pull/264
> 
> ```
>     Commit Summary
> ```
> - [license] updated year
> - [util] added estimated time of arrival module
> - [coor/tica] show eta for mean and cov calculation
> - [util/eta] use str concatenation since it is faster
> - [coor/transformer] added eta to get_output
> - [coor/transformer|tica] remember stride parameter in parametrize()
>   and respect it in eta.
> - [coor/pca] add eta
> - [coor/transformer] use a static counter instead of hex id as
>   logger name and remove logger upon deletion
> - [util/eta] use timediff to display eta
> - [coor/data/featurizer] made it a Transformer
>   
>   ```
>   File Changes
>   ```
> - _M_ LICENSE.txt
>   https://github.com/markovmodel/PyEMMA/pull/264/files#diff-0 (2)
> - _M_ pyemma/coordinates/data/featurizer.py
>   https://github.com/markovmodel/PyEMMA/pull/264/files#diff-1 (39)
> - _M_ pyemma/coordinates/transform/pca.py
>   https://github.com/markovmodel/PyEMMA/pull/264/files#diff-2 (23)
> - _M_ pyemma/coordinates/transform/tica.py
>   https://github.com/markovmodel/PyEMMA/pull/264/files#diff-3 (57)
> - _M_ pyemma/coordinates/transform/transformer.py
>   https://github.com/markovmodel/PyEMMA/pull/264/files#diff-4 (28)
> - _A_ pyemma/util/eta.py
>   https://github.com/markovmodel/PyEMMA/pull/264/files#diff-5 (186)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/markovmodel/PyEMMA/pull/264.patch
> - https://github.com/markovmodel/PyEMMA/pull/264.diff
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/264.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I've also tried to overwrite output, but the problem is (at least in 
ipython-nb) that you would loose all the previous output of the cell. In 
my opinion this is not really desirable.

As a workaround we can create a new output cell exclusively for the 
progressbar.

**Comment by franknoe** [comment]
Am 18/04/15 um 01:41 schrieb Martin K. Scherer:

> I've also tried to overwrite output, but the problem is (at least in
> ipython-nb) that you would loose all the previous output of the cell. In
> my opinion this is not really desirable.
> 
> As a workaround we can create a new output cell exclusively for the
> progressbar.
> ok, try it.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/264#issuecomment-94098729.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
The right way to draw progressbars in Ipython notebooks is IPython.html.widgets.IntProgress. On text-based environments we can use a library (or just copy the needed stuff into our tree).

**Comment by marscher** [comment]
It is now very pretty no matter if in IPython (in that case it uses a fancy widget) or console (in that case it uses a fancy text progressbar). To achieve the later I have imported the needed code of the project "etaprogress", which adds ~700 lines of code.

**Comment by franknoe** [comment]
OK. Is this in a PR or branch? Sorry, I haven't really followed 
developments in the last few days.

Am 21/04/15 um 18:15 schrieb Martin K. Scherer:

> It is now very pretty no matter if in IPython (in that case it uses a 
> fancy widget) or console (in that case it uses a fancy text 
> progressbar). To achieve the later I have imported the needed code of 
> the project "etaprogress", which adds ~700 lines of code.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/264#issuecomment-94857203.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
yes on my fork. The PR is open

If you wanna try it out:

git checkout devel
git checkout -b feature_runtime_estimation
git fetch https://github.com/marscher/PyEMMA.git && git merge FETCH_HEAD

**Comment by franknoe** [comment]
Sure, I'll try it out. Should we open a branch release_v1.2.1 for 
collecting merges for that release?

Am 21/04/15 um 21:07 schrieb Martin K. Scherer:

> yes on my fork. The PR is open
> 
> If you wanna try it out:
> 
> git checkout devel
> git checkout -b feature_runtime_estimation
> git fetch https://github.com/marscher/PyEMMA.git && git merge FETCH_HEAD
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/264#issuecomment-94908638.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
so far I don't see a difference, at least in ipython. Can you point me 
to where the changes are? Do I need to activate the feature?

Am 21/04/15 um 21:07 schrieb Martin K. Scherer:

> yes on my fork. The PR is open
> 
> If you wanna try it out:
> 
> git checkout devel
> git checkout -b feature_runtime_estimation
> git fetch https://github.com/marscher/PyEMMA.git && git merge FETCH_HEAD
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/264#issuecomment-94908638.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Hmh, you should see it. Maybe the merge was not successful - whats the 
output of git log?
Am 22.04.2015 um 11:15 schrieb Frank Noe:

> so far I don't see a difference, at least in ipython. Can you point me
> to where the changes are? Do I need to activate the feature?

**Comment by marscher** [comment]
sorry, my git fetch command was wrong (it fetched my forked devel branch)

git fetch https://github.com/marscher/PyEMMA.git feature_runtime_estimate
git checkout FETCH_HEAD -b feature_runtime_estimate

**Comment by franknoe** [comment]
Megageil :-) I love it.
A few minor issues:
- the get_output bar should also get a description
- try to use tabs to vertically align bars (e.g. calculate mean and 
  calculate cov for TICA/PCA)
- having these bars should be optional - if you do a lot of processing, 
  e.g. building multiple analyses for different parameters, one may not 
  want to get all the outputs.

Thanks a lot for this feature!

Am 22/04/15 um 13:38 schrieb Martin K. Scherer:

> sorry, my git fetch command was wrong (it fetched my forked devel branch)
> 
> git fetch https://github.com/marscher/PyEMMA.git feature_runtime_estimate
> git checkout FETCH_HEAD -b feature_runtime_estimate
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/264#issuecomment-95145967.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I want to introduce a configuration variable for pyemma.cfg, to disable the feature completely (default is on). Via that way, we can also turn it on/off during runtime.

**Comment by marscher** [comment]
Alignment would also be nice (in Ipython). Maybe we can wrap the widget in html somehow.

**Comment by franknoe** [comment]
Another question: did you need to add a dependency to ipython to enable 
that?

Am 23/04/15 um 18:41 schrieb Martin K. Scherer:

> I want to introduce a configuration variable for pyemma.cfg, to 
> disable the feature completely (default is on). Via that way, we can 
> also turn it on/off during runtime.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/264#issuecomment-95649745.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
no, its total optional. It is being checked if Ipython stuff can be
imported and if not it falls back to text progress bars.

**Comment by gph82** [comment]
which was kinda my point on the plane

On 24.04.2015 15:17, Martin K. Scherer wrote:

> no, its total optional. It is being checked if Ipython stuff can be
> imported and if not it falls back to text progress bars.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/pull/264#issuecomment-95930356.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

## http://userpage.fu-berlin.de/gph82/

**Comment by franknoe** [comment]
great

Am 24/04/15 um 15:17 schrieb Martin K. Scherer:

> no, its total optional. It is being checked if Ipython stuff can be
> imported and if not it falls back to text progress bars.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/264#issuecomment-95930356.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
and of course if it's an interactive session (if one uses Ipython shell,
html widgets make no sense).

**Comment by franknoe** [comment]
not what I understood, but doesn't matter.

Am 24/04/15 um 15:19 schrieb Guillermo Pérez-Hernández:

> which was kinda my point on the plane
> 
> On 24.04.2015 15:17, Martin K. Scherer wrote:
> 
> > no, its total optional. It is being checked if Ipython stuff can be
> > imported and if not it falls back to text progress bars.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/markovmodel/PyEMMA/pull/264#issuecomment-95930356.
> 
> ## 
> 
> Dr. Guillermo Pérez-Hernández
> Freie Universität Berlin
> Institute for Mathematics
> Arnimallee 6
> D-14195 Berlin
> tel 0049 30 838 75776
> 
> ## http://userpage.fu-berlin.de/gph82/
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/264#issuecomment-95930769.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I've wrapped the description text and the progressbar in IPython notebook in a BoxWidget so they are aligned in two rows. If there are no more suggestions, I will merge this soon.

**Comment by franknoe** [comment]
The output looks very beautiful now. I would like to have it a bit more compact if possible in order to avoid cluttering the notebook with many rows of output. Is it possible to have the progressbar and the Text in the same row or even in the same box (e.g. Text overlying the progress bar and shown in complementary colors?) I realize that this is purely cosmetic.

Please also remove log INFO's where a progress bar is shown. That is redundant.

Thanks!

**Pull request merged**
