### PR TITLE
[coor/api/save_traj] new optarg image_molecules and minor bugfix

### PR DESCRIPTION
**Pull request by gph82**
This incorporates the mdtraj's new feature of making molecules whole (instead of broken across PBCs) to save_traj, given that save_traj's main purpose is visualization

### CODE REVIEW

**Comment by marscher** [comment]
Thank you for this improvement! We then also need to require at least 1.7.2 in setup.py and meta.yaml (devtools/conda-recipe) to ensure nothing will break.

**Comment by marscher** [comment]
or probe the Trajectory object if it has the image attribute and trigger a warning instead?

**Comment by gph82** [comment]
I thought we we're doing that already. This can wait, until then (there's ways around it).

**Comment by marscher** [comment]
I think we are enforcing version >=1.7.0, so if this feature has been introduced in 1.7.2, we need to require that too.

**Comment by gph82** [comment]
@marscher , any clever way of re-triggering the appveyor build? Tests are failing because of  "Back-end server is at capacity for url: https://conda.anaconda.org/omnia/noarch/repodata.json.bz2: https://conda.anaconda.org/omnia/noarch/"...so....the intertubes are clogged :)

**Comment by marscher** [comment]
you can either add a (dummy) commit or I can re-trigger the build.

**Comment by gph82** [comment]
I re-triggered the build in travis, but my appveyor account does not allow me to do the same

**Pull request merged**
