### PR TITLE
[msm/estimators] MaximumLikelihoodMSM with fixed stationary vector

### PR DESCRIPTION
**Pull request by trendelkampschroer**
Add option statdist= to MSM estimator and updated unit tests.

### CODE REVIEW

**Comment by trendelkampschroer** [comment]
@franknoe Do you want to review/merge this?

**Comment by franknoe** [comment]
yes I will. Going to the office now.

Am 26/08/15 um 15:37 schrieb Benjamin Trendelkamp-Schroer:

> @franknoe https://github.com/franknoe Do you want to review/merge this?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/506#issuecomment-135024077.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by trendelkampschroer** [comment]
@franknoe Thanks

**Comment by franknoe** [comment]
To be compatible with the Estimator interface, you need to make sure that the name of an estimation parameter in **init** is the same as the name as the name with which you access that parameter. That means if you choose 'statdist' in **init**, you have to set `self.statdist=statdist`. Or use getter/setter properties mapping that name. That's because Estimators create a list of their properties by auto-inspecting init and that list is used e.g. in the setting of parameters in Meta-Algorithms such as ImpliedTimescales.

So you have to define a name that you are comfortable with using both as a parameter to **init** as well as a member in the Estimator class. For example `statdist_fixed`.

**Comment by trendelkampschroer** [comment]
Ok, I think I am not familiar enough with the structure at the moment. It would be great if we could go through this together when your back.

**Comment by franknoe** [comment]
Sure, no problem, but if we want to include this in the release that 
would be a bit too late. Is there a way that I can work on your branch?

Am 27/08/15 um 14:43 schrieb Benjamin Trendelkamp-Schroer:

> Ok, I think I am not familiar enough with the structure at the moment. 
> It would be great if we could go through this together when your back.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/506#issuecomment-135410119.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by trendelkampschroer** [comment]
Hi Frank,

I pushed the branch feature_msmrevpi to the central repo (origin). You can now pull it from there. 
After you have done your changes and pushed it to origin/feature_msmrevpi, I can update my version, to include your changes (update myfork) and create a pull request.

After that I'll delete the branch.

**Comment by franknoe** [comment]
Thank you! I think I can just update and push it without requiring a new 
PR. Will look at this.

Am 27/08/15 um 14:56 schrieb Benjamin Trendelkamp-Schroer:

> Hi Frank,
> 
> I pushed the branch feature_msmrevpi to the central repo (origin). You 
> can now pull it from there.
> After you have done your changes and pushed it to 
> origin/feature_msmrevpi, I can update my version, to include your 
> changes (update myfork) and create a pull request.
> 
> After that I'll delete the branch.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/506#issuecomment-135415084.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by trendelkampschroer** [comment]
Thanks!

**Comment by franknoe** [comment]
I have modified this branch and will close this PR for now. I had to make some changes in msmtools and need to wait for a new msmtools release before opening a new PR here.

**Pull request closed without merging**
