### PR TITLE
Fix sidechain torstions feat describe selection

### PR DESCRIPTION
**Pull request by marscher**
@gph82 can you take a look please?

### CODE REVIEW

**Comment by gph82** [comment]
LGTM, checked with  pyemma.version 2.5.1+65.gd42bad53. Correct labeling.

**Comment by marscher** [comment]
I guess you have checked this with and without a selection?

**Comment by gph82** [comment]
Of course! with () (and all residues are added up to all available chis) and then for just one residue

**Comment by marscher** [comment]
Thank you very much for testing this!

**Pull request merged**
