### PR TITLE
Feature cossin

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by franknoe** [comment]
Sorry, this feature is not complete:
- If cossin=True, you need to return the double dimension in the featurizer
- If cossin=True, you now have different features and thus need to change the describe() to contain cos and sin of that angle.
- The docstring is a bit misleading because one could think that you get (cos(a1), sin(a1), cos(a2), sin(a2),...) rather than (cos(a1), cos(a2), ... sin(a1), sin(a2), ...). I actually like the first version better, if it can be efficiently done.

**Comment by marscher** [comment]
It is possible to achieve our third point with numpy.dstack and a reshape.
Also adopted the description strings and dimensions accordingly.

**Comment by franknoe** [comment]
Still not quite right. describe() returns one label string _per feature_. cos(a) and sin(a) are two features, so they need to generate two strings. The number of strings returned by describe() should always be identical to dimension() (this could be a unit test).

**Comment by marscher** [comment]
Paretos principle applies to this request now :) will change it.

**Comment by franknoe** [comment]
looks good. Thanks @marscher

**Pull request merged**
