### PR TITLE
Save traj file handling

### LINKED ISSUE #788: [coor/save_traj]: building of an index file?
Hi, I don't know where this was introduced, but this was unknown to me:
save_traj relies upon indexing xtcs before carrying out its frame-of-file extraction. 

snap1

If the index has not been constructed before, this is definitely NOT the moment to do it, imho. Notice that I have to wait 20h+ to extract one single frame. 

I think that at least the possibility should be offered to skip reader construction (https://github.com/markovmodel/PyEMMA/blob/b5d9d6a912bb5016747ea1bbf84f5ce985d73735/pyemma/coordinates/data/util/frames_from_file.py#L35) and use the old implementation in cases where the trade-off is obviously worth it.

This is a REAL blocker for me now...

### PR DESCRIPTION
**Pull request by marscher**
Fixes #788 by only indexing files, which are are referenced by index array.

Unified implementation for frames_from_file and frames_from_files.

Changes:
- chunksize=0 got evaluated to default chunksize, because the comparision ("if chunksize") evaluates to False).
- coordinates.load uses chunksize=0 by default
- increased default chunksize of DataSource from 100 to 1000.
- FeatureReader may return mdtraj.Trajectory objects (private flag to toggle that).
- support setitem operation on mdtraj.Trajectory
- Added utility method in coordinates test to create synthetic trajs with known coordinates (ranges).

### CODE REVIEW

**Comment by marscher** [comment]
Windows build is completely borked due to a dllerror in scipy...

**Comment by gph82** [comment]
awesome. Will try soon and tell you. Thanks @marscher and @clonker for the 
debugging.

On 05/14/2016 04:47 PM, Martin K. Scherer wrote:

> Fixes #788 https://github.com/markovmodel/PyEMMA/issues/788 by only indexing
> files, which are are referenced by index array.
> 
> Unified implementation for frames_from_file and frames_from_files.
> 
> Changes:
> - chunksize=0 got evaluated to default chunksize, because the comparision ("if
>   chunksize") evaluates to False).
> - coordinates.load uses chunksize=0 by default
> - increased default chunksize of DataSource from 100 to 1000.
> - FeatureReader may return mdtraj.Trajectory objects (private flag to toggle
>   that).
> - support setitem operation on mdtraj.Trajectory
> - Added utility method in coordinates test to create synthetic trajs with
>   known coordinates (ranges).
> 
> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
> https://github.com/markovmodel/PyEMMA/pull/803
> 
> ```
>     Commit Summary
> ```
> - wip
> - [featurizer] show warning about empty feature list only once
> - [featurereader] added option to return plain mdtraj.Trajectory objects
> - [fragmentedreader] added reader_by_filename property
> - [coor.api] minor change
> - [coor/reader_utils] do not access private attributes
> - removed old impl
> - removed property attr
> - wip
> - unpack list of one element
> - fix iter
> - use public attr
> - wip
> - [coor/api] handle chunk_size argument correctly (0 evaluates to False).
> - def chunksize 1000
> - [patches] added setitem method for Trajectory objs
> - [reader_utils] def chunksize=1000, added setitem method for empty_traj
>   created objs.
> - [fragreader] use setitem method for traj objects collected by underlying
>   featurereaders
> - added test for cs=0
> - fix typo
> - [datasource] handle too large RA indices for stride
> - added create_traj in test.util.
> - bug fix
> - wip
> - [frames-from-file] fixed test
> - impl test, cleanup
> - removed dbg
> - fixes
>   
>   ```
>   File Changes
>   ```
> - _M_ pyemma/coordinates/api.py
>   https://github.com/markovmodel/PyEMMA/pull/803/files#diff-0 (45)
> - _M_ pyemma/coordinates/data/_base/datasource.py
>   https://github.com/markovmodel/PyEMMA/pull/803/files#diff-1 (9)
> - _M_ pyemma/coordinates/data/_base/iterable.py
>   https://github.com/markovmodel/PyEMMA/pull/803/files#diff-2 (2)
> - _M_ pyemma/coordinates/data/feature_reader.py
>   https://github.com/markovmodel/PyEMMA/pull/803/files#diff-3 (35)
> - _M_ pyemma/coordinates/data/featurization/featurizer.py
>   https://github.com/markovmodel/PyEMMA/pull/803/files#diff-4 (7)
> - _M_ pyemma/coordinates/data/fragmented_trajectory_reader.py
>   https://github.com/markovmodel/PyEMMA/pull/803/files#diff-5 (53)
> - _M_ pyemma/coordinates/data/util/frames_from_file.py
>   https://github.com/markovmodel/PyEMMA/pull/803/files#diff-6 (179)
> - _M_ pyemma/coordinates/data/util/reader_utils.py
>   https://github.com/markovmodel/PyEMMA/pull/803/files#diff-7 (25)
> - _M_ pyemma/coordinates/tests/test_featurereader.py
>   https://github.com/markovmodel/PyEMMA/pull/803/files#diff-8 (17)
> - _M_ pyemma/coordinates/tests/test_fragmented_trajectory.py
>   https://github.com/markovmodel/PyEMMA/pull/803/files#diff-9 (5)
> - _M_ pyemma/coordinates/tests/test_frames_from_file.py
>   https://github.com/markovmodel/PyEMMA/pull/803/files#diff-10 (9)
> - _M_ pyemma/coordinates/tests/test_random_access_stride.py
>   https://github.com/markovmodel/PyEMMA/pull/803/files#diff-11 (70)
> - _M_ pyemma/coordinates/tests/test_save_traj.py
>   https://github.com/markovmodel/PyEMMA/pull/803/files#diff-12 (79)
> - _M_ pyemma/coordinates/tests/test_save_trajs.py
>   https://github.com/markovmodel/PyEMMA/pull/803/files#diff-13 (9)
> - _M_ pyemma/coordinates/tests/test_traj_info_cache.py
>   https://github.com/markovmodel/PyEMMA/pull/803/files#diff-14 (2)
> - _A_ pyemma/coordinates/tests/util.py
>   https://github.com/markovmodel/PyEMMA/pull/803/files#diff-15 (24)
> - _M_ pyemma/coordinates/util/patches.py
>   https://github.com/markovmodel/PyEMMA/pull/803/files#diff-16 (28)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/markovmodel/PyEMMA/pull/803.patch
> - https://github.com/markovmodel/PyEMMA/pull/803.diff
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/pull/803

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75775

**Comment by gph82** [comment]
Hi @marscher, I just pulled your branch save_traj_file_handling and tried the example of #788 with very good results. great job!

snap3

**Comment by marscher** [comment]
Thank you for testing!

**Comment by franknoe** [comment]
great, thanks!

Am 16/05/16 um 16:20 schrieb Martin K. Scherer:

> Thank you for testing!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/803#issuecomment-219436960

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Pull request merged**
