### PR TITLE
Deterministic option of kmeans/kmeans++

### PR DESCRIPTION
**Pull request by clonker**
Deals with issue #505, i.e., adds an additional flag to the api that allows to fix the random seed on initialization. Also, one small fix for a unit test.

### CODE REVIEW

**Comment by franknoe** [comment]
Thanks Moritz! The failure is not due to your work, it's a random incarnation of an error bar problem with BHMMs. I think I need to adapt the prior choice in the test.

**Comment by franknoe** [comment]
This could be merged but someone needs to do this by hand. Probably Merging the Python 3 branch has caused a conflict with this one.

**Comment by marscher** [comment]
I'll do it manually.

**Comment by marscher** [comment]
done

**Comment by clonker** [comment]
Thanks! :)

**Comment by franknoe** [comment]
Thanks Moritz and Martin!

Am 26/08/15 um 17:57 schrieb Martin K. Scherer:

> I'll do it manually.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/507#issuecomment-135078529.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Pull request closed without merging**
