### PR TITLE
coordinates.api slight edit, unittest for save_trajs written, io util added

### PR DESCRIPTION
**Pull request by gph82**

### CODE REVIEW

**Comment by gph82** [comment]
Did not notice that  data/bpti_ca.pdb was not included in dev_release_1.2

**Comment by marscher** [comment]
no I did not - sorry. Are you sure you added it? You can include in this
PR and we merge it.

**Comment by gph82** [comment]
apparently it's there..do I need the full path? 
https://github.com/markovmodel/PyEMMA/tree/dev_release_1.2/pyemma/coordinates/tests/data

**Comment by gph82** [comment]
ok, so when I run nosetest out of the pyemma dir it works..., still does not find: "coordinates/tests/data/bpti_ca.pdb" in Travis

**Comment by marscher** [comment]
this should help:

path = os.path.join(os.path.split(__file__)[0],'data')
xtcfile = os.path.join(path, 'bpti_mini.xtc')
pdbfile = os.path.join(path, 'bpti_ca.pdb')

**Comment by gph82** [comment]
still failing, but at least not save_trajs

**Pull request merged**
