### PR TITLE
[base|coor|msm_estimators] Added progress reporter impl and use it in Transformers and Estimators.

### PR DESCRIPTION
**Pull request by marscher**
- Moved ProgressBar impl from pyemma.util.progressbar to pyemma._base.progress.bar
- new ProgressReporter interface (register, register_callback, silence(True|False), update)

Cktest on baysian msm leads to several "Sampling Models" progressbars, so it is not enabled right now. Need to discuss this case first.

### CODE REVIEW

**Comment by marscher** [comment]
needed to add two call back interfaces in bhmm (bayesian_hmm) and msmtools (tmatrix sampling) to enable the reportage of progress to an external procedure. 

Msmtools is now released with this addon to pypi and waiting for omnia conda recipes to be merged.

Also the build of bhmm should be fixed as soon as msmtools 1.0.3 is available, because the package depends on the conda version (didn't include nsteps parameter in tmatrix_sampler).

**Comment by marscher** [comment]
funny.. the import statements works on my local machine...

**Comment by franknoe** [comment]
thanks. This looks like it goes into the right direction, but at the 
moment I can't look into it. Maybe Fab could have a look.

Am 29/07/15 um 21:41 schrieb Martin K. Scherer:

> - Moved ProgressBar impl from pyemma.util.progressbar to
>   pyemma._base.progress.bar
> - new ProgressReporter interface (register, register_callback,
>   silence(True|False), update)
> 
> Cktest on baysian msm leads to several "Sampling Models" progressbars, 
> so it is not enabled right now. Need to discuss this case first.
> 
> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
> https://github.com/markovmodel/PyEMMA/pull/466
> 
> ```
>     Commit Summary
> ```
> - [base|coor|msm_estimators] Added progress reporter impl and use it
>   in Transformers and Estimators.
>   
>   ```
>   File Changes
>   ```
> - _M_ pyemma/_base/estimator.py
>   https://github.com/markovmodel/PyEMMA/pull/466/files#diff-0 (16)
> - _A_ pyemma/_base/progress/__init__.py
>   https://github.com/markovmodel/PyEMMA/pull/466/files#diff-1 (1)
> - _R_ pyemma/_base/progress/bar/_impl.py
>   https://github.com/markovmodel/PyEMMA/pull/466/files#diff-2 (0)
> - _R_ pyemma/_base/progress/bar/gui.py
>   https://github.com/markovmodel/PyEMMA/pull/466/files#diff-3 (0)
> - _R_ pyemma/_base/progress/bar/misc.py
>   https://github.com/markovmodel/PyEMMA/pull/466/files#diff-4 (0)
> - _A_ pyemma/_base/progress/reporter.py
>   https://github.com/markovmodel/PyEMMA/pull/466/files#diff-5 (120)
> - _A_ pyemma/_base/tests/__init__.py
>   https://github.com/markovmodel/PyEMMA/pull/466/files#diff-6 (0)
> - _A_ pyemma/_base/tests/test_progress.py
>   https://github.com/markovmodel/PyEMMA/pull/466/files#diff-7 (81)
> - _M_ pyemma/coordinates/clustering/kmeans.py
>   https://github.com/markovmodel/PyEMMA/pull/466/files#diff-8 (23)
> - _M_ pyemma/coordinates/data/numpy_filereader.py
>   https://github.com/markovmodel/PyEMMA/pull/466/files#diff-9 (11)
> - _M_ pyemma/coordinates/transform/pca.py
>   https://github.com/markovmodel/PyEMMA/pull/466/files#diff-10 (14)
> - _M_ pyemma/coordinates/transform/tica.py
>   https://github.com/markovmodel/PyEMMA/pull/466/files#diff-11 (12)
> - _M_ pyemma/coordinates/transform/transformer.py
>   https://github.com/markovmodel/PyEMMA/pull/466/files#diff-12 (26)
> - _M_ pyemma/msm/estimators/bayesian_hmsm.py
>   https://github.com/markovmodel/PyEMMA/pull/466/files#diff-13 (18)
> - _M_ pyemma/msm/estimators/bayesian_msm.py
>   https://github.com/markovmodel/PyEMMA/pull/466/files#diff-14 (18)
> - _M_ pyemma/msm/estimators/implied_timescales.py
>   https://github.com/markovmodel/PyEMMA/pull/466/files#diff-15 (16)
> - _M_ pyemma/msm/estimators/lagged_model_validators.py
>   https://github.com/markovmodel/PyEMMA/pull/466/files#diff-16 (14)
> - _D_ pyemma/util/progressbar/**init**.py
>   https://github.com/markovmodel/PyEMMA/pull/466/files#diff-17 (2)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/markovmodel/PyEMMA/pull/466.patch
> - https://github.com/markovmodel/PyEMMA/pull/466.diff
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/466.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
merged to dev_rel and then to devel

**Pull request closed without merging**
