### PR TITLE
[msm/flux] Pathway decomposition uses floating point tolerance when c…

### PR DESCRIPTION
**Pull request by trendelkampschroer**
…hecking the termination condition (current flux >= fraction \* total flux) in the main iteration

### CODE REVIEW

**Comment by franknoe** [comment]
What is `tol=1e-14` for?

**Comment by trendelkampschroer** [comment]
If decomposition is requested with fraction=1.0 the iteration has to successfully remove all reaction paths from the netflux network. This removal can introduce numerical errors since the flux matrix has to be updated after the detection of every path. I have observed that the algorithm can fail to discover pathways with very small capacity values at the end of the iteration,  i.e. the capacity of all previously found paths CF and the total capacity (or total flux) TF are almost equal/ fraction=1.0-tol. 

In order to prevent the algorithm from trying to detect paths (in a flux matrix possibly containing only numerical noise) and failing I have modified the termination criterion for the main iteration accordingly.

**Comment by franknoe** [comment]
Ah OK. Please document the argument then. I'll merge after the update.
I guess the high-level API (ReactiveFlux) is not affected by your change?

**Comment by trendelkampschroer** [comment]
The high level api is not affected by this change.

Will update the documentation and send a new pull request.

**Pull request merged**
