### PR TITLE
[setup] pin bhmm version to < 0.6

### LINKED ISSUE #599: set bhmm==0.5.2 in setup
The new release should use the bhmm bugfix, and for that the bhmm version number should be fixed to 0.5.2.

Addition to release file:
- Fixed bug in hidden MSMs that occurred with trajectories of different lengths

### PR DESCRIPTION
**Pull request by marscher**
Fixes #599

### CODE REVIEW

**Comment by marscher** [comment]
conda-build resolves dependencies correctly - merging.

**Comment by marscher** [comment]
So with the new bhmm version 0.5.2 there are deterministic test failures in msm.api.hmm

https://travis-ci.org/markovmodel/PyEMMA/jobs/88368696#L1644

@franknoe:
Is this behaviour expected?

**Comment by marscher** [comment]
It is output line 1644, actually the provided link should take you there, but at least my browser doesn't.

**Comment by franknoe** [comment]
That could be a result of the bug fix in the count matrix calculation. 
I'll have a look at this.

Am 30/10/15 um 17:18 schrieb Martin K. Scherer:

> So with the new bhmm version 0.5.2 there are deterministic test 
> failures in msm.api.hmm
> 
> https://travis-ci.org/markovmodel/PyEMMA/jobs/88368696#L1644
> 
> @franknoe https://github.com/franknoe:
> Is this behaviour expected?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/600#issuecomment-152571334.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Definitely expected, because the test trajectories have different 
lengths, so this was suffering from the bhmm counting bug. Please change 
the expected output to the new values.

Am 30/10/15 um 17:18 schrieb Martin K. Scherer:

> So with the new bhmm version 0.5.2 there are deterministic test 
> failures in msm.api.hmm
> 
> https://travis-ci.org/markovmodel/PyEMMA/jobs/88368696#L1644
> 
> @franknoe https://github.com/franknoe:
> Is this behaviour expected?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/600#issuecomment-152571334.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Pull request merged**
