### PR TITLE
Fix assert toptraj consistency

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by franknoe** [comment]
I suggest @gph82 to review that.

**Comment by marscher** [comment]
Yes, since he wrote this piece of code :+1:

**Comment by marscher** [comment]
going to merge and release an immediate micro release, since that code prior my changes forbids to use any format except XTC in pyemma.coordinates.

**Comment by franknoe** [comment]
thanks!

Am 06/09/15 um 12:31 schrieb Martin K. Scherer:

> going to merge and release an immediate micro release, since that code 
> prior my changes forbids to use any format except XTC in 
> pyemma.coordinates.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/548#issuecomment-138063934.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
For the next release, I suggest to build a test module that runs a 
mini-example of featurization + loading in various coordinate formats, 
such that we immediately track problems such as this one.
If I understand correctly this problem was introduced in 2.0 and we 
should thus notfiy the workshop attendees that the should upgrade to 
2.0.1 once it is out.

Am 06/09/15 um 12:31 schrieb Martin K. Scherer:

> going to merge and release an immediate micro release, since that code 
> prior my changes forbids to use any format except XTC in 
> pyemma.coordinates.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/548#issuecomment-138063934.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Yes it has been introduced in 2.0. I'll just add a minimal feature reader test for all supported mdtraj formats.

And of course we should announce it, to keep the hassle with this ugly glitch low.

**Comment by franknoe** [comment]
thanks

Am 06/09/15 um 12:42 schrieb Martin K. Scherer:

> Yes it has been introduced in 2.0. I'll just add a minimal feature 
> reader test for all supported mdtraj formats.
> 
> And of course we should announce it, to keep the hassle with this ugly 
> glitch low.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/548#issuecomment-138066956.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Perhaps we can just let the test run through various mdtraj-supported 
formats to be sure that there's not yet another different behavior with 
formats that we don't use at the moment?

Am 06/09/15 um 12:42 schrieb Martin K. Scherer:

> Yes it has been introduced in 2.0. I'll just add a minimal feature 
> reader test for all supported mdtraj formats.
> 
> And of course we should announce it, to keep the hassle with this ugly 
> glitch low.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/548#issuecomment-138066956.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Pull request merged**
