### PR TITLE
Split up MDFeaturizer and Feature impl

### PR DESCRIPTION
**Pull request by marscher**
@gph82 can you please have look? I actually changed some lines in groupmindist (dimension, added a TODO).

### CODE REVIEW

**Comment by franknoe** [comment]
Isn't that a bit too fine grained?

Any, can look at this later. I suppose we don't need to merge this 
before the workshop?

Am 16/02/16 um 23:29 schrieb Martin K. Scherer:

> @gph82 https://github.com/gph82 can you please have look? I actually 
> changed some lines in groupmindist (dimension, added a TODO).
> 
> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
> https://github.com/markovmodel/PyEMMA/pull/688
> 
> ```
>     Commit Summary
> ```
> - check for empty indices
> - [coor.featurizer] split up unit in features and featurizer.
> - [coor.Featurizer] further code cleanup
>   
>   ```
>   File Changes
>   ```
> - _A_ pyemma/coordinates/data/featurization/**init**.py
>   https://github.com/markovmodel/PyEMMA/pull/688/files#diff-0 (0)
> - _A_ pyemma/coordinates/data/featurization/_base.py
>   https://github.com/markovmodel/PyEMMA/pull/688/files#diff-1 (41)
> - _A_ pyemma/coordinates/data/featurization/angles.py
>   https://github.com/markovmodel/PyEMMA/pull/688/files#diff-2 (200)
> - _A_ pyemma/coordinates/data/featurization/distances.py
>   https://github.com/markovmodel/PyEMMA/pull/688/files#diff-3 (187)
> - _A_ pyemma/coordinates/data/featurization/misc.py
>   https://github.com/markovmodel/PyEMMA/pull/688/files#diff-4 (200)
> - _A_ pyemma/coordinates/data/featurization/util.py
>   https://github.com/markovmodel/PyEMMA/pull/688/files#diff-5 (211)
> - _M_ pyemma/coordinates/data/featurizer.py
>   https://github.com/markovmodel/PyEMMA/pull/688/files#diff-6 (843)
> - _M_ pyemma/coordinates/tests/test_featurizer.py
>   https://github.com/markovmodel/PyEMMA/pull/688/files#diff-7 (4)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/markovmodel/PyEMMA/pull/688.patch
> - https://github.com/markovmodel/PyEMMA/pull/688.diff
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/688.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Yes.

Am 17/02/16 um 13:26 schrieb Martin K. Scherer:

> On 17.02.2016 07:37, Frank Noe wrote:
> 
> > Isn't that a bit too fine grained?
> > Maybe it is, but having a 1600 lines module is far too overcharged. This
> > is nothing critical, we can discuss this after the workshop/seminar.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/688#issuecomment-185177225.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
@marscher things look okay from here.

**Pull request merged**
