### PR TITLE
Csv fixes

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by marscher** [comment]
Windows is crazy. I pass [[1,2,3], [4,5,6]] as reference and get arange(9).reshape(-1,3) out. WTF!

``` python
    def test_newline_at_eof(self):
        x = "1 2 3\n4 5 6\n\n"
        desired = np.fromstring(x, sep=" ", dtype=np.float32).reshape(-1, 3)
        assert len(desired) == 2
        with tempfile.NamedTemporaryFile(mode='w', delete=False) as f:
            f.write(x)
            f.close()
            reader = CSVReader(f.name)
            result = reader.get_output()[0]
            np.testing.assert_allclose(result, desired)

```

```
======================================================================
FAIL: test_newline_at_eof (pyemma.coordinates.tests.test_csvreader.TestCSVReader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\miniconda\envs\_test\lib\site-packages\pyemma-2.1rc3+99.g131b068-py2.7-win32.egg\pyemma\coordinates\tests\test_csvreader.py", line 268, in test_newline_at_eof
    np.testing.assert_allclose(result, desired)
  File "C:\Miniconda\envs\_test\lib\site-packages\numpy\testing\utils.py", line 1359, in assert_allclose
    verbose=verbose, header=header)
  File "C:\Miniconda\envs\_test\lib\site-packages\numpy\testing\utils.py", line 668, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(shapes (3, 3), (2, 3) mismatch)
 x: array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]], dtype=float32)
 y: array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]], dtype=float32)
```

**Comment by marscher** [comment]
On Py34, x64:

``` python
======================================================================
ERROR: test_newline_at_eof_carriage_return (pyemma.coordinates.tests.test_csvreader.TestCSVReader)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\miniconda3-x64\envs\_test\lib\site-packages\pyemma-2.1rc3+99.g131b068-py3.4-win-amd64.egg\pyemma\coordinates\tests\test_csvreader.py", line 276, in test_newline_at_eof_carriage_return
    reader = CSVReader(f.name)
  File "c:\miniconda3-x64\envs\_test\lib\site-packages\pyemma-2.1rc3+99.g131b068-py3.4-win-amd64.egg\pyemma\coordinates\data\py_csv_reader.py", line 239, in __init__
    self.filenames = filenames
  File "c:\miniconda3-x64\envs\_test\lib\site-packages\pyemma-2.1rc3+99.g131b068-py3.4-win-amd64.egg\pyemma\coordinates\data\_base\datasource.py", line 117, in filenames
    info = self._get_traj_info(filename)
  File "c:\miniconda3-x64\envs\_test\lib\site-packages\pyemma-2.1rc3+99.g131b068-py3.4-win-amd64.egg\pyemma\coordinates\data\py_csv_reader.py", line 406, in _get_traj_info
    length, offsets = PyCSVReader._calc_offsets(fh)
  File "c:\miniconda3-x64\envs\_test\lib\site-packages\pyemma-2.1rc3+99.g131b068-py3.4-win-amd64.egg\pyemma\coordinates\data\py_csv_reader.py", line 364, in _calc_offsets
    offsets[i] = fh.tell()
OverflowError: int too big to convert
```

**Comment by franknoe** [comment]
So is this needed for the 2.1 release? Is it a bugfix for things that have led to problems?

**Comment by franknoe** [comment]
@marscher how is this going? If this issue doesn't break any previous code, I would prefer to release 2.1 sooner rather than later.

**Comment by marscher** [comment]
It contains several bug fixes for serious issues. So yes, it should be
contained in 2.1

The windows related problems are unfortunately hard to tackle.

**Pull request merged**
