### PR TITLE
refactor random access

### PR DESCRIPTION
**Pull request by clonker**
Some performance optimizations and removal of random access for not supported file formats / readers.

### CODE REVIEW

**Comment by marscher** [comment]
Thank you. What is the state this PR is based on?

**Comment by clonker** [comment]
The current state (this morning) of the devel_refactor_transformer branch.

**Comment by marscher** [comment]
so why would this merge include the whole prior history of devel_refactor_transformer?

**Comment by clonker** [comment]
You are right, I somehow confused something but now it should be the correct state.

**Comment by marscher** [comment]
Looks good

**Pull request merged**
