### PR TITLE
Fix warnings when importing pyemma

### PR DESCRIPTION
**Pull request by clonker**
This pull deals with issue #683. It contains an out of the refactor_transformer branch extracted patch by  @marscher dealing with the warnings when importing pyemma.

### CODE REVIEW

**Comment by franknoe** [comment]
Thanks a lot Moritz!! Can you also trigger a patch release if this passes or should we wait for Martin?

**Comment by clonker** [comment]
No problem! I guess the safer bet would be to wait for him, nevertheless I can have a look at the release system, try to figure it out and then maybe trigger a patch release.

**Comment by franknoe** [comment]
Yes, please do. It would be good if we have at least two people able to 
do this.

Martin wrote a release HOWTO in msmtools, perhaps this is useful:

https://github.com/markovmodel/msmtools/blob/devel/dev_readme.rst

Am 08/02/16 um 13:50 schrieb Moritz Hoffmann:

> No problem! I guess the safer bet would be to wait for him, 
> nevertheless I can have a look at the release system, try to figure it 
> out and then maybe trigger a patch release.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/684#issuecomment-181354140.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by clonker** [comment]
Yes this is very useful, thank you!

**Comment by franknoe** [comment]
Please feel free to make a PR with additions / suggestions if something 
is missing or unclear.

Am 08/02/16 um 13:59 schrieb Moritz Hoffmann:

> Yes this is very useful, thank you!
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/684#issuecomment-181356212.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Pull request merged**
