### PR TITLE
[msm/api] corrected values due to release of bhmm 0.5.2 (uniform traj length bug)

### PR DESCRIPTION
**Pull request by marscher**
.

### CODE REVIEW

**Comment by franknoe** [comment]
A corresponding update is needed in the doc test of timescales_hmsm

**Comment by marscher** [comment]
We have to investigate, why only Python 3.3 fails deterministically (able to reproduce this locally).

The timescalles in Py33 are always different than the other tested branches of Python:

``` python
File "/home/travis/miniconda/envs/_test/lib/python3.3/site-packages/pyEMMA-2.0.1+61.g7ef8fbb-py3.3-linux-x86_64.egg/pyemma/msm/api.py", line 548, in pyemma.msm.api.timescales_hmsm

Failed example:

    print(ts.timescales) # doctest: +ELLIPSIS

Expected:

    [[  1.691]
     [  7.184]
     [  2.037]
     [ 41.015]
     [ 10.853]]

Got:
    [[  1.691]
     [  7.537]
     [  1.919]
     [ 40.962]
     [ 11.527]]
```

**Comment by marscher** [comment]
In py33 bhmm converges to a slightly different transition matrix than other branches:

``` python
Expected:
    [[ 0.711  0.289]
     [ 0.206  0.794]]

Got:
    [[ 0.756  0.244]
     [ 0.205  0.795]]
```

**Comment by marscher** [comment]
I got this... the bhmm has not been built for old numpy versions like the one we test against, so this can not work :+1:

**Comment by marscher** [comment]
seems like the binary is only built for py27, py34 and py35 - so py33 is missing in the build queue somewhere.

**Comment by marscher** [comment]
omnia-md/conda-recipes#370

**Comment by marscher** [comment]
Since Python 3.3 has been removed from Omnia, I've also kicked it out from Travis build matrix (and added Python 3.5).

**Comment by marscher** [comment]
Appveyor is still failing because of this Matplotlib png bug - which seems to be unfixed/unreleased upstream. I'm going to merge soon.

**Comment by franknoe** [comment]
Does that mean PyEMMA won't work on Windows? If so, how can we avoid 
this problem?

Am 03/11/15 um 14:45 schrieb Martin K. Scherer:

> Appveyor is still failing because of this Matplotlib png bug - which 
> seems to be unfixed/unreleased upstream. I'm going to merge soon.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/602#issuecomment-153356546.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 03.11.2015 um 15:02 schrieb Frank Noe:

> Does that mean PyEMMA won't work on Windows? If so, how can we avoid
> this problem?

It means that Matplotlib is broken on Windows (and therefore Pyemma can 
not be imported, since the plots package is automatically imported).

Do you think it is worth spending much time on looking for workarounds 
for this or simply wait until this is fixed upstream?

**Comment by franknoe** [comment]
Matplotlib broken on Windows? This sounds pretty dramatic, hard to 
believe, since they would certainly test on windows. @fabian-paul can 
you confirm this?

Am 03/11/15 um 15:04 schrieb Martin K. Scherer:

> Am 03.11.2015 um 15:02 schrieb Frank Noe:
> 
> > Does that mean PyEMMA won't work on Windows? If so, how can we avoid
> > this problem?
> 
> It means that Matplotlib is broken on Windows (and therefore Pyemma can
> not be imported, since the plots package is automatically imported).
> 
> Do you think it is worth spending much time on looking for workarounds
> for this or simply wait until this is fixed upstream?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/602#issuecomment-153364436.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
It could also be that Appveyors pre-installed Miniconda is broken somehow.

**Comment by marscher** [comment]
I can confirm that latest matplotlib build for win64/py27 is broken. The upstream bug has been reported here:

https://github.com/conda/conda/issues/1753

**Comment by marscher** [comment]
If we pin down to matplotlib 1.4.2, we also enforce the usage of the old numpy version 1.9, which is not desireable in my opinion (will also pin down scipy and so forth).

Note that this already broken and we can only enforce the win-users to use all this old software, but in the meantime the originating problem will be solved and then there is no way for these users to upgrade until we un-pin again.

It is just a matter of time until this gets fixed (it is an important package) and we have only 1-2 windows users as indicated by the recent download statistics.

**Comment by franknoe** [comment]
I agree, this is not desireable.

However, if the appveyor tests fail already at import time, I guess the 
units tests aren't executed at all under windows - or am I wrong? If 
they are not, how do we know that the windows PyEMMA does work except 
for the matplotlib problem?

Best Frank

Am 03/11/15 um 16:56 schrieb Martin K. Scherer:

> If we pin down to matplotlib 1.4.2, we also enforce the usage of the 
> old numpy version 1.9, which is not desireable in my opinion (will 
> also pin down scipy and so forth).
> 
> Note that this already broken and we can only enforce the win-users to 
> use all this old software, but in the meantime the originating problem 
> will be solved and then there is no way for these users to upgrade 
> until we un-pin again.
> 
> It is just a matter of time until this gets fixed (it is an important 
> package) and we have only 1-2 windows users as indicated by the recent 
> download statistics.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/602#issuecomment-153396861.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 03.11.2015 um 18:10 schrieb Frank Noe:

> I agree, this is not desireable.
> 
> However, if the appveyor tests fail already at import time, I guess the
> units tests aren't executed at all under windows - or am I wrong? If
> they are not, how do we know that the windows PyEMMA does work except
> for the matplotlib problem?

Is this a rhetoric question?

**Comment by franknoe** [comment]
of course not

Am 03/11/15 um 18:25 schrieb Martin K. Scherer:

> Am 03.11.2015 um 18:10 schrieb Frank Noe:
> 
> > I agree, this is not desireable.
> > 
> > However, if the appveyor tests fail already at import time, I guess the
> > units tests aren't executed at all under windows - or am I wrong? If
> > they are not, how do we know that the windows PyEMMA does work except
> > for the matplotlib problem?
> 
> Is this a rhetoric question?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/602#issuecomment-153424694.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Pull request merged**
