### PR TITLE
[util/config] do not fail, if configuration directory (.pyemma) can not be created.

### LINKED ISSUE #350: .pyemma is not writeable
I get a error when importing pyemma in a job on a cluster, it says ".pyemma is not writeable". But when I import pyemma in python it works without error. I tried making .pyemma directory chmod 777, but didn't help. Do you know how to fix this?

"""
raceback (most recent call last):
  File "/home/eh22/local/bin/lsdmap", line 3, in <module>
    import lsdmap.lsdm as lsdm
  File "/home/eh22/local/lib/python2.7/site-packages/lsdmap/lsdm.py", line 15, in <module>
    from lsdmap.util import metric as mt
  File "/home/eh22/local/lib/python2.7/site-packages/lsdmap/util/metric.py", line 7, in <module>
    import pyemma
  File "/home/eh22/local/lib/python2.7/site-packages/pyemma/**init**.py", line 31, in <module>
    from . import coordinates
  File "/home/eh22/local/lib/python2.7/site-packages/pyemma/coordinates/**init**.py", line 75, in <module>
    from .api import *
  File "/home/eh22/local/lib/python2.7/site-packages/pyemma/coordinates/api.py", line 32, in <module>
    from pyemma.util.log import getLogger as _getLogger
  File "/home/eh22/local/lib/python2.7/site-packages/pyemma/util/log.py", line 124, in <module>
    setupLogging()
  File "/home/eh22/local/lib/python2.7/site-packages/pyemma/util/log.py", line 60, in setupLogging
    from pyemma.util.config import conf_values
  File "/home/eh22/local/lib/python2.7/site-packages/pyemma/util/config.py", line 205, in <module>
    readConfiguration()
  File "/home/eh22/local/lib/python2.7/site-packages/pyemma/util/config.py", line 156, in readConfiguration
    pyemma_cfg_dir = create_cfg_dir(default_pyemma_conf)
  File "/home/eh22/local/lib/python2.7/site-packages/pyemma/util/config.py", line 134, in create_cfg_dir
    raise RuntimeError("%s is not writeable" % pyemma_cfg_dir)
RuntimeError: /home/eh22/.pyemma is not writeable
"""

### PR DESCRIPTION
**Pull request by marscher**
Triggers a UserWarning instead. Fixes #350

### CODE REVIEW

**Comment by franknoe** [comment]
Looks OK to me, but AppVeyor build fails.

**Comment by marscher** [comment]
obviously.

**Comment by marscher** [comment]
The test failures are the new minRMSD feature and on windows test_tica which both are failing randomly...

**Comment by gph82** [comment]
Preparing PR right now, trying to make it less random.

**Pull request merged**
