### PR TITLE
[msm.estimators]: fixed trajectory weights (MSM/HMM)

### LINKED ISSUE #717: [trajectory_weights] cannot handle list of dtrajs of different lengths
I think this had not been caught by any test, 

``` python
import pyemma
import numpy as np
nt = int(1e3)

print(pyemma.__version__)
#2.1rc3-16-g1b54118-dirty

P = np.array([
        [0.1,.9],
        [0.5, .5]
    ])

# Minimal MSM, two dtarjs 5 steps each, no problem
nt = 5
dtrajs = pyemma.msm.generation.generate_trajs(P, 2, nt)


MSM = pyemma.msm.estimate_markov_model(dtrajs, lag=1)
MSM.trajectory_weights()
#[array([ 0.06315789,  0.06315789,  0.07368421,  0.06315789,  0.07368421]),
# array([ 0.06315789,  0.06315789,  0.06315789,  0.07368421,  0.06315789])]

# Append a 3rd trajectory, twice as long as the others
longer_traj = pyemma.msm.generation.generate_trajs(P, 1, 2* nt)[0]
dtrajs.append(longer_traj)

MSM = pyemma.msm.estimate_markov_model(dtrajs, lag=1)
MSM.trajectory_weights()
```

now we get the error:

``` python
AttributeError                            Traceback (most recent call last)
/home/mi/gph82/miniconda3/lib/python3.4/site-packages/numpy/core/fromnumeric.py in sum(a, axis, dtype, out, keepdims)
   1826         try:
-> 1827             sum = a.sum
   1828         except AttributeError:

AttributeError: 'list' object has no attribute 'sum'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-8-b3ddfefc3ce9> in <module>()
      4 #print(len(dtrajs))
      5 MSM = pyemma.msm.estimate_markov_model(dtrajs, lag=1)
----> 6 MSM.trajectory_weights()

/home/mi/gph82/programs/PyEmma/pyemma/msm/estimators/maximum_likelihood_msm.py in trajectory_weights(self)
    532             w = statdist_full[dtraj] / hist[dtraj]
    533             W.append(w)
--> 534             wtot += _np.sum(W)
    535         # normalize
    536         for w in W:

/home/mi/gph82/miniconda3/lib/python3.4/site-packages/numpy/core/fromnumeric.py in sum(a, axis, dtype, out, keepdims)
   1828         except AttributeError:
   1829             return _methods._sum(a, axis=axis, dtype=dtype,
-> 1830                                  out=out, keepdims=keepdims)
   1831         # NOTE: Dropping the keepdims parameters here...
   1832         return sum(axis=axis, dtype=dtype, out=out)

/home/mi/gph82/miniconda3/lib/python3.4/site-packages/numpy/core/_methods.py in _sum(a, axis, dtype, out, keepdims)
     30 
     31 def _sum(a, axis=None, dtype=None, out=None, keepdims=False):
---> 32     return umr_sum(a, axis, dtype, out, keepdims)
     33 
     34 def _prod(a, axis=None, dtype=None, out=None, keepdims=False):

ValueError: operands could not be broadcast together with shapes (5,) (10,) 


```

### PR DESCRIPTION
**Pull request by franknoe**
Fixes #717 

@marscher : this failure occurs on my system. Please check:

```
======================================================================
ERROR: test_corrupted_db (pyemma.coordinates.tests.test_traj_info_cache.TestTrajectoryInfoCache)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/noe/data/software_projects/pyemma/pyemma/coordinates/tests/test_traj_info_cache.py", line 209, in test_corrupted_db
    db = TrajectoryInfoCache(name)
  File "/Users/noe/data/software_projects/pyemma/pyemma/coordinates/data/util/traj_info_cache.py", line 156, in __init__
    self._database.sync()
AttributeError: sync
```

### CODE REVIEW

**Comment by franknoe** [comment]
Weird that Travis and Appveyor don't exhibit this problem at all. Any ideas?

**Comment by marscher** [comment]
It is not weird - we're not testing OSX on travis (which starts to be supported recently).

**Comment by franknoe** [comment]
OK, but do you know what causes this problem?

Am 07/03/16 um 13:57 schrieb Martin K. Scherer:

> It is not weird - we're not testing OSX on travis (which starts to be 
> supported recently).
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/719#issuecomment-193238104.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 07.03.2016 um 14:49 schrieb Frank Noe:

**Comment by franknoe** [comment]
I have no idea what that means. Can you give me a command to find this out?

Am 07/03/16 um 14:53 schrieb Martin K. Scherer:

> Am 07.03.2016 um 14:49 schrieb Frank Noe:
> 
> > OK, but do you know what causes this problem?
> > we're using anydbm to get a implementation of a file serialized
> > dictionary on any system. So I need to know which DBM file format you're
> > using to figure this out. Actually every impl should have a sync method,
> > but it does not seem to be the case.
> > 
> > Am 07/03/16 um 13:57 schrieb Martin K. Scherer:
> > 
> > > It is not weird - we're not testing OSX on travis (which starts to be
> > > supported recently).
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> > > https://github.com/markovmodel/PyEMMA/pull/719#issuecomment-193238104.
> > 
> > ## 
> > 
> > ---
> > 
> > Prof. Dr. Frank Noe
> > Head of Computational Molecular Biology group
> > Freie Universitaet Berlin
> > 
> > Phone: (+49) (0)30 838 75354
> > Web: research.franknoe.de
> > 
> > ## Mail: Arnimallee 6, 14195 Berlin, Germany
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/markovmodel/PyEMMA/pull/719#issuecomment-193254028.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/719#issuecomment-193255848.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 07.03.2016 um 14:58 schrieb Frank Noe:

**Comment by franknoe** [comment]
/Users/noe/.pyemma/trajlen_cache.dat: cannot open 
`/Users/noe/.pyemma/trajlen_cache.dat' (No such file or directory)

Am 07/03/16 um 15:00 schrieb Martin K. Scherer:

> file ~/.pyemma/trajlen_cache.dat

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 07.03.2016 um 15:02 schrieb Frank Noe:

> /Users/noe/.pyemma/trajlen_cache.dat: cannot open
> `/Users/noe/.pyemma/trajlen_cache.dat' (No such file or directory)

try wildcard on this:

file $HOME/.pyemma/trajlen_cache*

**Comment by franknoe** [comment]
/Users/noe/.pyemma/trajlen_cache.db: Berkeley DB 1.85 (Hash, version 2, 
native byte-order)

Am 07/03/16 um 15:04 schrieb Martin K. Scherer:

> file $HOME/.pyemma/trajlen_cache*

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Well installing berkdb with conda and trying to access the sync method on that works just fine. Maybe your installation is messed up?

**Comment by marscher** [comment]
However I can reproduce this on Travis OSX now.

**Pull request merged**
