### PR TITLE
Merge devel into dev release 1.3

### PR DESCRIPTION
**Pull request by clonker**
Referring to PR #352 which was merged into devel instead of dev_release_1.3.

### CODE REVIEW

**Comment by franknoe** [comment]
did you merge or rebase? Should be rebase

Am 01/07/15 um 12:40 schrieb Moritz Hoffmann:

> Referring to PR #352 https://github.com/markovmodel/PyEMMA/pull/352 
> which was merged into devel instead of dev_release_1.3.
> 
> ---
> 
> ```
>     You can view, comment on, or merge this pull request online at:
> ```
> 
> https://github.com/markovmodel/PyEMMA/pull/387
> 
> ```
>     Commit Summary
> ```
> - [doc] added autoautosummary directive
> - [doc] documentation updates for coordinates/pca and
>   msm/(estimated_)markov_model.
> - [doc] documentation updates
> - [doc] fixed accidental constructor change of msm
> - Merge branch 'devel' of https://github.com/markovmodel/PyEMMA into
>   sphinx_doc_autoautosummary
> - [coordinates/transform/docs] moved updated docs to **init**
> - Revert "[coor/test_featurereader] added test for two files."
> - [bugfix][coordinates/tica] fixed normalization of correlation
>   matrices (with traditional counting)
> - Merge pull request #386 from fabian-paul/fix_tica_normalization
> - # Conflicts:
> - Merge branch 'devel' of https://github.com/markovmodel/PyEMMA into
>   sphinx_doc_autoautosummary
> - Updated docs of MDFeaturizer
> - Merge pull request #352 from clonker/sphinx_doc_autoautosummary
> - Merge branch 'devel' of https://github.com/markovmodel/PyEMMA into
>   sphinx_doc_autoautosummary
>   
>   ```
>   File Changes
>   ```
> - _M_ doc/source/conf.py
>   https://github.com/markovmodel/PyEMMA/pull/387/files#diff-0 (51)
> - _M_ pyemma/coordinates/api.py
>   https://github.com/markovmodel/PyEMMA/pull/387/files#diff-1 (112)
> - _M_ pyemma/coordinates/clustering/kmeans.py
>   https://github.com/markovmodel/PyEMMA/pull/387/files#diff-2 (42)
> - _M_ pyemma/coordinates/clustering/regspace.py
>   https://github.com/markovmodel/PyEMMA/pull/387/files#diff-3 (67)
> - _M_ pyemma/coordinates/clustering/uniform_time.py
>   https://github.com/markovmodel/PyEMMA/pull/387/files#diff-4 (21)
> - _M_ pyemma/coordinates/data/featurizer.py
>   https://github.com/markovmodel/PyEMMA/pull/387/files#diff-5 (16)
> - _M_ pyemma/coordinates/pipelines.py
>   https://github.com/markovmodel/PyEMMA/pull/387/files#diff-6 (22)
> - _M_ pyemma/coordinates/tests/test_featurereader.py
>   https://github.com/markovmodel/PyEMMA/pull/387/files#diff-7 (123)
> - _M_ pyemma/coordinates/transform/pca.py
>   https://github.com/markovmodel/PyEMMA/pull/387/files#diff-8 (51)
> - _M_ pyemma/coordinates/transform/tica.py
>   https://github.com/markovmodel/PyEMMA/pull/387/files#diff-9 (132)
> - _M_ pyemma/msm/api.py
>   https://github.com/markovmodel/PyEMMA/pull/387/files#diff-10 (88)
> - _M_ pyemma/msm/flux/reactive_flux.py
>   https://github.com/markovmodel/PyEMMA/pull/387/files#diff-11 (78)
> - _M_ pyemma/msm/ui/msm.py
>   https://github.com/markovmodel/PyEMMA/pull/387/files#diff-12 (147)
> - _M_ pyemma/msm/ui/timescales.py
>   https://github.com/markovmodel/PyEMMA/pull/387/files#diff-13 (43)
>   
>   ```
>   Patch Links:
>   ```
> - https://github.com/markovmodel/PyEMMA/pull/387.patch
> - https://github.com/markovmodel/PyEMMA/pull/387.diff
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/387.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by clonker** [comment]
yes, sorry. Closing this PR and creating a new one once i rebased.

**Comment by marscher** [comment]
please do not waste pr numbers for fixing mistakes in the pr, but just
force push the correct version over the faulty branch!

**Comment by marscher** [comment]
Why should this be a rebase? My argument is that it makes no difference
at the end of the day (when we release the branch, we do a merge of
dev_rel into devel).

**Comment by marscher** [comment]
a rebase is just more complicated, since the history is applied one
patch after another and this causes much more conflicts than a merge.

**Comment by franknoe** [comment]
Because we will later merge dev_release_1.3 into devel, to have commits 
applied in the right order. I.e. the stuff in dev_release_1.3 will be 
all after the devel commits.

I don't think there will be conflicts for this merge either way.

Am 01/07/15 um 14:07 schrieb Martin K. Scherer:

> Why should this be a rebase? My argument is that it makes no difference
> at the end of the day (when we release the branch, we do a merge of
> dev_rel into devel).
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/pull/387#issuecomment-117635718.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Pull request closed without merging**
